<?php


namespace Src\Views\Music;


use JointApp\Interfaces\LangWebViewInterface;
use JointApp\Views\Records\RecordListView;

class View_Music extends RecordListView
{

    public $albumsList  = null;
    public $playAlb = null;
    public $trackList = null;

    const MUSIC_ALB_DIR = '/ddd-test/albCovers';
    const MUSIC_TRACKS_DIR = '/ddd-test/tracks';

    public string $logo = '/img/popimg/music-logo.png';
    public string $shortcutIcon = '/img/popimg/music-logo.png';

    public $robot_no_index = true;
    public $metrik_block = false;

    public static function addScriptLinks(callable $addScriptLinks): void
    {
        parent::addScriptLinks($addScriptLinks); // TODO: Change the autogenerated stub
        $addScriptLinks(['/js/music/musicgallery.js']);
    }

    public static function addStyleLinks(callable $addStyleLinks): void
    {
        parent::addStyleLinks($addStyleLinks); // TODO: Change the autogenerated stub
        $addStyleLinks(['/css/music/musicgallery.css']);
    }

    public static function loadLangView(string $docRoot = __DIR__, string $viewLang = 'ru', $loads = []): LangWebViewInterface
    {
        $name = 'LangFiles_'.self::langNs($viewLang).'_Views_Music';
        $loads[] = [$name => $docRoot.'/LangFiles/Views/Music/'.$name];
        return parent::loadLangView($docRoot, $viewLang, $loads);
    }

    public static function musicMenu(\stdClass $langPageContent):string
    {
        return '<div class="music-menu">'.
        self::musicNavMenu($langPageContent->navMenu).
        '</div>';
    }

    public static function musicNavMenu(\stdClass $navMenu):string
    {
        return '<div class="music-nav" id="music-nav-menu">'.
            '<span>'.$navMenu->nav_text.'</span>'.
            '<ul>'.
            '<li><a href="/music/albums">'.$navMenu->nav_alb.'</a></li>'.
            '<li><a href="/music/tracks">'.$navMenu->nav_tracks.'</a></li>'.
            '<li>'.'<a href="/music">'.$navMenu->nav_fresh.'</a>'.'</li>'.
            '</ul>'.
            '</div>';
    }

    public static function printMusicAlbum(\stdClass $albBlock, array $album):string
    {
        $return_text = '<div class="alb-block">'.
            '<div class="alb-name">'.$album['albumName'].'</div>'.
            '<div class="alb-cover"><a href="/music/album/'.$album['albumAlias'].'" title="play album">';
        if($album['albumImg']!=null){
            $return_text .='<img src="'.self::MUSIC_ALB_DIR.'/'.$album['albumImg'].'">';
        }else{
            $return_text .='<img src="/img/popimg/avatar-default.png" alt="no-cover">';
        }
        $return_text .='</a>'.
            '<div class="alb-count-tracks">'.
            '<span class="alb-info-name">'.$albBlock->alb_cnt_tracks_1.'</span>'.
            '<span class="alb-info-val">'.$album['countRec'].'</span>'.
            '<span class="alb-info-name">'.$albBlock->alb_cnt_tracks_2.'<span>'.
            '</div>'.
            '</div>'.
            '<div class="alb-descr">'.
            $album['metaDescr'].'</div>'.
            '<div class="alb-row3">'.
            '<span class="alb-info-name">'.$albBlock->alb_created_by.'</span>'.
            '<span class="alb-info-val">'.$album['alb_created'].'</span>'.
            '</div>'.
            '<div class="alb-row3">'.
            '<span class="alb-info-name">'.$albBlock->alb_created_date.'</span>'.
            '<span class="alb-info-val">'.$album['dateOfCr'].'</span>'.
            '</div>'.
            '<div class="alb-row3">'.
            '<span class="alb-info-name">'.$albBlock->alb_updated.'</span>'.
            '<span class="alb-info-val">'.$album['refreshDate'].'</span>'.
            '</div>'.
            '</div>';
        return $return_text;
    }

    public static function printMusicTracks(\stdClass $albBlock, array $listRecords = [])
    {
        $return_text = '<div class="ac-wrap">'.
            '<audio controls="controls" autoplay id="htmlMusicPlayer">'.
            '</audio>'.
            '</div>'.
            '<div class="tracks-list" id="music-album">';
        if(count($listRecords)){
            $return_text.= '<div class="track-line caption">'.
                '<div class="track-num">No</div>'.
                '<div class="track-artist">'.$albBlock->t_art.'</div>'.
                '<div class="track-name">'.$albBlock->t_song.'</div>'.
                '<div class="track-play">'.$albBlock->t_play.'</div>'.
                '</div>';

            $track_num = 0;

            foreach ($listRecords  as $num => $track_row){

                $print_track_file = $track_row['track_file'];
                if(strpos(' '.$track_row['track_file'], 'http', 0)!=1){
                    $print_track_file=self::MUSIC_TRACKS_DIR.'/'.$print_track_file;
                }

                $track_num++;
                $return_text.= '<div class="track-line">'.
                    '<div class="track-num">'.$track_num.'</div>'.
                    '<div class="track-artist">'.$track_row['track_artist'].'</div>'.
                    '<div class="track-name">'.
                    '<a href="'.$print_track_file.'">'.$track_row['track_name'].'</a>'.
                    '</div>'.
                    '<div class="track-play"><input type="button" value="Play"></div>'.
                    '</div>';
            }
        }

        $return_text.= '</div>';
        return $return_text;
    }
}