<?php
include "application/core/Records/RecordsController.php";
include "application/core/Module/ModuleRecordsController.php";

class Controller_Siteman extends ModuleRecordsController
{
    public $modules;

    function __construct()
    {
        $this->lang_map["menu-index-warning"] = array(
            "en" => "denied in controller siteman action index",
            "rus" => "Ошибка доступа в controller siteman action index",
        );

        $modulesInfo = null;
        require_once JOINT_CONF_DIR."/modulesInfo.php";

        $this->modules = $modulesInfo;

        parent::__construct();
    }

    function loadView($type_of_view, $process_path, $custom_name = null)
    {
        $loadedView = parent::loadView($type_of_view, $process_path, $custom_name); // TODO: Change the autogenerated stub

        $loadedView->robot_no_index = true;
        $loadedView->metrik_block = false;

        return $loadedView;
    }

    function action_groups()
    {
        $this->module_process("groups");
    }

    function action_users()
    {
        $this->module_process("users");
    }

    function action_notifications()
    {
        $this->module_process("notifications");
    }
}