<?php
class Controller_Main extends Controller
{
    function LoadModel_custom($action_name = null)
    {
        require_once $_SERVER["DOCUMENT_ROOT"].JOINT_SITE_EXEC_DIR.
            "/application/models/model_landing.php";
        return "model_landing";
    }

    function LoadView_custom($action_name = null)
    {
        require_once $_SERVER["DOCUMENT_ROOT"].JOINT_SITE_EXEC_DIR.
            "/application/views/landing_view.php";
        return "landing_view";
    }

    function action_index()
    {
        if(isset($_GET["lBasketAdd"])){
            $this->model->lBasketAdd();
            $this->view->basket_prod = $this->model->basketCalc();
            $modalOrder = $this->view->print_basket();
            if(isset($_SESSION[JS_SAIK]['basket']['total'])){
                $modalOrder["total"] = $_SESSION[JS_SAIK]['basket']['total'];
            }else{
                $modalOrder["total"] = 0;
            }

            $this->view->generateJson($modalOrder);
        }elseif(isset($_GET["basket-clear"])){
            unset($_SESSION[JS_SAIK]["basket"]);
        }else{
            $this->view->basket_prod = $this->model->basketCalc();
            parent::action_index(); // TODO: Change the autogenerated stub
        }
    }


}