<?php
include "application/views/view_notes.php";
class controller_notes extends Controller
{
    function __construct()
    {
        $this->model = new model_notes();
        $this->view = new view_notes();
    }

    function action_index()
    {
        parent::action_index(); // TODO: Change the autogenerated stub
    }
}