<?php
class Controller_Products extends Controller
{
    function LoadView_custom()
    {
        global $request;
        $custom_name = null;
        if ($request["routes"][$request["exec_dir_cnt"]+1] == "jointsite"){
            if(!empty($request["routes"][$request["exec_dir_cnt"]+2])){
                $try_name =  "View_".$request["routes"][$request["exec_dir_cnt"]+1]."_".
                    $request["routes"][$request["exec_dir_cnt"]+2];
                $try_path = $_SERVER["DOCUMENT_ROOT"].$request["exec_path"]."/application/views/".
                    $request["routes"][$request["exec_dir_cnt"]]."/".strtolower($try_name).'.php';
            }
        }
        if(file_exists($try_path)){
            require_once ($try_path);
            $custom_name = $try_name;
        }

        return $custom_name;
    }

    function action_jointsite()
    {
        parent::action_index(); // TODO: Change the autogenerated stub
    }
}