<?php

namespace Src\Views\Cv;



use JointApp\Interfaces\LangWebViewInterface;
use Src\Views\Blog\IT\SkillsTableTrait;

class View_Cv_Experience extends View_Cv_Main
{

    public bool $robotNoIndex = true;

    use SkillsTableTrait;

    public static function loadLangView(string $docRoot = __DIR__, string $viewLang = 'ru', $loads = []): LangWebViewInterface
    {
        $name = 'LangFiles_'.self::langNs($viewLang).'_Views_Cv_Experience';
        $loads[] = [$name => $docRoot.'/LangFiles/Views/Cv/'.$name];
        return parent::loadLangView($docRoot, $viewLang, $loads);
    }

    public static function addStyleLinks(callable $addStyleLinks): void
    {
        parent::addStyleLinks($addStyleLinks); // TODO: Change the autogenerated stub
        $addStyleLinks([
            '/css/cv/cv-experience.css',
        ]);
    }

    public static function cvExperience(\stdClass $langExp):string
    {
        return
            '<section class="cv-experience">'.
            '<h3>'.$langExp->h3.'</h3>'.
            '<div class="prevExp">'.
            '<p>'.$langExp->p1.'</p>'.
            '<p>'.$langExp->p2.'</p>'.
            '</div>'.
            '<div class="t-wrap">'.
            '<table>'.
            '<tr>'.
            '<td class="c-c1">'.$langExp->table->trc->c1.'</td>'.
            '<td class="c-c2">'.$langExp->table->trc->c2.'</td>'.
            '<td class="c-c3">'.$langExp->table->trc->c3.'</td>'.
            self::cvExperienceTkb($langExp->table->tr1).
            self::cvExperienceOkna($langExp->table->tr2).
            self::cvExperienceLider($langExp->table->tr3).
            '</table>'.
            '</div>'.
            '</section>';
    }

    public static function cvExperienceTkb(\stdClass $langTr1):string
    {
        return
            '<tr>'.
            '<td rowspan="3" class="c1">'.
            '<p class="cv-cell-company">'.$langTr1->c1->company.'</p>'.
            '<p class="cv-cell-role">'.$langTr1->c1->app.'</p>'.
            '<p class="cv-cell-date">'.$langTr1->c1->period.'</p>'.
            '<p class="cv-cell-dtDif">('.$langTr1->c1->dDiff.')</p>'.
            '</td>'.
            '<td class="c2">'.
            '<p class="cv-cell-pName">'.$langTr1->c2->p1Name.'</p>'.
            '<p>'.$langTr1->c2->p1Descr.'</p>'.
            '<p class="cv-cell-stack-c">'.$langTr1->c2->pStack.':</p>'.
            '<p>php, js, jQuery, Ajax, git, api, cron, linux</p>'.
            '</td>'.

            '<td class="c3">'.
            '<ul>'.
            '<li>'.$langTr1->c3->p1Li1.'</li>'.
            '<li>'.$langTr1->c3->p1Li2.'</li>'.
            '<li>'.$langTr1->c3->p1Li3.'</li>'.
            '<li>'.$langTr1->c3->p1Li4.'</li>'.
            '<li>'.$langTr1->c3->p1Li5.'</li>'.
            '<li>'.$langTr1->c3->p1Li6.'</li>'.
            '<li>'.$langTr1->c3->p1Li7.'</li>'.
            '<li>'.$langTr1->c3->p1Li8.'</li>'.
            '<li>'.$langTr1->c3->p1Li9.'</li>'.
            '<li>'.$langTr1->c3->p1Li10.'</li>'.
            '<li>'.$langTr1->c3->p1Li11.'</li>'.
            '</ul>'.
            '</td>'.
            '</tr>'.
            '<tr>'.
            '<td class="c2">'.
            '<p class="cv-cell-pName">'.$langTr1->c2->p2Name.'</p>'.
            '<p>'.$langTr1->c2->p2Descr.'</p>'.
            '<p class="cv-cell-stack-c">'.$langTr1->c2->pStack.':</p>'.
            '<p>Ansible, polemarch</p>'.
            '</td>'.
            '<td class="c3">'.
            '<ul>'.
            '<li>'.$langTr1->c3->p2Li1.'</li>'.
            '<li>'.$langTr1->c3->p2Li2.'</li>'.
            '<li>'.$langTr1->c3->p2Li3.'</li>'.
            '<li>'.$langTr1->c3->p2Li4.'</li>'.
            '</ul>'.
            '</td>'.
            '</tr>'.
            '<tr>'.
            '<td class="c2">'.
            '<p class="cv-cell-pName">'.$langTr1->c2->p3Name.'</p>'.
            '<p>'.$langTr1->c2->p3Descr.'</p>'.
            '<p class="cv-cell-stack-c">'.$langTr1->c2->pStack.':</p>'.
            '<p>Elasticsearch, logstash, kibana, devTool</p>'.
            '</td>'.
            '<td class="c3">'.
            '<ul>'.
            '<li>'.$langTr1->c3->p3Li1.'</li>'.
            '<li>'.$langTr1->c3->p3Li2.'</li>'.
            '<li>'.$langTr1->c3->p3Li3.'</li>'.
            '<li>'.$langTr1->c3->p3Li4.'</li>'.
            '</ul>'.
            '</td>'.
            '</tr>';
    }

    public static function cvExperienceOkna(\stdClass $langTr2):string
    {
        return

            '<tr>'.
            '<td class="c1" rowspan="2">'.
            '<p class="cv-cell-company">'.$langTr2->c1->company.'</p>'.
            '<p class="cv-cell-role">'.$langTr2->c1->app.'</p>'.
            '<p class="cv-cell-date">'.$langTr2->c1->period.'</p>'.
            '<p class="cv-cell-dtDif">'.$langTr2->c1->dDiff.'</p>'.
            '</td>'.
            '<td class="c2">'.
            '<p class="cv-cell-pName">'.$langTr2->c2->p1Name.'</p>'.
            '<p>'.$langTr2->c2->p1Descr.'</p>'.
            '<p class="cv-cell-stack-c">'.$langTr2->c2->pStack.':</p>'.
            '<p>php, mySql, javaScript, JQuery, Html, Windows</p>'.
            '</td>'.
            '<td class="c3">'.
            '<ul>'.
            '<li>'.$langTr2->c3->p1Li1.'</li>'.
            '<li>'.$langTr2->c3->p1Li2.'</li>'.
            '</ul>'.
            '</td>'.
            '</tr>'.
            '<tr>'.
            '<td class="c2">'.
            '<p class="cv-cell-pName">'.$langTr2->c2->p2Name.'</p>'.
            '<p>'.$langTr2->c2->p2Descr.'</p>'.
            '<p class="cv-cell-stack-c">'.$langTr2->c2->pStack.':</p>'.
            '<p>C#, WindowsForms, MsSql</p>'.
            '</td>'.
            '<td class="c3">'.
            '<ul>'.
            '<li>'.$langTr2->c3->p2Li1.'</li>'.
            '<li>'.$langTr2->c3->p2Li2.'</li>'.
            '</td>'.
            '</ul>'.
            '</tr>';
    }

    public static function cvExperienceLider(\stdClass $langTr3):string
    {
        return
            '<tr>'.
            '<td class="c1">'.
            '<p class="cv-cell-company">'.$langTr3->c1->company.'</p>'.
            '<p class="cv-cell-role">'.$langTr3->c1->app.'</p>'.
            '<p class="cv-cell-date">'.$langTr3->c1->period.'</p>'.
            '<p class="cv-cell-dtDif">'.$langTr3->c1->dDiff.'</p>'.
            '</td>'.
            '<td class="c2">'.
            '<p class="cv-cell-pName">'.$langTr3->c2->p1Name.'</p>'.
            '<p>'.$langTr3->c2->p1Descr.'</p>'.
            '<p class="cv-cell-stack-c">'.$langTr3->c2->pStack.':</p>'.
            '<p>php, MySql, javaScript, jQuery, cron, api, linux</p>'.
            '</td>'.
            '<td class="c3">'.
            '<ul>'.
            '<li>'.$langTr3->c3->p1Li1.'</li>'.
            '<li>'.$langTr3->c3->p1Li2.'</li>'.
            '<li>'.$langTr3->c3->p1Li3.'</li>'.
            '<li>'.$langTr3->c3->p1Li4.'</li>'.
            '<li>'.$langTr3->c3->p1Li5.'</li>'.
            '<li>'.$langTr3->c3->p1Li6.'</li>'.
            '<li>'.$langTr3->c3->p1Li7.'</li>'.
            '<li>'.$langTr3->c3->p1Li8.'</li>'.
            '<li>'.$langTr3->c3->p1Li9.'</li>'.
            '<li>'.$langTr3->c3->p1Li10.'</li>'.
            '</ul>'.
            '<p>'.$langTr3->c3->p1Ach.'</p>'.
            '</td>'.
            '</tr>';
    }
}