<?php

namespace Src\Views\Cv;



use JointApp\Interfaces\LangWebViewInterface;
use Src\Views\Blog\IT\SkillsTableTrait;

class View_Cv_Faq extends View_Cv_Main
{

    use SkillsTableTrait;

    public string $logo = '/img/popimg/cv-logo.png';
    public string $shortcutIcon = '/img/popimg/cv-logo.png';

    public static function loadLangView(string $docRoot = __DIR__, string $viewLang = 'ru', $loads = []): LangWebViewInterface
    {
        $name = 'LangFiles_'.self::langNs($viewLang).'_Views_Cv_FAQ';
        $loads[] = [$name => $docRoot.'/LangFiles/Views/Cv/'.$name];
        return parent::loadLangView($docRoot, $viewLang, $loads);
    }

    public static function addStyleLinks(callable $addStyleLinks): void
    {
        parent::addStyleLinks($addStyleLinks); // TODO: Change the autogenerated stub
        $addStyleLinks([
            '/css/cv/cv-faq.css',
        ]);
    }

    public static function cvContent(\stdClass $langCvContent):string
    {
        return self::cvFaq($langCvContent);
    }

    public static function cvFaq(\stdClass $langCvFaq):string
    {
        return '<div class="contentBlock-frame">'.
            '<div class="contentBlock-center"><div class="contentBlock-wrap">'.
            '<section class="cv-faq">'.
            '<h3>'.$langCvFaq->h3.'</h3>'.
            '<div class="cv-q">'.
            '<div class="cv-q-i">'.
            '<img src="/img/cv/question-logo.png">'.
            '</div>'.
            '<div class="cv-q-t">'.
            '<span>'.$langCvFaq->q1.'?</span>'.
            '</div>'.
            '<div class="cv-a">'.
            '<div class="cv-a-i">'.
            '<img src="/img/cv/answer-logo.png">'.
            '</div>'.
            '<div class="cv-a-t">'.
            '<p>'.$langCvFaq->a1.'</p>'.
            '</div>'.
            '</div>'.
            '</div>'.
            '<div class="cv-q">'.
            '<div class="cv-q-i">'.
            '<img src="/img/cv/question-logo.png">'.
            '</div>'.
            '<div class="cv-q-t">'.
            '<span>'.$langCvFaq->q2.'?</span>'.
            '</div>'.
            '<div class="cv-a">'.
            '<div class="cv-a-i">'.
            '<img src="/img/cv/answer-logo.png">'.
            '</div>'.
            '<div class="cv-a-t">'.
            '<p>'.$langCvFaq->a2.'</p>'.
            '</div>'.
            '</div>'.
            '</div>'.
            '<div class="cv-q">'.
            '<div class="cv-q-i">'.
            '<img src="/img/cv/question-logo.png">'.
            '</div>'.
            '<div class="cv-q-t">'.
            '<span>'.$langCvFaq->q3.'?</span>'.
            '</div>'.
            '<div class="cv-a">'.
            '<div class="cv-a-i">'.
            '<img src="/img/cv/answer-logo.png">'.
            '</div>'.
            '<div class="cv-a-t">'.
            //'<p>'.
            '<ul>'.
            '<li>'.$langCvFaq->a31.'</li>'.
            '<li>'.$langCvFaq->a32.'</li>'.
            '<li>'.$langCvFaq->a33.'</li>'.
            '<li>'.$langCvFaq->a34.'</li>'.
            '<li>'.$langCvFaq->a35.'</li>'.
            '<li>'.$langCvFaq->a36.'</li>'.
            '<li>'.$langCvFaq->a37.'</li>'.
            '</ul>'.
            //'</p>'.
            '</div>'.
            '</div>'.
            '</div>'.
            '<div class="cv-q">'.
            '<div class="cv-q-i">'.
            '<img src="/img/cv/question-logo.png">'.
            '</div>'.
            '<div class="cv-q-t">'.
            '<span>'.$langCvFaq->q4.'?</span>'.
            '</div>'.
            '<div class="cv-a">'.
            '<div class="cv-a-i">'.
            '<img src="/img/cv/answer-logo.png">'.
            '</div>'.
            '<div class="cv-a-t">'.
            //'<p>'.
            '<ul>'.
            '<li>'.$langCvFaq->a41.'</li>'.
            '<li>'.$langCvFaq->a42.'</li>'.
            '</ul>'.
            //'</p>'.
            '</div>'.
            '</div>'.
            '</div>'.
            '<div class="cv-q">'.
            '<div class="cv-q-i">'.
            '<img src="/img/cv/question-logo.png">'.
            '</div>'.
            '<div class="cv-q-t">'.
            '<span>'.$langCvFaq->q5.'?</span>'.
            '</div>'.
            '<div class="cv-a">'.
            '<div class="cv-a-i">'.
            '<img src="/img/cv/answer-logo.png">'.
            '</div>'.
            '<div class="cv-a-t">'.
            '<ul>'.
            '<li>'.$langCvFaq->a51.'</li>'.
            '<li>'.$langCvFaq->a52.'</li>'.
            '<li>'.$langCvFaq->a53.'</li>'.
            '</ul>'.
            '<p>'.$langCvFaq->a5p.'</p>'.
            '</div>'.
            '</div>'.
            '</div>'.
            '<div class="cv-q">'.
            '<div class="cv-q-i">'.
            '<img src="/img/cv/question-logo.png">'.
            '</div>'.
            '<div class="cv-q-t">'.
            '<span>'.$langCvFaq->q6.'?</span>'.
            '</div>'.
            '<div class="cv-a">'.
            '<div class="cv-a-i">'.
            '<img src="/img/cv/answer-logo.png">'.
            '</div>'.
            '<div class="cv-a-t">'.
            '<ul>'.
            '<li>'.$langCvFaq->a61.'</li>'.
            '<li>'.$langCvFaq->a62.'</li>'.
            '<li>'.$langCvFaq->a63.'</li>'.
            '</ul>'.
            '</div>'.
            '</div>'.
            '</div>'.
            '<div class="cv-q">'.
            '<div class="cv-q-i">'.
            '<img src="/img/cv/question-logo.png">'.
            '</div>'.
            '<div class="cv-q-t">'.
            '<span>'.$langCvFaq->q7.'n>'.
            '</div>'.
            '<div class="cv-a">'.
            '<div class="cv-a-i">'.
            '<img src="/img/cv/answer-logo.png">'.
            '</div>'.
            '<div class="cv-a-t">'.
            '<p>'.$langCvFaq->a7.'</p>'.
            '</div>'.
            '</div>'.
            '</div>'.
            '<div class="cv-q">'.
            '<div class="cv-q-i">'.
            '<img src="/img/cv/question-logo.png">'.
            '</div>'.
            '<div class="cv-q-t">'.
            '<span>'.$langCvFaq->q8.'?</span>'.
            '</div>'.
            '<div class="cv-a">'.
            '<div class="cv-a-i">'.
            '<img src="/img/cv/answer-logo.png">'.
            '</div>'.
            '<div class="cv-a-t">'.
            '<p>'.$langCvFaq->a8.'</p>'.
            '</div>'.
            '</div>'.
            '</div>'.
            '<div class="cv-q">'.
            '<div class="cv-q-i">'.
            '<img src="/img/cv/question-logo.png">'.
            '</div>'.
            '<div class="cv-q-t">'.
            '<span>'.$langCvFaq->q9.'?</span>'.
            '</div>'.
            '<div class="cv-a">'.
            '<div class="cv-a-i">'.
            '<img src="/img/cv/answer-logo.png">'.
            '</div>'.
            '<div class="cv-a-t">'.
            '<p>'.$langCvFaq->a9.'</p>'.
            '</div>'.
            '</div>'.
            '</div>'.
            '<div class="cv-q">'.
            '<div class="cv-q-i">'.
            '<img src="/img/cv/question-logo.png">'.
            '</div>'.
            '<div class="cv-q-t">'.
            '<span>'.$langCvFaq->q10.'?</span>'.
            '</div>'.
            '<div class="cv-a">'.
            '<div class="cv-a-i">'.
            '<img src="/img/cv/answer-logo.png">'.
            '</div>'.
            '<div class="cv-a-t">'.
            '<p>'.$langCvFaq->a10.'</p>'.
            '</div>'.
            '</div>'.
            '</div>'.
            '</section>';
    }
}