<?php

namespace Src\Views\Cv;

use JointApp\Views\SiteView;
use JointApp\Interfaces\LangWebViewInterface;
use Src\Views\Blog\IT\SkillsTableTrait;

class View_Cv_Main extends SiteView
{

    use SkillsTableTrait;

    public string $logo = '/img/popimg/cv-logo.png';
    public string $shortcutIcon = '/img/popimg/cv-logo.png';

    public static function loadLangView(string $docRoot = __DIR__, string $viewLang = 'ru', $loads = []): LangWebViewInterface
    {
        $name = 'LangFiles_'.self::langNs($viewLang).'_Views_Cv_Main';
        $loads[] = [$name => $docRoot.'/LangFiles/Views/Cv/'.$name];
        return parent::loadLangView($docRoot, $viewLang, $loads);
    }

    public static function addStyleLinks(callable $addStyleLinks): void
    {
        parent::addStyleLinks($addStyleLinks); // TODO: Change the autogenerated stub
        $addStyleLinks([
            '/css/cv/cv-header.css',
            '/css/cv/cv-menu.css',
        ]);
    }

    public static function createPageContent(\stdClass $langPageContent, \stdClass $viewParams):string
    {
        return
            '<div class="contentBlock-frame"><div class="contentBlock-center">'.
            '<div class="contentBlock-wrap">'.
            self::cvHeader($langPageContent->cvHeader).
            self::cvMenu($langPageContent->cvMenu, $viewParams->langSl, $viewParams->routes_ns).
            static::cvContent($langPageContent->cvContent).
            '</div>'.
            '</div>'.
            '</div>';
    }

    public static function cvHeader(\stdClass $langCvHeader):string
    {
        return
            '<div class="cv-header">'.
            '<div class="cv-header-row">'.
            '<div class="cv-header-role">'.
            '<div class="cv-header-role-title">'.$langCvHeader->title.'</div>'.
            '<div class="cv-header-role-skills">'.
            '<span>php</span>'.
            '<span>html</span>'.
            '<span>database</span>'.
            '<span>Apache</span>'.
            '<span>MySql</span>'.
            '<span>REST</span>'.
            '<span>SOLID</span>'.
            '<span>MVC</span>'.
            '<span>PSR</span>'.
            '<span>API</span>'.
            '<span>php-unit</span>'.
            '<span>phpStorm</span>'.
            '<span>Jquery</span>'.
            '<span>Ajax</span>'.
            '<span>Docker</span>'.
            '<span>Scrum</span>'.
            '<span>Ansible</span>'.
            '<span>Elasticsearch</span>'.
            '</div>'.
            '</div>'.
            '<div class="cv-header-img">'.
            '<img src="/img/cv/photo.jpg">'.
            '</div>'.
            '<div class="cv-header-contacts">'.
            '<div class="cv-header-contacts-line">'.
            '<span class="c-l-field">'.$langCvHeader->contacts->phoneLabel.'</span>'.
            '+7 (903) 888-7772'.
            '</div>'.
            '<div class="cv-header-contacts-line">'.
            '<span class="c-l-field">'.
            'E-Mail'.
            '</span>'.
            'rightjoint@yandex.ru'.
            '</div>'.
            '<div class="cv-header-contacts-line">'.
            '<span class="c-l-field">'.
            $langCvHeader->contacts->addressLabel.
            '</span>'.
            $langCvHeader->contacts->addressVal.
            '</div>'.
            '<div class="cv-header-contacts-line">'.
            '<span class="c-l-field">'.
            $langCvHeader->contacts->tgText.
            '</span>'.
            't.me/rightjoint'.
            '</div>'.
            '<div class="cv-header-contacts-line">'.
            '<span class="c-l-field">'.
            'Linkedin'.
            '</span>'.
            'linkedin.com/rightjoint'.
            '</div>'.
            '<div class="cv-header-contacts-line">'.
            '<span class="c-l-field">'.
            $langCvHeader->contacts->webLabel.
            '</span>'.
            'rightjoint.ru'.
            '</div>'.
            '</div>'.
            '</div>'.
            '</div>';
    }

    public static function cvMenu(\stdClass $langMenu, string $langSl, array $routes_ns):string
    {
        $return= '<div class="cv-menu">'.
            '<div class="cv-menu-row">'.
        '<div class="cv-menu-i';
        if(!isset($routes_ns[2])){
            $return.=' active';
        }
        $return.='">'.
        '<a href="'.$langSl.'/cv" title="'.$langMenu->expTitle.'">'.$langMenu->expText.'</a>'.
        '</div>'.
        '<div class="cv-menu-i';
        if(isset($routes_ns[2]) and $routes_ns[2] == 'skills'){
            $return.=' active';
        }
        $return.='">'.
        '<a href="'.$langSl.'/cv/skills" title="'.$langMenu->skillsTitle.'">'.$langMenu->skillsText.'</a>'.
        '</div>'.
        '<div class="cv-menu-i';
        if(isset($routes_ns[2]) and $routes_ns[2] == 'faq'){
            $return.=' active';
        }
        $return.='">'.
        '<a href="'.$langSl.'/cv/faq" title="'.$langMenu->faqTitle.'">'.$langMenu->faqText.'</a>'.
        '</div>'.
        '<div class="cv-menu-i">'.
        '<a href="'.$langSl.'/cv/faq" title="'.$langMenu->pdfTitle.'">'.$langMenu->pdfText.'</a>'.
        '</div>'.
        '</div>'.
        '</div>';
        return $return;
    }

    public static function cvContent(\stdClass $langCvContent):string
    {
        return static::cvExperience($langCvContent);
    }

    public static function cvExperience(\stdClass $langCvContent):string
    {
        return
            'Experience table';
    }
}