<?php


namespace JointApp\Models\User;


use JointApp\Models\ModuleModel;

class Model_User_Groups extends ModuleModel
{

    public string $tableName = 'usersToGroups_dt';

    public function checkAccessModel(): bool
    {
        $this->access_rules = array(
            "read_rule" => 7,
            "create_rule" => 7,
            "edit_rule" => 7,
            "delete_rule" => 7,
        );
        return true;
        //return parent::checkAccessModel(); // TODO: Change the autogenerated stub
    }

    public function getRecordStructure()
    {
        $this->record = array(
            'group_id' => array(
                'pri' => 1,
                'format' => 'varchar',
                'custom' => false,
            ),
            'user_id' => array(
                'pri' => 1,
                'format' => 'varchar',
                'custom' => false,
            ),
            'read_rule' => array(
                'format' => 'varchar',
                'custom' => false,
            ),
            'create_rule' => array(
                'format' => 'varchar',
                'custom' => false,
            ),
            'edit_rule' => array(
                'format' => 'varchar',
                'custom' => false,
            ),
            'delete_rule' => array(
                'format' => 'varchar',
                'custom' => false,
            ),
            'created_by' => array(
                'format' => 'varchar',
                'custom' => false,
            ),
            'send_ntf' => array(
                'format' => 'varchar',
                'custom' => false,
            ),
        );
    }

    public function getUserGroups(string $user_id = ''):bool
    {
        $return = false;
        if(!empty($user_id)){
            $this->record['user_id']['curVal'] = $user_id;
            return $this->copyRecord();
        }
        return $return;
    }

}