<?php
require_once "application/core/Records/RecordsView.php";
require_once "application/core/Records/RecordEditView.php";
require_once "application/core/Module/ModuleEditView.php";
class changePasswordView extends ModuleEditView
{
    public $logo = "/img/popimg/user-logo.png";
    public $shortcut_icon = "/img/popimg/checkInNow.png";

    public $user_modules = null;

    public function __construct()
    {
        $this->lang_map["view_submit_val"] = array(
            "en" => "Update",
            "rus" => "Обновить"
        );

        parent::__construct();

        include "application/core/Module/ModuleMenu.php";

    }

    function print_page_content()
    {
        echo moduleMenu::print_module_menu($this->user_modules);
        parent::print_page_content(); // TODO: Change the autogenerated stub
    }
}