<?php
class userNotificationDetailView extends ModuleDetailView
{
    public $logo = "/img/popimg/eye-icon.png";
    public $shortcut_icon = "/img/popimg/eye-icon.png";

    public $robot_no_index = true;
    public $metrik_block = false;

    function LoadViewLang_custom()
    {
        parent::LoadViewLang_custom(); // TODO: Change the autogenerated stub

        require_once $_SERVER["DOCUMENT_ROOT"] . JOINT_SITE_EXEC_DIR.
            "/application/lang_files/views/user/lang_view_user_ntf_d_".$_SESSION[JS_SAIK]["lang"].".php";
        return "lang_view_user_ntf_d_".$_SESSION[JS_SAIK]["lang"];
    }

    //function set_head_array()
   // {
     //   $this->lang_map->update_head_array($options = null);
        //parent::set_head_array(); // TODO: Change the autogenerated stub
   // }

    //function print_page_content()
    //{

        //parent::print_page_content(); // TODO: Change the autogenerated stub
    //}
}