<?php
class view_signup extends SiteView
{
    public $logo = JOINT_SITE_EXEC_DIR."/img/popimg/checkInNow.png";
    public $shortcut_icon = JOINT_SITE_EXEC_DIR."/img/popimg/checkInNow.png";

    public $robot_no_index = true;
    public $metrik_block = false;

    public $signUp_message;

    public $signUp_err = array(
        "login_unacceptable" => false,
        "login_reserved" => false,
        "pass_unacceptable" => false,
        "pass_dont_match" => false,
        "email_unacceptable" => false,
    );

    function print_auth_forms()
    {
        $this->print_signIn_form("disp-none");
        $this->print_signUp_form(null, $this->signUp_err);
    }

    function print_page_content()
    {
        $this->print_signUp_message();
        parent::print_page_content(); // TODO: Change the autogenerated stub
    }

    function print_signUp_message()
    {
        echo "<div class='contentBlock-frame'><div class='contentBlock-center'>".
            "<div class='contentBlock-wrap'>";
        echo $this->signUp_message;
        echo "</div></div></div>";
    }
}