<?php
require_once $_SERVER["DOCUMENT_ROOT"].JOINT_SITE_EXEC_DIR."/application/views/templates/RecordView.php";
require_once $_SERVER["DOCUMENT_ROOT"].JOINT_SITE_EXEC_DIR."/application/views/templates/RecordDetailView.php";
class view_trec_dv extends RecordDetailView
{
    function print_page_content()
    {
        echo "la-la-la";
        parent::print_page_content(); // TODO: Change the autogenerated stub
    }
}