<?php


namespace JointApp\Views\User;


use JointApp\Views\Records\RecordEditView;

class View_User_Main extends RecordEditView
{
    /*
    public $h2 = null;
    public string $process_url = '';
    public $fieldAliases = [];
    public bool|null $actionResult = null;
    public string|null $logMessage = '';
    public $editFields = [];
    public string $type = 'edit';
*/
    public static function createPageContent(\stdClass $langPageContent, \stdClass $viewParams): string
    {
        $subMenuItems = array(
            '' => array(
                'usage' => 1,
                'refTitle' => 'user main',
                'refText' => 'main info',
            ),
            'notifications' => array(
                'usage' => 1,
                'refTitle' => 'read notifications',
                'refText' => 'notifications',
            ),
            'changeEmail' => array(
                'usage' => 1,
                'refTitle' => 'change email',
                'refText' => 'email',
            ),
            'changePassword' => array(
                'usage' => 1,
                'refTitle' => 'change password',
                'refText' => 'password',
            ),
            'userGroups' => array(
                'usage' => 1,
                'refTitle' => 'groups settings',
                'refText' => 'groups',
            ),
        );

        $menuItems = self::printMenuItems($subMenuItems, '/user', $viewParams->langSl, $viewParams->routes_ns);

        //echo '<pre>';
        //print_r($menuItems);
        //exit;


        //return ModuleSubMenu::bindModuleMenu($viewParams->bindComponents, $viewParams->userModules, $langPageContent->modulesMenu, $viewParams->moduleName).
         return   parent::createPageContent($langPageContent, $viewParams); // TODO: Change the autogenerated stub
    }
}