<?php

namespace JointApp\Views\User;


use JointApp\Interfaces\LangWebViewInterface;
use JointApp\Views\SiteView;

class View_User_SignUp extends SiteView
{
    protected string $logo = '/img/popimg/checkInNow.png';
    public string $shortcutIcon = '/img/popimg/checkInNow.png';

    public $modalMenuActive = true;

    public $robot_no_index = true;
    public $metrik_block = false;

    public $registerResult = null;
    public string $validCode = '';

    public static function loadLangView(string $docRoot = __DIR__, string $viewLang = 'ru', $loads = []):LangWebViewInterface
    {
        $name = 'LangFiles_'.self::langNs($viewLang).'_Views_User_SignUp';
        $loads[] = [$name => $docRoot.'/JointApp/LangFiles/Views/User/'.$name];

        return parent::loadLangView($docRoot, $viewLang, $loads);
    }

    public function addViewParams(callable $addViewParams)
    {
        parent::addViewParams($addViewParams); // TODO: Change the autogenerated stub
        $viewParams = new \stdClass();
        $viewParams->registerResult = $this->registerResult;
        $viewParams->validCode = $this->validCode;
        $addViewParams($viewParams);
    }

    public static function createPageContent(\stdClass $langPageContent, \stdClass $viewParams): string
    {
        if(is_null($viewParams->registerResult)){
            return $langPageContent->registerDefault;
        }elseif ($viewParams->registerResult == true){
            //return $langPageContent->registerSussess;
            return $langPageContent->registerSussess.
                '<br>'.
                '<a href="/user/validate?vldCode='.$viewParams->validCode.'">ссылка</a>';
        }elseif ($viewParams->registerResult == false){
            return $langPageContent->registerFail;
        }
    }
}