<?php


namespace Src\Views\Blog\IT;


use Src\Views\Blog\View_Blog_Art;
use JointApp\Interfaces\LangWebViewInterface;


class View_Blog_IT_PhpJob2025 extends View_Blog_Art
{
    const JOINT_PASS_IMG = '/userdata/blog/IT/JointPass';

    public static function loadLangView(string $docRoot = __DIR__, string $viewLang = 'ru', $loads = []): LangWebViewInterface
    {
        $lang = 'LangFiles_' . self::langNs($viewLang) . '_Views_Blog_IT_JointPass';
        $loads[] = [$lang => $docRoot . '/LangFiles/Views/Blog/IT/' . $lang];
        return parent::loadLangView($docRoot, $viewLang, $loads);
    }

    public static function addStyleLinks(callable $addStyleLinks): void
    {
        parent::addStyleLinks($addStyleLinks); // TODO: Change the autogenerated stub
        $addStyleLinks([
            '/css/blog/joint-pass.css',
        ]);
    }

    public static function printArtContent(\stdClass $langArtContent, \stdClass $viewParams, string $langLw): string
    {
        return '<p>'.
            'Поиск работы разработчком php в 2025 году. Обзор вакансий, зарплат, требований, встреч с hr и собеседований.'.
            '</p>';
    }
}