<?php


namespace Src\Views\Blog\IT;


use Src\Views\Blog\View_Blog_Art;
use JointApp\Interfaces\LangWebViewInterface;


class View_Blog_IT_MultiLang extends View_Blog_Art
{
    public static function loadLangView(string $docRoot = __DIR__, string $viewLang = 'ru', $loads = []): LangWebViewInterface
    {
        $lang = 'LangFiles_' . self::langNs($viewLang) . '_Views_Blog_IT_TestTaskPhpJob';
        $loads[] = [$lang => $docRoot . '/LangFiles/Views/Blog/IT/' . $lang];
        return parent::loadLangView($docRoot, $viewLang, $loads);
    }

    public static function addStyleLinks(callable $addStyleLinks): void
    {
        parent::addStyleLinks($addStyleLinks); // TODO: Change the autogenerated stub
        $addStyleLinks([
            '/css/blog/code-snippet.css',
        ]);
    }

    public static function printArtContent(\stdClass $langArtContent, \stdClass $viewParams, string $langLw): string
    {
        return '<h3>Как сделать сайт многоязычным и отделить логику от языковых настроек</h3>'.
            '<p>'.
            'На pet-проекте я пошел по пути поддериктории (e.g. http://rightjoint.ru/<b>ru</b>/blog/article/make-website-multi-language) '.
            'так как этот способ является приемлемый с точки зрения seo и не требует '.
            'дополнительных затрат на регистрацию отдельных языковых доменов. '.
            'Мне было интересно не только отображать текст на страницах на разных языках, но ещё и выдавать ошибки приложения с переводом.'.
            '</p>'.
            '<p>'.
            'Все запросы к своему сайту я обрабатываю с помощью языкового адаптера (extends ServerRequest). '.
            'Таким образом маршрутизатор, контроллер, модель и представление не зависит от конкретного языка, а все переводы хранятся в '.
            'языковых файлах.'.
            '</p>'.
            '<p>'.
            'Адаптер разбирает адрес запроса. Для этого необходимо создать массив доступных языков и указать язык по умолчанию.'.
            '<ul>'.
            '<li>$acceptableLangs = ["en", "ru",] - это массив со списком языков приложения</li>'.
            '<li>$langDefault = "ru" - это язык по умолчанию, когда в адресе нет языковой ссылки '.
            'http://rightjoint.ru/blog/article/make-website-multi-language , и необходим для определения канонической страницы, '.
            'когда в адрес содержит язык по умолчанию</li>'.
            '</ul>'.
            '</p>'.
            '<p>'.
            'Существенными оказались следующие четыре настройки:'.
            '<table>'.
            '<tr><td colspan="1">Настройка</td><td></td><td>Диапазон значений</td><td>Назначение</td></tr>'.
            '<tr><td rowspan="1">$appLang</td><td>$langLw</td><td>"en", "ru",</td><td>для постановки в sql-запросы</td></tr>'.
            '<tr><td></td><td>$langNs</td><td>"En", "Ru",</td><td>для загрузки языковых файлов чтоб указать пространство имен</td></tr>'.
            '<tr><td colspan="1">$langSl</td><td></td><td>"/en", "/ru", or empty</td><td>для постановки в ссылки на представлениях, '.
            'для редиректа контроллером</td></tr>'.
            '<tr><td colspan="1">$langRef</td><td></td><td>/blog/article/make-website-multi-language</td>'.
            '<td>в маршрутизаторе, для постановки в ссылки на представлениях, для редиректа контроллером</td></tr>'.
            '<tr><td colspan="1">$langCanonical</td><td></td><td>true or false</td>'.
            '<td>на представлениях для отображения канонической ссылки</td></tr>'.
            '</table>'.
            '$langLw и $langNs определяются из $appLang который не может быть пустым'.
            '</p>'.
            '<h4>Маршруты</h4>'.
            '<p>'.
            'Мой маршрутизатор предварительно выбирает контроллер, модель и представление, не зависит от конкретного '.
            'языка и в него передается адрес $langRef без языковой части.'.
            '</p>'.
            '<p>'.
            'Контроллер: '.
            '<ul>'.
            '<li>$appLang'.
            '<ul>'.
            '<li>langNs - загрузка языковых файлов</li>'.
            '<li>langLw - в запросах к базе данных, чтоб создать view или модель с соответствующим языком</li>'.
            '</ul>'.
            '</li>'.
            '<li>langSl - во view для корректного отображения языковых ссылок ссылок, для редиректа в коде контроллера</li>'.
            '</ul>'.
            '</p>'.
            '<p>'.
            'Модель: '.
            '<p>'.
            'Моя модель не делает редиректов, по этому для неё достаточно одной настройки: '.
            '<ul>'.
            '<li>$appLang'.
            '<ul>'.
            '<li>langNs - загрузка языковых файлов</li>'.
            '<li>langLw - в запросах к базе данных</li>'.
            '</ul>'.
            '</li>'.
            '</ul>'.
            '</p>'.
            '<p>'.
            'Моя модель не содержит Request. Иногда одна модель может использовать внутри себя другую модель. Для этого я '.
            'использую фабрику чтоб создать модель с теми же языковыми настройками. '.
            '</p>'.
            '<h3>Запросы к базе данных</h3>'.
            '<p>'.
            'В контроллере и модели я использую алиасы для выбоки данных и having для фильтрации, так как это получается удобнее, например '.
            'select artMeta_".$langLw" as artMeta having artMeta="тест"'.
            '</p>'.
            '<p>'.
            'В представлении: '.
            '<ul>'.
            '<li>$langNs (En, Ru ) - загрузка языковых файлов</li>'.
            '<li>langLw (en, eu ) - на кнопке переключения языков</li>'.
            '<li>$langSl (en, eu ) - во view для корректного отображения языковых ссылок ссылок</li>'.
            '<li>$viewLang (en, ru or empty for default lang) - </li>'.
            '<li>$langRef (en, eu ) - это часть адреса запроса без языка, нужна для переключеня языков на языковой панели и для указания канонической страницы</li>'.
            '<li>$langCanonical (en, eu ) Эта часть важна для определения какнонической страницы</li>'.
            '</ul>'.
            '</p>'.
            '<p>'.
            '<h3>Языковые фалы для представлений</h3>'.
            '<p>'.
            'Все переводы для представлений я сохранияю в язвковых файлах в виде std-классов, методы которых могут перезаписыватся '.
            'и расширятся по принципам ООП. Для доступа к данным я использую статические функции чтоб печатать представление по частям'.
            '</p>'.
            '<div class="code-snippet">'.
            '<ul>'.
            '<li>cd ~/.PhpStorm[version]</li>'.
            '<li>rm config/eval/PhpStorm[version].evaluation.key</li>'.
            '<li><b>rm config/options</b></li>'.
            '<li>cd ~/.java/.userPrefs/jetbrains</li>'.
            '<li>rm -rf phpstorm</li>'.
            '</ul>'.
            '</div>'.
            '<h3>Загрузка языковых файлов</h3>'.
            '<p>'.
            'Lang files'.
            '</p>'.
            '<h3>Фабрики для модели, вывод представлений</h3>'.

            '<p>'.
            'Все '.
            'использую фабрику чтоб создать модель с теми же языковыми настройками. '.
            '</p>'.
            '<h3>Тесты чтоб не забыть делаем тесты</h3>'.
            '<p>'.
            'Lang files'.
            '</p>'.
            '<h3>Несколько примеров</h3>'.
            '<p>'.
            'Lang files'.
            '</p>'.
            '<h3>Выводы</h3>'.
            '<p>можно переводить представления кусочками, не обязательно все сразу. Этот способ достаточно хорош.</p>';
    }
}