<?php


namespace Src\Views\Blog\IT;


use Src\Views\Blog\View_Blog_Art;
use JointApp\Interfaces\LangWebViewInterface;


class View_Blog_IT_JointPass extends View_Blog_Art
{
    const JOINT_PASS_IMG = '/userdata/blog/IT/JointPass';

    public static function loadLangView(string $docRoot = __DIR__, string $viewLang = 'ru', $loads = []): LangWebViewInterface
    {
        $lang = 'LangFiles_' . self::langNs($viewLang) . '_Views_Blog_IT_JointPass';
        $loads[] = [$lang => $docRoot . '/LangFiles/Views/Blog/IT/' . $lang];
        return parent::loadLangView($docRoot, $viewLang, $loads);
    }

    public static function addStyleLinks(callable $addStyleLinks): void
    {
        parent::addStyleLinks($addStyleLinks); // TODO: Change the autogenerated stub
        $addStyleLinks([
            '/css/blog/joint-pass.css',
        ]);
    }

    public static function printArtContent(\stdClass $langArtContent, \stdClass $viewParams, string $langLw): string
    {
        return '<div class="contentBlock-frame"><div class="contentBlock-center">'.
            '<div class="contentBlock-wrap">'.
            '<section class="prod-about">'.
            '<p>'.
            $langArtContent->prod_about.
            '</p>'.
            '</section>'.
            '</div></div></div>'.


            '<div class="contentBlock-frame"><div class="contentBlock-center">'.
            '<div class="contentBlock-wrap">'.
            '<section class="prod-menu">'.
            '<h2>'.$langArtContent->product_info['h2_сontent'].'</h2>'.
            '<ul>'.
            '<li><a href="#product-downloads">'.$langArtContent->product_info['h2_dwl'].'</a></li>'.
            '<li><a href="#product-info">'.$langArtContent->product_info['h2_common'].'</a></li>'.
            '<li><a href="#product-craft">'.$langArtContent->product_info['h2_craft'].'</a></li>'.
            '<li><a href="#product-feedback">'.$langArtContent->product_info['h2_feedback'].'</a></li>'.
            '</ul>'.
            '</section>'.
            '</div></div></div>'.

            '<div class="contentBlock-frame"><div class="contentBlock-center">'.
            '<div class="contentBlock-wrap">'.
            '<section>'.
            '<h2 id="product-downloads">'.$langArtContent->product_info['h2_dwl'].'</h2>'.
            '<p>'.
            '<a class="dwl-img-link" href="/downloads/jointPass.zip" title="'.$langArtContent->jp_dwl['a_title'].' jointPass.zip">'.
            '<img src="'.self::JOINT_PASS_IMG.'/jointPass.png">jointPass.zip'.
            '</a>'.
            ' '.$langArtContent->jp_dwl['p1_txt1'].' <span class="ex-conf">jointPass.exe</span>. '.
            $langArtContent->jp_dwl['p1_txt2'].
            '</p>'.
            '<p>'.$langArtContent->jp_dwl['p2'].' <strong>aa653c47a6b6925441fb7faf0689eb3a</strong>'.
            '</p>'.
            '<div class="example">'.
            '<div class="example-code">'.
            'CertUtil -hashfile jointPass.exe MD5'.
            '</div>'.
            '<div class="example-code">'.
            'Хэш MD5 : jointPass.exe: aa653c47a6b6925441fb7faf0689eb3a'.
            '</div>'.
            '<div class="example-text">'.
            $langArtContent->jp_dwl['ex-text1'].
            '</div>'.
            '</div>'.
            '</p>'.
            '<p>'.$langArtContent->jp_dwl['p3'].'</p>'.
            '<div class="example">'.
            '<div class="example-code">'.
            'git clone https://github.com/rightJoint/jointpass'.
            '</div>'.
            '<div class="example-code">'.
            'git checkout main'.
            '</div>'.
            '<div class="example-text">'.
            $langArtContent->jp_dwl['ex-text2'].
            '</div>'.
            '</div>'.
            '</section>'.
            '</div></div></div>'.

            '<div class="contentBlock-frame"><div class="contentBlock-center">'.
            '<div class="contentBlock-wrap">'.
            '<section>'.
            '<h2 id="product-info">'.$langArtContent->product_info['h2_common'].'</h2>'.

            '<div class="branches-block">'.
            '<p>'.$langArtContent->jp_gui['p1'].'</p>'.
            '<p>'.$langArtContent->jp_gui['p2'].'</p>'.
            '<div class="example">'.
            "<div class='example-img'>".
            '<img src="'.self::JOINT_PASS_IMG.'/jp-signup_'.$langLw.'.png">'.
            '</div>'.
            '<div class="example-text">'.
            $langArtContent->jp_gui['example-text-1'].
            '</div>'.
            '</div>'.
            '<p>'.
            $langArtContent->jp_gui['p3'].
            '</p>'.
            '<p>'.
            $langArtContent->jp_gui['p4'].
            '</p>'.
            '<div class="example">'.
            '<div class="example-img">'.
            '<img src="'.self::JOINT_PASS_IMG.'/jp-change-pass_'.$langLw.'.png">'.
            '</div>'.
            '<div class="example-text">'.
            $langArtContent->jp_gui['example-text-2'].
            '</div>'.
            '</div>'.
            '<p>'.
            $langArtContent->jp_gui['p5'].
            '</p>'.
            '<div class="example">'.
            '<div class="example-img">'.
            '<img src="'.self::JOINT_PASS_IMG.'/jp-mainWin_'.$langLw.'.png">'.
            '</div>'.
            '<div class="example-text">'.
            $langArtContent->jp_gui['example-text-3'].
            '</div>'.
            '</div>'.
            '<p>'.
            $langArtContent->jp_gui['p6'].
            '</p>'.
            '<p>'.
            $langArtContent->jp_gui['p7'].
            '</p>'.
            '<p>'.
            $langArtContent->jp_gui['p8'].
            '</p>'.
            '<p>'.
            $langArtContent->jp_gui['p9'].
            '</p>'.
            '<div class="example">'.
            '<div class="example-img">'.
            '<img src="'.self::JOINT_PASS_IMG.'/jp-accFields_'.$langLw.'.png">'.
            '</div>'.
            '<div class="example-text">'.
            $langArtContent->jp_gui['example-text-4'].
            '</div>'.
            '</div>'.
            '<p>'.
            $langArtContent->jp_gui['p10'].
            '<p>'.
            $langArtContent->jp_gui['p11'].
            '</p>'.
            '<div class="example">'.
            '<div class="example-img">'.
            '<img src="'.self::JOINT_PASS_IMG.'/jp-group_'.$langLw.'.png">'.
            '</div>'.
            '<div class="example-text">'.
            $langArtContent->jp_gui['example-text-5'].
            '</div>'.
            '</div>'.
            '<p>'.
            $langArtContent->jp_gui['p12'].
            '</p>'.
            '<div class="example">'.
            '<div class="example-img">'.
            '<img src="'.self::JOINT_PASS_IMG.'/jp-cat_'.$langLw.'.png">'.
            '</div>'.
            '<div class="example-text">'.
            $langArtContent->jp_gui['example-text-6'].
            '</div>'.
            '</div>'.
            '<p>'.
            $langArtContent->jp_gui['p13'].
            '</p>'.
            '<div class="example">'.
            '<div class="example-img">'.
            '<img src="'.self::JOINT_PASS_IMG.'/jp-fields_'.$langLw.'.png">'.
            '</div>'.
            '<div class="example-text">'.
            $langArtContent->jp_gui['example-text-7'].
            '</div>'.
            '</div>'.
            '<p>'.
            $langArtContent->jp_gui['p14'].
            '</p>'.
            '<div class="example">'.
            '<div class="example-img">'.
            '<img src="'.self::JOINT_PASS_IMG.'/jp-acc_'.$langLw.'.png">'.
            '</div>'.
            '<div class="example-text">'.
            $langArtContent->jp_gui['example-text-8'].
            '</div>'.
            '</div>'.
            '</section>'.
            '</div></div></div>'.


            '<div class="contentBlock-frame"><div class="contentBlock-center">'.
            '<div class="contentBlock-wrap">'.
            '<section class="prod-deploy">'.
            '<h2 id="product-craft">'.$langArtContent->product_info['h2_craft'].'</h2>'.
            '<p>'.
            $langArtContent->jp_craft['p1'].
            '</p>'.
            '<p>'.
            $langArtContent->jp_craft['p2'].
            '</p>'.
            '<div class="example">'.
            '<div class="example-code">'.
            '4O5VjnGixFORFSNfwfZwSl+LDrkF3C98EiaY87EweKN7bKSSv3ER6U8rq03yx8rwsCCK5DrP6yrR0ED6oVttrlotC8Cqu4E4I8MCQqxwDu61U4PE/sOUrNkI9SSrAzqj'.
            '</div>'.
            '<div class="example-text">'.
            $langArtContent->jp_craft['example-text-1'].
            '</div>'.
            '</div>'.
            '<p>'.
            $langArtContent->jp_craft['p3'].
            '<p>'.
            $langArtContent->jp_craft['p4'].
            '</p>'.
            '<div class="example">'.
            '<div class="example-img">'.
            '<img src="'.self::JOINT_PASS_IMG.'/jp-dataFolder.png">'.
            '</div>'.
            '<div class="example-text">'.
            $langArtContent->jp_craft['example-text-2'].
            '</div>'.
            '</div>'.
            '<p>'.
            $langArtContent->jp_craft['p5'].
            '</p>'.
            '</section>'.
            '</div></div></div>'.

            '<div class="contentBlock-frame"><div class="contentBlock-center">'.
                 '<div class="contentBlock-wrap">'.
                 '<section style="margin-bottom: 4em">'.
                 '<h2 id="product-feedback">'.$langArtContent->product_info['h2_feedback'].'</h2>'.
                 '<p>'.$langArtContent->jp_feedback['p1'].' <span class="ex-conf">rightjoint@yandex.ru</span>'.
                 '</p>'.
                 '</section>'.
                 '</div></div></div>';
    }
}