<?php


namespace Src\Views\Blog\IT;


use Src\Views\Blog\View_Blog_Art;
use JointApp\Interfaces\LangWebViewInterface;


class View_Blog_IT_RightJointUpdated extends View_Blog_Art
{
    const JOINT_PASS_IMG = '/userdata/blog/IT/JointPass';

    public static function loadLangView(string $docRoot = __DIR__, string $viewLang = 'ru', $loads = []): LangWebViewInterface
    {
        $lang = 'LangFiles_' . self::langNs($viewLang) . '_Views_Blog_IT_RightJointUpdated';
        $loads[] = [$lang => $docRoot . '/LangFiles/Views/Blog/IT/' . $lang];
        return parent::loadLangView($docRoot, $viewLang, $loads);
    }

    public static function addStyleLinks(callable $addStyleLinks): void
    {
        parent::addStyleLinks($addStyleLinks); // TODO: Change the autogenerated stub
        $addStyleLinks([
            '/css/blog/joint-pass.css',
        ]);
    }

    public static function printArtContent(\stdClass $langArtContent, \stdClass $viewParams, string $langLw): string
    {
        return '<p>'.
            '<ol class="joint-site-about">'.
            '<li>Я постоянно развиваюсь в it-сфере и когда решаю какую-нибудь задачу или нахожу что-нибудь интересное, '.
            'то стараюсь поделиться этим в интернет. Таким образом этот сайт прежде всего нужен мне. Я могу использовать '.
            'его как тренировочный проект, привлекать единомышленников, так же заказчиков чтобы заработать '.
            'немного денег.</li>'.
            '<li>'.
            'Этот сайт может быть полезен моим постетителям и подписчикам. '.
            'В блоге вы можете найти ответы или развлекательный контент, задать ваши вопросы или обсудить тему. '.
            'Right Joint выступает на стороне безопасности, анонимности и свободы в интернет. '.
            '</li>'.
            '<li>'.
            'Мой сайт может быть интересен заказчикам, которые желают получить качественные услуги и передать '.
            'часть ответственности специалисту с опытом успешного решения сложных проблем.'.
            '</li>'.
            '</ol>'.
            '</p>'.
            '<style>'.
            '
            ol.joint-site-about{
            margin-top: 2em;
            margin-bottom: 2em;
            }
            ol.joint-site-about li{
            margin-top: 1em;
            margin-bottom: 1em;
                color: rgb(54, 54, 54);
    font-family: Karla, Arial, Helvetica, sans-serif;
            }'.
            '</style>';
    }
}