<?php


namespace JointApp\Models\Components;


use JointApp\Models\ModuleModel;
use JointApp\Models\Records\RecordsModel;

class Model_Components_MusicTracksToAlb extends ModuleModel
{
    public string $tableName = 'musicTracksToAlb';
    public string $moduleName = 'musictrackstoalb';

    public function getRecordStructure()
    {
        $this->record = array(
            'track_id' => array(
                'pri' => 1,
                'format' => 'varchar',
                'custom' => false,
            ),
            'album_id' => array(
                'pri' => 1,
                'format' => 'varchar',
                'custom' => false,
            ),
            'comment' => array(
                'format' => 'text',
                'custom' => false,
            ),
            'sortDate' => array(
                'format' => 'date',
                'custom' => false,
            ),
            'mActive' => array(
                'format' => 'tinyint',
                'custom' => false,
            ),
            'created_by' => array(
                'format' => 'varchar',
                'custom' => false,
            ),
/*
            'albumName' => array(
                'format' => 'popup',
                'options' => '',
                'use_table_name' => 'no-bd'
            )
*/
        );

        //return parent::getRecordStructure(); // TODO: Change the autogenerated stub
    }

    public function copyCustomFields(): bool
    {
        $this->record['albumName']['curVal'] = 'from - copyCustomFields';
        return true;
        //return parent::copyCustomFields(); // TODO: Change the autogenerated stub
    }
}