<?php


namespace JointApp\Models\Components;


use JointApp\JointAppQueryBuilder;
use JointApp\Models\ModuleModel;

class Model_Components_BlogTagsToArts extends ModuleModel
{
    public string $tableName = 'blogAtrTags';

    public string $moduleName = 'blogtagstoarts';

    public function getRecordStructure()
    {
        $this->record = array(
            'art_id' => array(
                'pri' => 1,
                'format' => 'varchar',
                'custom' => false,
            ),
            'tag_id' => array(
                'pri' => 1,
                'format' => 'varchar',
                'custom' => false,
            ),
            'created_by' => array(
                'format' => 'varchar',
                'custom' => false,
            ),
        );
    }

    public function listRecords(JointAppQueryBuilder $qBuilder): array
    {
        $qBuilder
            ->select(
                $this->tableName.'.art_id, '.
                $this->tableName.'.tag_id, '.
                $this->tableName.'.created_by, '.
                'blogArts.artName_'.$this->langLw.' as artName, '.
                'blogTags.tag_'.$this->langLw.' as tagName '
            )
            ->from($this->tableName)
            ->join(
                'left join blogArts on '.$this->tableName.'.art_id = blogArts.art_id '.
                'left join blogTags on '.$this->tableName.'.tag_id = blogTags.tag_id '
            );

        return $this->fetchToArray($qBuilder->buildQuery());
    }

    public function countRecords(JointAppQueryBuilder $qBuilder): int
    {
        return parent::countRecords($qBuilder); // TODO: Change the autogenerated stub
    }
}