<?php


namespace JointApp\Models\Components;


use JointApp\JointAppQueryBuilder;
use JointApp\Models\ModuleModel;

class Model_Components_MusicTracksToAlb extends ModuleModel
{
    public string $tableName = 'musicTracksToAlb';
    public string $moduleName = 'musictrackstoalb';

    public function getRecordStructure()
    {
        $this->record = array(
            'track_id' => array(
                'pri' => 1,
                'format' => 'varchar',
                'custom' => false,
            ),
            'album_id' => array(
                'pri' => 1,
                'format' => 'varchar',
                'custom' => false,
            ),
            'comment' => array(
                'format' => 'text',
                'custom' => false,
            ),
            'sortDate' => array(
                'format' => 'date',
                'custom' => false,
            ),
            'mActive' => array(
                'format' => 'tinyint',
                'custom' => false,
            ),
            'created_by' => array(
                'format' => 'varchar',
                'custom' => false,
            ),
        );
    }

    public function listRecords(JointAppQueryBuilder $qBuilder): array
    {

        $qBuilder->select = $this->tableName.'.track_id, '.$this->tableName.'.album_id, '.
            $this->tableName.'.comment, '.$this->tableName.'.sortDate, '.$this->tableName.'.mActive, '.
            $this->tableName.'.created_by, users_dt.accAlias, musicTracks.track_name, musicAlb.albumName ';
        $qBuilder
            ->from($this->tableName)
            ->join('left join users_dt on '.$this->tableName.'.created_by = users_dt.user_id '.
                'left join musicTracks on '.$this->tableName.'.track_id = musicTracks.track_id '.
                'left join musicAlb on '.$this->tableName.'.album_id = musicAlb.album_id');
                return $this->fetchToArray($qBuilder->buildQuery());
    }

    public function countRecords(JointAppQueryBuilder $qBuilder): int
    {
        $qBuilder->select = 'COUNT(*) as cnt';
        $qBuilder
            ->from($this->tableName)
            ->join('left join users_dt on '.$this->tableName.'.created_by = users_dt.user_id '.
                'left join musicTracks on '.$this->tableName.'.track_id = musicTracks.track_id '.
                'left join musicAlb on '.$this->tableName.'.album_id = musicAlb.album_id');
        return parent::countRecords($qBuilder); // TODO: Change the autogenerated stub
    }
}