<?php


namespace JointApp\Models\Components;


use JointApp\JointAppQueryBuilder;
use JointApp\Models\ModuleModel;

class Model_Components_MusicTracks extends ModuleModel
{
    public string $moduleName = 'musictracks';
    public string $tableName = 'musicTracks';

    const MUSIC_TRACKS_DIR = '/userdata/music/tracks';

    public function getRecordStructure()
    {
        $this->record = array(
            'track_id' => array(
                'pri' => 1,
                'format' => 'varchar',
                'custom' => false,
            ),
            'track_name' => array(
                'format' => 'varchar',
                'custom' => false,
            ),
            'track_artist' => array(
                'format' => 'varchar',
                'custom' => false,
            ),
            'track_file' => array(
                'format' => 'file',
                'custom' => false,
                'file_options' => array(
                    'accept' => 'mp3',
                    'load_dir' => self::MUSIC_TRACKS_DIR.'/track_file',
                    'replaces' => ['track_file'],
                ),
            ),
            'loadDate' => array(
                'format' => 'date',
                'custom' => false,
            ),
            'sortDate' => array(
                'format' => 'date',
                'custom' => false,
            ),
            'created_by' => array(
                'format' => 'varchar',
                'custom' => false,
            ),
            'created_alias' => array(
                'format' => 'varchar',
                'custom' => true,
            ),
        );
    }

    public function copyCustomFields(): bool
    {
        $findCreatedAlias_qry = 'select accAlias from users_dt where created_by="'.$this->record['created_by']['curVal'].'"';
        $findCreatedAlias_arr = $this->fetchToArray($findCreatedAlias_qry);
        if(count($findCreatedAlias_arr)){
            $this->record['created_alias']['curVal'] = $findCreatedAlias_arr[0]['accAlias'];
        }
        return true;
    }

    public function listRecords(JointAppQueryBuilder $qBuilder): array
    {
        $qBuilder = $this->createdByListWhere($qBuilder);
        $qBuilder->select = $this->tableName.'.track_id, '.$this->tableName.'.track_name, '.
            $this->tableName.'.track_artist, '.$this->tableName.'.track_file, '.$this->tableName.'.loadDate, '.
            $this->tableName.'.sortDate, '.$this->tableName.'.created_by, '.
            'users_dt.accAlias ';
        $qBuilder
            ->from($this->tableName)
            ->join('left join users_dt on '.$this->tableName.'.created_by = users_dt.user_id');

        return $this->checkListButtons($this->fetchToArray($qBuilder->buildQuery()));
    }

    public function countRecords(JointAppQueryBuilder $qBuilder): int
    {
        $qBuilder = $this->createdByListWhere($qBuilder);
        $qBuilder->select = 'COUNT(*) as cnt';
        $qBuilder
            ->from($this->tableName)
            ->join('left join users_dt on '.$this->tableName.'.created_by = users_dt.user_id');
        return parent::countRecords($qBuilder); // TODO: Change the autogenerated stub
    }
}