<?php


namespace JointApp\Models\Components;


use JointApp\JointAppQueryBuilder;
use JointApp\Models\ModuleModel;

class Model_Components_MusicTracksToAlb extends ModuleModel
{
    public string $tableName = 'musicTracksToAlb';
    public string $moduleName = 'musictrackstoalb';

    public function getRecordStructure()
    {
        $this->record = array(
            'track_id' => array(
                'pri' => 1,
                'format' => 'varchar',
                'custom' => false,
            ),
            'album_id' => array(
                'pri' => 1,
                'format' => 'varchar',
                'custom' => false,
            ),
            'comment' => array(
                'format' => 'text',
                'custom' => false,
            ),
            'sortDate' => array(
                'format' => 'date',
                'custom' => false,
            ),
            'mActive' => array(
                'format' => 'tinyint',
                'custom' => false,
            ),
            'created_by' => array(
                'format' => 'varchar',
                'custom' => false,
            ),
            'created_alias' => array(
                'format' => 'varchar',
                'custom' => true,
            ),
        );
    }

    public function listRecords(JointAppQueryBuilder $qBuilder): array
    {

        $qBuilder->select = $this->tableName.'.track_id, '.$this->tableName.'.album_id, '.
            $this->tableName.'.comment, '.$this->tableName.'.sortDate, '.$this->tableName.'.mActive, '.
            $this->tableName.'.created_by, users_dt.accAlias, musicTracks.track_name, musicAlb.albumName ';
        $qBuilder
            ->from($this->tableName)
            ->join('left join users_dt on '.$this->tableName.'.created_by = users_dt.user_id '.
                'left join musicTracks on '.$this->tableName.'.track_id = musicTracks.track_id '.
                'left join musicAlb on '.$this->tableName.'.album_id = musicAlb.album_id');
                return $this->fetchToArray($qBuilder->buildQuery());
    }

    public function countRecords(JointAppQueryBuilder $qBuilder): int
    {
        $qBuilder->select = 'COUNT(*) as cnt';
        $qBuilder
            ->from($this->tableName)
            ->join('left join users_dt on '.$this->tableName.'.created_by = users_dt.user_id '.
                'left join musicTracks on '.$this->tableName.'.track_id = musicTracks.track_id '.
                'left join musicAlb on '.$this->tableName.'.album_id = musicAlb.album_id');
        return parent::countRecords($qBuilder); // TODO: Change the autogenerated stub
    }

    public function copyCustomFields(): bool
    {
        $findCreatedAlias_qry = 'select accAlias from users_dt where created_by="'.$this->record['created_by']['curVal'].'"';
        $findCreatedAlias_arr = $this->fetchToArray($findCreatedAlias_qry);
        if(count($findCreatedAlias_arr)){
            $this->record['created_alias']['curVal'] = $findCreatedAlias_arr[0]['accAlias'];
        }

        $findTrackName_qry = 'select track_name from musicTracks where track_id="'.$this->record['track_id']['curVal'].'"';
        $findTrackName_arr = $this->fetchToArray($findTrackName_qry);
        if(count($findTrackName_arr)){
            $this->record['track_id']['findVal'] = $findTrackName_arr[0]['track_name'];
        }

        $findAlbName_qry = 'select albumName from musicAlb where album_id="'.$this->record['album_id']['curVal'].'"';
        $findAlbName_arr = $this->fetchToArray($findAlbName_qry);
        if(count($findAlbName_arr)){
            $this->record['album_id']['findVal'] = $findAlbName_arr[0]['albumName'];
        }
        return true;
        //return parent::copyCustomFields(); // TODO: Change the autogenerated stub
    }
}