<?php
require_once $_SERVER["DOCUMENT_ROOT"]."/application/recordsStructureFiles/test/rsf_musictrackstoalb.php";
class Model_Test_Records_Musictrackstoalb extends RecordsModel
{
    public $tableName = "rjt_musicTracksToAlb";

    public $albTable = "rjt_musicAlb";
    public $tracksTable = "rjt_musicTracks";


    public $modelAliases = array(
        "en" => "music tracks to albums",
        "rus" => "мелодии в альбом"
    );

    function getRecordStructure()
    {
        $this->recordStructureFields = new rsf_musictrackstoalb();
        $this->recordStructureFields->record["track_name"]["use_table_name"] =
        $this->recordStructureFields->record["albumName"]["use_table_name"] =
        $this->recordStructureFields->searchFields["track_name"]["use_table_name"] = $this->tracksTable;
        $this->recordStructureFields->searchFields["albumName"]["use_table_name"] = $this->albTable;
    }

    function copyCustomFields()
    {
        $albName_qry = "select albumName from ".$this->albTable." where album_id = '".$this->recordStructureFields->record["album_id"]["curVal"]."'";
        $albName_res = $this->query($albName_qry);
        if($albName_res->rowCount() == 1){
            $this->recordStructureFields->record["albumName"]["curVal"] = $albName_res->fetch(self::FETCH_ASSOC)["albumName"];
        }

        $trackName_qry = "select track_name from ".$this->tracksTable." where track_id = '".$this->recordStructureFields->record["track_id"]["curVal"]."'";
        $trackName_res = $this->query($trackName_qry);
        if($trackName_res->rowCount() == 1){
            $this->recordStructureFields->record["track_name"]["curVal"] = $trackName_res->fetch(self::FETCH_ASSOC)["track_name"];
        }

        return true;
    }

    public function listRecords($where = null, $order = null, $limit = null, $having = null)
    {
        $findList_qry = "select ".$this->tableName.".track_id, 
".$this->tableName.".album_id, 
".$this->tableName.".comment,
".$this->tableName.".mActive,
".$this->tableName.".sortDate, 
".$this->tracksTable.".track_name, 
".$this->tracksTable.".track_artist, 
".$this->tracksTable.".loadDate, 
".$this->albTable.".albumName, 
".$this->albTable.".albumImg 
from ".$this->tableName." 
left join ".$this->tracksTable." on ".$this->tracksTable.".track_id = ".$this->tableName.".track_id 
left join ".$this->albTable." on ".$this->tableName.".album_id = ".$this->albTable.".album_id  ".
            $where.$order.$limit;

        return $this->fetchToArray($findList_qry);
    }

    public function countRecords($where = null)
    {
        return $this->query("SELECT COUNT(*) as cnt from ".$this->tableName." ".
            "left join ".$this->tracksTable." on ".$this->tracksTable.".track_id = ".$this->tableName.".track_id 
left join ".$this->albTable." on ".$this->tableName.".album_id = ".$this->albTable.".album_id  ".
            $where)->fetch(PDO::FETCH_ASSOC)["cnt"];
    }

    function copyGetId()
    {
        parent::copyGetId();
        $this->copyCustomFields();
    }

    function insertRecord()
    {
        if($this->recordStructureFields->record["album_id"]["curVal"]){
            return parent::insertRecord(); // TODO: Change the autogenerated stub
        }
    }
}