<?php


namespace JointApp\Controllers\Components;


use JointApp\Controllers\ModuleController;
use JointApp\Models\Components\Model_Components_UsersToGroups;
use JointApp\Views\Records\RecordListView;

class Controller_Components_Groups extends ModuleController
{

    public string $moduleName = 'groups';

    public string $processUri = '/siteman/groups';

    public function loadBindComponents(): void
    {
        //echo 'Load-bind';
        $this->bindComponents = array(
            "userstogroups" => array(
                "relationships" => array(
                    "user_id" => "user_id",
                ),
            ),
            "users" => [],
            //"musicalb" => [],
        );
    }

    public function loadLangController():string
    {
        parent::loadLangController();
        $name = 'LangFiles_'.$this->langNs.'_Controller_Components_Groups';
        require_once $this->docRoot.'/JointApp/LangFiles/Controllers/Components/'.$name.'.php';
        return $name;
    }

    public function getDetailView(): void
    {

        parent::getDetailView(); // TODO: Change the autogenerated stub
        /*
                $usersToGroupsModel = new Model_Components_UsersToGroups($this->getRequest());
                $usersToGroupListView = new RecordListView($this->docRoot);

                $viewLang = $usersToGroupListView::loadLangView($this->docRoot);
                $viewLangPageContent = $viewLang::getLangPageContent();
        */
        /*
        echo '<pre>';
        print_r($viewLangPageContent->fiterView);
        exit;

        $viewParams->curPage = $this->viewCurPage;
        $viewParams->onPage = $this->viewOnPage;
        $viewParams->list_frame_id = $this->model->tableName;
        if(isset($this->model->langMap->modelAlias)){
            $viewParams->h2=$this->model->langMap->modelAlias;
        }else{
            $viewParams->h2 = $this->model->tableName;
        }
        $this->view->process_url = $this->processUri;
        if(isset($this->langMap->fieldAliases)){
            $viewParams->fieldAliases = $this->langMap->fieldAliases;
        }
        //create fieldAliases from model
        else{
            foreach ($this->model->record as $fN => $fOpt){
                $this->view->fieldAliases[$fN] = $fN;
            }
        }
*/
        /*
                $usersToGroupsController = new Controller_Components_UsersToGroups($this->getRequest(), $usersToGroupsModel, $usersToGroupListView);
                $usersToGroupsController->applyFilterRecord = true;
                $usersToGroupsController->applyFilterView();

                echo '<pre>';
                print_r($usersToGroupListView->responseJson);
                exit;
                //$usersToGroupListView::listView($viewLangPageContent->fiterView, );
        */

    }

    public function prepareEditFields(): void
    {
        $this->editFields = array(
            'group_id' => array(
                'format' => 'varchar',
                'curVal'=>'',
                'pri'=>1,
                'readonly' => true,
            ),
            'groupAlias_en' => array(
                'format' => 'varchar',
                'curVal' => '',
                'accept' => '/.{1,}/'
            ),
            'groupAlias_ru' => array(
                'format' => 'varchar',
                'curVal' => '',
                'accept' => '/.{1,}/'
            ),
            'activeFlag' => array(
                'format' => 'tinyint',
                'curVal' => false,
            ),
            'created_by' => array(
                'format' => 'hidden',
                'curVal' => '',
                'readonly' => true,
            ),
            'createdUser' => array(
                'format' => 'varchar',
                'curVal' => '',
                'readonly' => true,
            )

        );
    }

    public function prepareSearchFields(): void
    {
        $this->searchFields = array(
            'group_id' => array(
                'search' => 1,
                'sort' => 1,
                'format' => 'varchar',
            ),
            'groupAlias_en' => array(
                'search' => 1,
                'sort' => 1,
                'format' => 'varchar',
            ),
            'groupAlias_ru' => array(
                'search' => 1,
                'sort' => 1,
                'format' => 'varchar',
            ),
            'activeFlag' => array(
                'search' => 1,
                'sort' => 1,
                'format' => 'tinyint',
            ),

            'created_by' => array(
                'search' => 1,
                'sort' => 1,
                'format' => 'varchar',
            ),
            /*
            'createdUser' => array(
                'search' => 1,
                'sort' => 1,
                'format' => 'varchar',
            ),
            */
        );
    }

    public function prepareListFields(): void
    {
        $this->prepareListButtons();
        $this->listFields['group_id'] = ['format' => 'varchar'];
        $this->listFields['groupAlias_en'] = ['format' => 'varchar'];
        $this->listFields['groupAlias_ru'] = ['format' => 'varchar'];
        $this->listFields['activeFlag'] = ['format' => 'tinyint'];
        $this->listFields['created_by'] = ['format' => 'varchar'];
    }


}