<?php


namespace JointApp\Controllers\Components;


use JointApp\Controllers\Controller;
use JointApp\Controllers\ModuleController;
use JointApp\Factories\ModelFactory;
use JointApp\Models\Components\Model_Components_MusicTracksToAlb;
use JointApp\Models\Components\Model_Components_User;
use JointApp\Models\Model_Pdo;
use JointApp\Views\Records\RecordListView;
use JointApp\Views\WebView;

class Controller_Components_MusicAlb extends ModuleController
{
    public string $processUri = '/siteman/musicalb';

    public string $moduleName = 'musicalb';

    const MUSIC_ALB_DIR = '/ddd-test/albCovers';

    public function loadBindComponents(): void
    {
        $this->bindComponents = array(
            "musictrackstoalb" => array(
                "relationships" => array(
                    "album_id" => "album_id",
                ),
            ),
            "musictracks" => [],
        );
    }

    public function getDetailView(): void
    {
        parent::getDetailView(); // TODO: Change the autogenerated stub


        //$defaultModel = new Model();
        //$defautView = new View();

        $bindComponents[] = array(
            'model' => 'JointApp\Models\Components\Model_Components_MusicTracksToAlb',
            'controller' => 'JointApp\Controllers\Components\Controller_Components_MusicTracksToAlb',
        );

        $bindComponents[] = array(
            'model' => 'JointApp\Models\Components\Model_Components_User',
            'controller' => 'JointApp\Controllers\Components\Controller_Components_Users',
        );


       // echo '<pre>';
       // print_r($bindComponents);

        $addAfterText = '';
        foreach ($bindComponents as $kN=>$kOpt){
            $mName = $kOpt['model'];
            $cName = $kOpt['controller'];


            $bindModel = ModelFactory::createFromExistModel($mName, $this->model);

            //$bindModel = new $mName($this->getRequest());
            $redordList_view = new RecordListView($this->docRoot);
            $bindController = new $cName($this->getRequest(), $bindModel, $redordList_view);


            $viewLang_name = $redordList_view::loadLangView($this->docRoot, $this->langLw);
            $viewLang = new $viewLang_name;
            $viewLang_pageContent = $viewLang::getLangPageContent();

            $bindController->prepareSearchFields();
            $bindController->prepareListFields();

            $listRec_arr = $bindController->getListRecords();



            $viewParams = new \stdClass();
            $viewParams->listFields = $bindController->listFields;
            //$viewParams->searchFields = $bindController->searchFields;
            $viewParams->listRecords = $listRec_arr['list'];
            $viewParams->fieldAliases = [];

            $viewParams->langSl = $bindController->langSl;
            $viewParams->process_url = $bindController->processUri;
            $viewParams->list_frame_id = $bindController->model->tableName;
            $viewParams->listCount = $listRec_arr['count'];
            $viewParams->curPage = $bindController->viewCurPage;
            $viewParams->onPage = $bindController->viewOnPage;
            $viewParams->h2 = $bindModel->tableName;
            $viewParams->onPage_list = ['10', '20', '50'];

            $viewParams->searchFields = $bindController->searchFields;

            $viewParams->hasAccessCreate = $redordList_view->hasAccessCreate ;
            $viewParams->slave_req  = 'album_id='.$this->model->record['album_id']['curVal'];
            $viewParams->newBtn_qry  = $redordList_view->newBtn_qry  ;


            $addAfterText.= $redordList_view::listView($viewLang_pageContent->fiterView, $viewParams);

        }
        $this->view->putPageContentAfter($addAfterText);
    }

    public function prepareListFields(): void
    {
        $this->listFields = array(
            'btnDetail' => array(
                'replaces' => ['album_id'],
                'format' => 'link',
                'url' => 'album_id=album_id',
            ),
            'btnEdit' => array(
                'replaces' => ['album_id'],
                'format' => 'link',
                'url' => 'album_id=album_id',
            ),
            'btnDelete' => array(
                'replaces' => ['album_id'],
                'format' => 'link',
                'url' => 'album_id=album_id',
            ),
            'album_id' => array(
                'format' => 'varchar',
            ),
            'albumName' => array(
                'format' => 'varchar',
            ),
            'albumAlias' => array(
                'format' => 'varchar',
            ),
            'metaDescr' => array(
                'format' => 'varchar',
            ),
            'dateOfCr' => array(
                'format' => 'date',
            ),
            'albumImg' => array(
                'format' => 'file',
                'file_options' => array(
                    "load_dir" => self::MUSIC_ALB_DIR,
                    "file_type" => "img",
                ),
            ),
            'activeFlag' => array(
                'format' => 'tinyint',
            ),
            'refreshDate' => array(
                'format' => 'date',
            ),
            'robIndex' => array(
                'format' => 'tinyint',
            ),
            'created_by' => array(
                'format' => 'varchar',
            ),
        );
    }

    public function prepareEditFields(): void
    {
        $this->editFields = array(
            'album_id' => array(
                'pri' => 1,
                'format' => 'varchar',
                'curVal' => '',
            ),
            'albumName' => array(
                'format' => 'varchar',
                'curVal' => '',
            ),
            'albumAlias' => array(
                'format' => 'varchar',
                'curVal' => '',
            ),
            'metaDescr' => array(
                'format' => 'varchar',
                'curVal' => '',
            ),
            'dateOfCr' => array(
                'format' => 'date',
                'curVal' => '',
            ),
            'albumImg' => array(
                'format' => 'file',
                'file_options' => array(
                    "load_dir" => self::MUSIC_ALB_DIR,
                    'file_type' => 'img',
                    'accept' => '.jpg, .jpeg, .bmp, .git, .png',
                ),
                'with_name' => 'GUID',
                'curVal' => '',
            ),
            'activeFlag' => array(
                'format' => 'tinyint',
                'curVal' => '',
            ),
            'refreshDate' => array(
                'format' => 'date',
                'curVal' => '',
            ),
            'robIndex' => array(
                'format' => 'tinyint',
                'curVal' => '',
            ),
            'created_by' => array(
                'format' => 'varchar',
                'curVal' => '',
            ),
        );
    }

    public function prepareSearchFields(): void
    {
        $this->searchFields = array(
            'album_id' => array(
                'format' => 'varchar',
                'sort' => 1,
                'search' => 1,
            ),
            'albumName' => array(
                'format' => 'varchar',
                'sort' => 1,
                'search' => 1,
            ),
            'albumAlias' => array(
                'format' => 'varchar',
                'sort' => 1,
                'search' => 1,
            ),
            'metaDescr' => array(
                'format' => 'varchar',
                'sort' => 1,
                'search' => 1,
            ),
            'dateOfCr' => array(
                'format' => 'date',
                'sort' => 1,
                'search' => 1,
            ),
            'activeFlag' => array(
                'format' => 'tinyint',
                'sort' => 1,
                'search' => 1,
            ),
            'refreshDate' => array(
                'format' => 'date',
                'sort' => 1,
                'search' => 1,
            ),
            'robIndex' => array(
                'format' => 'tinyint',
                'sort' => 1,
                'search' => 1,
            ),
            'created_by' => array(
                'format' => 'varchar',
                'sort' => 1,
                'search' => 1,
            ),
        );
    }
}