<?php


namespace JointApp\Controllers\Components;


use http\Exception\InvalidArgumentException;
use JointApp\Controllers\ModuleController;

class Controller_Components_MusicTracksToAlb extends ModuleController
{
    public string $processUri = '/siteman/musictrackstoalb';
    public string $moduleName = 'musictrackstoalb';

    public function loadBindComponents(): void
    {
        $this->bindComponents = array(
            'musicalb' => [],
            'musictracks' => [],
        );
    }

    public function getEditView(): void
    {

        //echo '<pre>';
        //print_r($this->model->record);
        //exit;

        parent::getEditView(); // TODO: Change the autogenerated stub
    }


}