<?php


namespace JointApp\Controllers\Components;


use JointApp\Controllers\ModuleController;

class Controller_Components_NtfTemplates extends ModuleController
{
    public string $moduleName = 'ntftemplates';

    public string $processUri = '/siteman/ntftemplates';

    public function loadBindComponents(): void
    {
        $this->bindComponents = array(
            "ntflist" => [],
            "ntfread" => [],
        );
    }

    public function prepareListFields(): void
    {
        $this->listFields = array(
            'btnDetail' => array(
                'replaces' => array('template_id'),
                'format' => 'link',
                'url' => 'template_id=template_id'
            ),
            'btnEdit' => array(
                'replaces' => array('template_id'),
                'format' => 'link',
                'url' => 'template_id=template_id'
            ),
            'btnDelete' => array(
                'replaces' => array('template_id'),
                'format' => 'link',
                'url' => 'template_id=template_id'
            ),
            'template_id' => array(
                'format' => 'hidden',
            ),
            'tName' => array(
                'format' => 'varchar',
            ),
            /*
            'tHeader_en' => array(
                'format' => 'text',
            ),
            'tHeader_rus' => array(
                'format' => 'text',
            ),
            'tBody_en' => array(
                'format' => 'text',
            ),
            'tBody_rus' => array(
                'format' => 'text',
            ),
            */
            'date_created' => array(
                'format' => 'datetime',
            ),
            'created_by' => array(
                'format' => 'varchar',
            ),
        );

        //parent::prepareListFields(); // TODO: Change the autogenerated stub

        //echo '<pre>';
        //print_r($this->listFields);
        //exit;

    }

    public function prepareSearchFields(): void
    {
        $this->searchFields = array(
            'tName' => array(
                'search' => true,
                'sort' => true,
                'format' => 'varchar',
            ),
        );
    }

    public function prepareEditFields(): void
    {
        $this->editFields = array(
            'template_id' => array(
                'format' => 'varchar',
                'curVal' => '',
                'pri' => true,
            ),
            'tName' => array(
                'format' => 'varchar',
                'curVal' => '',
            ),
            'tHeader_en' => array(
                'format' => 'text',
                'curVal' => '',
            ),
            'tHeader_ru' => array(
                'format' => 'text',
                'curVal' => '',
            ),
            'tBody_en' => array(
                'format' => 'tinymce',
                'id' => 'tBody_en',
                'curVal' => '',
                'style' => array(
                    'class' => 'wd100',
                ),
            ),
            'tBody_ru' => array(
                'format' => 'tinymce',
                'id' => 'tBody_ru',
                'curVal' => '',
                'style' => array(
                    'class' => 'wd100',
                ),
            ),
            'date_created' => array(
                'format' => 'datetime',
                'curVal' => '',
            ),
            'created_by' => array(
                'format' => 'varchar',
                'curVal' => '',
            ),
        );
    }

    public function loadLangController():string
    {
        parent::loadLangController();
        $name = 'LangFiles_'.$this->langNs.'_Controller_Components_NtfTemplates';
        require_once $this->docRoot.'/JointApp/LangFiles/Controllers/Components/'.$name.'.php';
        return $name;
    }
}