<?php


namespace JointApp\Controllers\Components;


use JointApp\Controllers\ModuleController;

class Controller_Components_NtfList extends ModuleController
{
    public string $moduleName = 'ntflist';

    public string $processUri = '/siteman/ntflist';

    public function loadBindComponents(): void
    {
        $this->bindComponents = array(
            "ntftemplates" => [],
            "ntfread" => [],
        );
    }

    public function loadLangController():string
    {
        parent::loadLangController();
        $name = 'LangFiles_'.$this->langNs.'_Controller_Components_NtfList';
        require_once $this->docRoot.'/JointApp/LangFiles/Controllers/Components/'.$name.'.php';
        return $name;
    }

    public function prepareListFields(): void
    {
        $this->listFields = array(
            'btnDetail' => array(
                'replaces' => array('ntf_id'),
                'format' => 'link',
                'url' => 'ntf_id=ntf_id'
            ),
            'btnEdit' => array(
                'replaces' => array('ntf_id'),
                'format' => 'link',
                'url' => 'ntf_id=ntf_id'
            ),
            'btnDelete' => array(
                'replaces' => array('ntf_id'),
                'format' => 'link',
                'url' => 'ntf_id=ntf_id'
            ),
            'ntf_id' => array(
                'pri' => true,
                'format' => 'varchar',
            ),
            'template_id' => array(
                'format' => 'varchar',
            ),
            'subscriber_type' => array(
                'format' => 'varchar',
            ),
            'type_id' => array(
                'format' => 'varchar',
            ),
            'add_date' => array(
                'format' => 'datetime',
            ),
            //'template_params' => array(
            //    'format' => 'text',
            //),
            //'send_params' => array(
            //    'format' => 'text',
            //),
            'send_date' => array(
                'format' => 'datetime',
            ),
            'created_by' => array(
                'format' => 'varchar',
            ),
            'send_res' => array(
                'format' => 'tinyint',
            ),
            'send_log' => array(
                'format' => 'text',
            ),
        );
        //parent::prepareListFields(); // TODO: Change the autogenerated stub
        //echo '<pre>';
        //print_r($this->listFields);
        //exit;
    }

    public function prepareViewFields(): void
    {
        $this->viewFields = array(
            'ntf_id' => array(
                'pri' => true,
                'format' => 'varchar',
                'readonly' => 1,
            ),
            'template_id' => array(
                'format' => 'varchar',
                'readonly' => 1,
            ),
            'subscriber_type' => array(
                'format' => 'varchar',
                'readonly' => 1,
            ),
            'type_id' => array(
                'format' => 'varchar',
                'readonly' => 1,
            ),
            'add_date' => array(
                'format' => 'datetime',
                'readonly' => 1,
            ),
            'template_params' => array(
                'format' => 'text',
                'readonly' => 1,
            ),
            'send_params' => array(
                'format' => 'text',
                'readonly' => 1,
            ),
            'send_date' => array(
                'format' => 'datetime',
                'readonly' => 1,
            ),
            'created_by' => array(
                'format' => 'varchar',
                'readonly' => 1,
            ),
            'send_res' => array(
                'format' => 'tinyint',
                'readonly' => 1,
            ),
            'send_log' => array(
                'format' => 'text',
                'readonly' => 1,
            ),
        );
    }
}