<?php


namespace JointApp\Controllers\Components;


use JointApp\Controllers\ModuleController;

class Controller_Components_Robots extends ModuleController
{

    public string $moduleName = 'robots';

    public string $processUri = '/siteman/robots';

    public function loadBindComponents(): void
    {
        $this->bindComponents = array(
            "robotsupdate" => [],
            "sitemap" => [],

        );
    }
    public function loadLangController():string
    {
        parent::loadLangController();
        $name = 'LangFiles_'.$this->langNs.'_Controller_Components_Robots';
        require_once $this->docRoot.'/JointApp/LangFiles/Controllers/Components/'.$name.'.php';
        return $name;
    }

    public function prepareEditFields(): void
    {
        $this->editFields = array(
            'maploc'=> Array(
                'pri' => 1,
                'format' => 'varchar',
                'curVal' => '',
            ),
            'indexVal' => array(
                'format' => 'select',
                'filling' => array(
                    'Disallow' => 'Disallow',
                ),
            ),
            'comment' => array(
                'format' => 'varchar',
                'curVal' => '',
            ),
            'use_flag' => array(
                'format' => 'tinyint',
                'curVal' => '',
            ),
            'date_created' => array(
                'format' => 'datetime',
                'curVal' => '',
            ),
            'created_by' => array(
                'format' => 'varchar',
                'curVal' => '',
            ),
        );
    }

    public function prepareSearchFields(): void
    {
        $this->searchFields = array(
            'maploc'=> Array(
                'sort' => 1,
                'search' => 1,
                'format' => 'varchar',
            ),
            'indexVal' => array(
                'format' => 'varchar',
                'sort' => 1,
                'search' => 1,
            ),
            'comment' => array(
                'format' => 'varchar',
                'sort' => 1,
                'search' => 1,
            ),
            'use_flag' => array(
                'format' => 'tinyint',
                'sort' => 1,
                'search' => 1,
            ),
            'date_created' => array(
                'format' => 'datetime',
                'sort' => 1,
                'search' => 1,
            ),
            'created_by' => array(
                'format' => 'varchar',
                'sort' => 1,
                'search' => 1,
            ),
        );
    }

    public function prepareListFields(): void
    {
        $this->listFields = array(
            'btnDetail' => array(
                'replaces' => ['maploc'],
                'format' => 'link',
                'url' => 'maploc=maploc',
            ),
            'btnEdit' => array(
                'replaces' => ['maploc'],
                'format' => 'link',
                'url' => 'maploc=maploc',
            ),
            'btnDelete' => array(
                'replaces' => ['maploc'],
                'format' => 'link',
                'url' => 'maploc=maploc',
            ),
            'maploc'=> Array(
                'format' => 'varchar',
            ),
            'indexVal' => array(
                'format' => 'varchar',
            ),
            'comment' => array(
                'format' => 'varchar',
            ),
            'use_flag' => array(
                'format' => 'tinyint',
            ),
            'date_created' => array(
                'format' => 'hidden',
            ),
            'created_by' => array(
                'format' => 'hidden',
            ),
        );
    }

    public function siteRobotsUpdate()
    {
        $this->loadBindComponents();

        $this->model->siteName = $this->siteName;

        $this->model->createRobotsTxt();

        $this->view->bindComponents = $this->bindComponents;

        $this->view->moduleName = $this->moduleName;
    }

    public function prepareViewParams(): void
    {
        parent::prepareViewParams(); // TODO: Change the autogenerated stub
        if($this->view->type == 'new'){
            $this->view->editFields['date_created']['curVal'] = date('Y-m-d');
            $this->view->editFields['use_flag']['curVal'] = 1;
        }
    }
}