<?php
class view_test_records extends view_test
{

    function print_page_content()
    {
        parent::print_page_content(); // TODO: Change the autogenerated stub

        echo "<div class='contentBlock-frame'><div class='contentBlock-center'>".
            "<div class='contentBlock-wrap'>".
            "<h3>Список тестов</h3>".
            "<p>Чтобы открыть таблицу (список и далее), используйте адерес /table_name, где table_name - имя таблицы в БД</p>".
            "<p>Для примера используются три кастомные модели</p>".
            "<ul>".
            "<li><a href='".JOINT_SITE_EXEC_DIR."/test/records/musicalb'>musicalb</a></li>".
            "<li><a href='".JOINT_SITE_EXEC_DIR."/test/records/musictracks'>musictracks</a></li>".
            "<li><a href='".JOINT_SITE_EXEC_DIR."/test/records/musictrackstoalb'>musictrackstoalb</a></li>".
            "</ul>".
            "</div></div></div>";
    }

}