<?php
class view_music extends SiteView
{
    public $albumsList  = null;
    public $playAlb = null;
    public $trackList = null;

    function __construct()
    {
        parent::__construct();

        $this->logo = JOINT_SITE_EXEC_DIR."/img/popimg/music-logo.png";
        $this->shortcut_icon = $this->logo;
        $this->scripts[]= JOINT_SITE_EXEC_DIR."/js/musicgallery.js";
        $this->styles[]= JOINT_SITE_EXEC_DIR."/css/musicgallery.css";
    }

    function LoadViewLang_custom()
    {
        parent::LoadViewLang_custom();
        require_once $_SERVER["DOCUMENT_ROOT"].JOINT_SITE_EXEC_DIR.
            "/application/lang_files/views/music/lang_view_music_".$_SESSION[JS_SAIK]["lang"].".php";
        return "lang_view_music_".$_SESSION[JS_SAIK]["lang"];
    }


    function load_lang_files()
    {
        parent::load_lang_files(); // TODO: Change the autogenerated stub
        require_once "application/lang_files/views/music/lang_view_music_".$_SESSION["lang"].".php";
        return "lang_view_music_".$_SESSION["lang"];
    }

    function set_head_array()
    {
        if(!$this->playAlb["robIndex"]){
            $this->metrik_block = false;
            $this->robot_no_index = true;
        }
        //$this->lang_map->set_head_array(array("albumName" => $this->playAlb["albumName"], "metaDescr" => $this->playAlb["metaDescr"]));
        //include "application/lang_files/views/music/sha_music_".$_SESSION["lang"].".php";
    }

    function print_page_content()
    {
        echo "<div class='contentBlock-frame'><div class='contentBlock-center'>" .
            "<div class='contentBlock-wrap'>";

        if($this->albumsList){
            if($this->albumsList->rowCount()){

                echo "<div class='alb-menu'>";

                while ($alb_row = $this->albumsList->fetch(PDO::FETCH_ASSOC)){
                    echo "<a href='/music/album/".$alb_row["albumAlias"]."'>".$alb_row["albumName"]."</a>";
                }
                echo "</div>";
            }
        }

        if($this->playAlb){
            echo "<div class='play-alb'>".
                "<div class='alb-name'>".$this->playAlb["albumName"]."</div>".
                "<div class='alb-cover'><img src='".MUSIC_COVERS_DIR."/".$this->playAlb["albumImg"]."'></div>".
                "<div class='alb-descr'>".$this->playAlb["metaDescr"]."</div>".
                "<div class='alb-created'>".$this->lang_map->music["alb_created"].": <span>".
                $this->playAlb["dateOfCr"]."</span></div>".
                "<div class='alb-updated'>".$this->lang_map->music["alb_updated"].": <span>".
                $this->playAlb["refreshDate"]."</span></div>".
                "</div>";
        }

        echo "<div class='ac-wrap'>".
            "<audio controls='controls' autoplay id='htmlMusicPlayer'>".
            "</audio>".
            "</div>".
            "<div class='tracks-list' id='music-album'>";

        if($this->trackList->rowCount() > 0){
            echo "<div class='track-line caption'>".
                "<div class='track-num'>No</div>".
                "<div class='track-artist'>".$this->lang_map->music["t_art"]."</div>".
                "<div class='track-name'>".$this->lang_map->music["t_song"]."</div>".
                "<div class='track-play'>".$this->lang_map->music["t_play"]."</div>".
                "</div>";

            $track_num = 0;

            while ($track_row = $this->trackList->fetch(PDO::FETCH_ASSOC)){
                $print_track_file = $track_row["track_file"];
                if(strpos(" ".$track_row["track_file"], "http", 0)!=1){
                    $print_track_file=MUSIC_TRACKS_DIR."/".$print_track_file;
                }

                $track_num++;
                echo "<div class='track-line'>".
                    "<div class='track-num'>".$track_num."</div>".
                    "<div class='track-artist'>".$track_row["track_artist"]."</div>".
                    "<div class='track-name'>".
                    "<a href='".$print_track_file."'>".$track_row["track_name"]."</a>".
                    "</div>".
                    "<div class='track-play'><input type='button' value='Play'></div>".
                    "</div>";
            }
        }

        echo "</div>".
            "</div></div></div>";
    }
}