insert into srvCards_dt (
    card_id, cardName_rus, cardName_en, cardAlias, shortDescr_rus, shortDescr_en, longDescr_rus, longDescr_en, cardImg, cardActive, cardPrice_rus, cardPrice_en, cardCurr_rus, cardCurr_en, sortDate, unit_rus, unit_en, created_by)
values
('1', 'php', 'php', 'php', 'Программирование на php', 'programming php', '<p>php считается самым простым языком программирования и предназначен в основном для создания сайтов, хотя с помощью его можно решать и другие задачи. Большинство сайтов в интернет написано именно на php, плюс его еще и в том, что он бесплатный.<br />Скрипты должны быть написаны специалистами, быть понятными, гибкими для изменений и выполнятся быстро. Чтобы писать много надо придерживаться какого либо шаблона программирования, например MVC.</p>
<p>При поиске проблем приходится проверять множество условий, например, ошибки могут быть как в самом скрипте, так и в используемых библиотеках, зависящих сервисах, настройках на сервере и многом другом. При отладке кода на рабочих сайтах надо быть особенно внимательным потому что ошибки могут причинить неудобство пользователям и стоить денег заказчику. Обязательно нужно делать резервные копии файлов, проводить тестирование внесенных изменений.</p>', '<p>php is the simplest programming language and mental mainly for making websites, through, with that may do another tasks. Most part websites are made on php, plus of that is that free. Scripts must be written by specialist, be flexible for modifying and have high speed execution. To write big srcipts, it would better adhere MVC proggramming pattern. Solving problems, needs to check many versions, for example, errors could be occurred in the script or dependent libraries, outside services, servers setting and other cases. Have to be extremely attentive do debugging code, because of problems might troubles for users and cost money for owner. It is necessarily making reserve copy and testing changes.</p>', '60475b5f8b8e1.png', '1', '1000', '10', 'руб', '$', '2021-01-21', 'час', 'h', 'F42F81F8-1300-41CA-89BB-36BD7417BE1E'),
('5', 'SQL', 'SQL', 'database', 'Базы данных', 'database', '<p class="MsoNormal">Популярных баз данных много (PostgreSQL, MS-SQL, MySQL, Monogo Db и другие) и принцип работы с ними примерно одинаковый. На практике мне чаще всего приходится работать реляционными базами как MySQL. <br />Опыт показывает что в небольших базах данных практически всегда все запросы выполняются быстро. В базах в несколько ГБ, где в таблицах хранятся и постоянно используются десятки миллионов записей, все сложнее. Время выполнения разных запросов на выборку одних и тех же данных (с одинаковым результатом) может очень существенно различаться.<br />Оптимизация баз данных требует тщательного анализа структуры и связей между таблицами, индексов и ключевых полей, типов операторов SQL, также настроек сервера и нагрузки на него.</p>', '<p>There are lot of popular databases (PostgreSQL, MS-SQL, MySQL, Monogo Db and others) and principles of wort with are similar. In my practice, i more frequently use relation databases like MYSQL. Experience reveals, that in small databases almost all queries execution fast. In databases size of GB, where in the tables stored and always used millions records, all becomes more complicated. Lead-time different type queries for selection the same data (with equal results) can be signafinty different. Optimizations databases demands thorough analysis of structure and dependency between tables, indexes and key words, types of sql-operators, servers setting and loading.</p>', '604e359390b91.jpg', '1', '1000', '10', 'руб', '$', '2021-01-18', 'час', 'h', 'F42F81F8-1300-41CA-89BB-36BD7417BE1E'),
('2', 'Сайт-визитка', 'Visit-card site', 'vCard-site', 'Небольшой и недорогой, как правило одностраничный сайт.', null, '<p>Сайты - визитки обычно используют когда не хотят тратить время и деньги чтобы вести полноценный сайт или в качестве заглушек до разработки полного функционала.</p>
<p>Такие сайты обычно содержат только основную информацию о компании: контакты, вид деятельности, прайс-листы, описание одного или нескольких товаров или услуг. Обычно этого бывает достаточно чтоб запустить контекстную рекламу и начать получать заказы.</p>
<p>Цена сайта-визитки зависит от объема и сложности работ, условий размещения сайта на хостинге и складывается примерно следующим образом:</p>
<p>6000 руб. - средняя стоимость создания одной страницы (динамической или статической в зависимости от сложности)</p>
<p>3000 руб. - примерная стоимость аренды хостинга на 1 год и работы по его заказу.</p>
<p>Среднее время работы над одной страницей занимает два дня.</p>
<p>Вы можете значительно уменьшить стоимость работы если имеете четкое представление как должен выглядеть и работать ваш сайт. Наличие готовых текстов и изображений или даже примеров страниц, которые можно скопировать, ускорят время создания сайта и снизят ваши затраты.</p>
<p>Создание сайта-визитки выполняется по тех. заданию, при необходимости с заказчиком заключается договор на оказание услуг.</p>', null, '5b76976d03ede.jpg', null, '15000', '190', '643', '840', '2018-08-17', null, null, 'F42F81F8-1300-41CA-89BB-36BD7417BE1E'),
('6', 'Javascript', 'javascript', 'javascript', 'Программирование Javascript', 'coding javascript', '<p>Javascript поддерживается браузерами и находит очень широкое применение в web. Обычно это изменения на странице в зависимости от выбора пользователя. С помощью Javascript создаются сложные виджеты, данные можно обработать не только на стороне клиента, но и на сервере.</p>', '<p>Javascript has support browsers and has wide usage in websites. Often for modifying page of clients choice. Complex javascript widgets able handles data as on client PC, as servers side.</p>', '60477c72cb8be.jpg', '1', '1000', '10', 'руб', '$', '2021-01-16', 'час', 'h', 'F42F81F8-1300-41CA-89BB-36BD7417BE1E'),
('3', 'тариф Базовый', null, 'base-site', 'Установка Windows на ваш компьютер (ноутбук). Обычно вместе с Windows клиенту, по его желанию, может быть установлено дополнительное ПО (браузеры, ридеры и д.р.)', null, '<p>Как правило установка Windows занимает не более часа. Часто после установки требуется настройка ОС, обычно заказчик желает установить дополнительные пакеты программ: msOffice, Chrome, torren и другие.</p>
<p>Windows следует устанавливать на исправный компьютер предварительно освободив место на жестком диске. Дополнительные проверки, копирование данных, тесты памяти и жесткого могут существенно увеличить время на работу по установки системы. </p>
<p>По умолчанию предполагается установка стабильных сборок Windows-10 x32 или x64 в зависимости от характеристик компьютера, а на старые компьютеры обычно устанавливается Windows XP SP3 по выбору специалиста. Возможна установка ОС с диска или флэшки заказчика.</p>
<p>Важно, что Windows - это коммерческий продукт, хотя сам образ системы можно скачать бесплатно с сайта Microsoft, лицензия на него стоит денег. Под ответственность заказчика может быть применен активатор Windows для установки лицензионного ключа.</p>
<p>Вы можете установить Windows <a title="как установить windows 10 на компьютер" href="../../../../pc/which-of-window">самостоятельно</a> или воспользоваться услугами специалиста. </p>
<p>При заказе услуги клиенту предоставляется скидка на выезд. По договоренности работы могут быть выполнены на территории клиента или удаленно, при необходимости составляется акт приемки техники в ремонт и договор на оказание слуг.</p>', null, '5b76982c7cf6f.png', null, '50000', '600', '643', '840', '2018-08-17', null, null, 'F42F81F8-1300-41CA-89BB-36BD7417BE1E'),
('4', 'тариф Продвинутый', null, 'advanced-site', 'Подключив yandex money на свой сайт вы сможете получать предоплату за свои товары или услуги с банковских карт с возможностью автоматической привязки платежа к заказу и корзине клиента.', null, '<p>Это решение хорошо подходит для небольших интернет-магазинов и фрилансеров, желающих получать оплату заказов на своем сайте. Деньги переводятся на Яндекс кошелек и могут быть в последствии выведены и обналичены вами самостоятельно.</p>
<p>Работа по безналу и за предоплату уменьшит процент отказа и сбережет вас от недобросовестных клиентов.</p>
<p>Преимушества использования Яндекс-денег:</p>
<ul>
<li>простота регистрации и настройки кошелька, доступно для физических лиц с небольшим оборотом до 100 тыс. в месяц (и более)</li>
<li>небольшой 2% комиссии за пополнение кошелька с банковских карт, 3%+ за вывод денег на банковскую карту. Подробнее о лимитах можно прочитать по ссылкам <a title="https://yandex.ru/support/money/fees-limits/transfers.html" href="https://yandex.ru/support/money/fees-limits/transfers.html" target="_blank" rel="noopener">один</a> и <a title="https://money.yandex.ru/doc.xml?id=524834" href="https://money.yandex.ru/doc.xml?id=524834" target="_blank" rel="noopener">два</a></li>
</ul>
<p>api yandex money позволяет идентифицировать заказ на вашем сайте и отправить на него http-уведомление о результатах перевода и пополнения кошелька. Настройки кошелька не позволят провести ложный платеж благодаря наличию секретного слова и функции проверки хэш. Таким образом можно однозначно привязать заказ к платежу и корзине клиента.</p>
<p>Цена за подключение оплаты Яндекс-деньгами на вашем сайте - от 6 тыс. руб. в зависимости от сложности реализации.</p>', null, '5b87a73a7f773.jpg', null, '100000', '130', '643', '840', '2018-08-30', null, null, 'F42F81F8-1300-41CA-89BB-36BD7417BE1E'),
('7', 'Верстка HTML', 'html', 'html', 'Верстка HTML', 'html layout', '<p class="MsoNormal">Даже версткой html-документов должны заниматься компетентные люди, а при выполнении сложных элементов дизайна необходимо хорошее знание и умение применять CSS. Здесь тоже нужно уделать внимание многим мелочам, прописывать метатеги и заголовки, в правильной последовательности включать в документ стили и скрипты, тогда документ будет работать правильно, выглядеть привлекательно для пользователей и хорошо распознаваемым для робота.<br />Вы можете заказать верстку по собственным макетам или попросить скопировать понравившуюся вам страницу, выполнить адаптивный дизайн под разные размеры и ориентации экрана.</p>', '<p class="MsoNormal">Even html layout should made by awared people, making difficult pieces needs good knowledges CSS. This work need attention to details, set up headers, meta tags, in right sequence attach scripts and styles, then document become well-recognized for robots and nice-looking for users. You may order html by your own layouts or ask for copy what you want, make Responsive Layout for different screen sizes and orientations.</p>', '60478b2ee69ba.jpg', null, '500', '7', 'руб', '$', '2021-01-15', 'час', 'h', 'F42F81F8-1300-41CA-89BB-36BD7417BE1E'),
('8', 'Настройка сервера', 'Server setups', 'server', 'Настройка сервера', 'Server configuration', '<p class="MsoNormal">От правильности настроек сервера во многом зависит правильность и безопасность работы сайта. Чаще всего серверов одновременно несколько, у каждого из которых свои настройки и разрешенные пользователи, которым доступны определенные права и директории. Таким образом множество различных ошибок может возникать на сервере, отладку которых лучше доверить специалистам, или для начала можно попробовать проверить конфиги и разобрать логи.</p>', '<p>Of right server configuration, mainly depend properly and safety functioning website. Generraly there are some servers at the same time, each of them has own settings and allowed users, that avalibale appropriated rules and directories. That way lot of bugs might occurred on server, debugging that better trust to specialist, or for the beginning, you may try to check configuration and parse logs.</p>', '60477d8ebd085.jpg', '1', '1000', '10', 'руб', '$', '2021-01-12', 'час', 'h', 'F42F81F8-1300-41CA-89BB-36BD7417BE1E'),
('9', 'CRM - системы', 'crm', 'crm', 'CRM - системы', 'crm-systems', '<p class="MsoNormal">В продажах удобно использовать программы, в которых продавцы ведут базу клиентов и сделок с ними. Программа покажет продавцу входящую цену и его прибыль, сколько и когда клиент брал ранее, остатки на складах, создаст необходимые документы на оплату и передачу товара, рассчитает дату отгрузки и доставки клиенту. Каждая стадия такой цепочки продажи может быть представлена отдельным бизнес-процессом.<br />Примером такой customers relationships management может быть сложный web-сайт в локальной сети, работа которого может зависеть от разных сервисов и популярной 1С.<br />Часто требуется анализ и исправление алгоритмов crm описывающих бизнес-процессы, разработка под новые сущности структуры данных и методов обработки и представления.</p>', '<p>For the sales are useful software where sellers have database of leads and opportunities. App show income price and profit to seller, amount and date of last clients purchase, volume in storages, create documents for invoice and delivery, calcs shipment and delivery date. Each stage of this chain can be abstracted as standalone business-process. For example, this may be complex website in local network, functioning of that may depended on out-services and popular 1C. Often needs analytics and reviewing algorithms of crm describes business-process, working out structure, methods and views for new entities.</p>', '60478c110835f.png', '1', '1000', '10', 'руб', '$', '2021-01-13', 'час', 'h', 'F42F81F8-1300-41CA-89BB-36BD7417BE1E'),
('10', 'SEO и реклама', 'seo', 'seo', 'Продвижение сайтов', 'promoting web-sites', '<p class="MsoNormal">Обычно процесс продвижения сайтов очень длительный, требует аудита большого количества данных и исходя из выводов применение каких-то мер, которые не гарантируют результат.<br />Сравнительный анализ показывает что сайты примерно одинаковой тематики набирают примерно одинаковые показатели просмотров по контекстной рекламе. Сколько раз вам при этом позвонят и сколько купят будет в большей степени зависеть от вас, возможно от расценок или условий доставки. Бывает что рекомендуемы меры не применяются, в таком случае уровень планки задаете вы. Обратите внимание что при поиске товаров или услуг на первых позициях обычно показывается реклама, такой взгляд сейчас на это у поисковых систем.<br />Для продвижения сайтов обычно пользуются стандартными бесплатными инструментами webmaster.yandex и googlesearch, следуют их рекомендациям. Эти инструменты покажут поисковые запросы и посещаемость сайта, допущенные ошибки на карте сайта или в размере текста на экране. Для заказа рекламы пользуются сервисами ads.google.com и direct.yandex.ru</p>', '<p class="MsoNormal">As a rule, process of promoting websites is too long, demands of audit big data, after appreciation that, taking some actions that not warranty the results. Comparison reveals, similar sites have similar ranks in ad. How many calls or orders you will get, dependent generally on you, may be on price on things or delivery terms. Sometimes recommended actions has not applied, this way you set level of the bar. Take attentions, when searching for good or services, at the top of list are paid ad, this is standpoint of search systems. For promoting websites are useful free services as google search console and yandex webmaster. These services show search queries and numbers of visitors, reveal errors on site map or in text size on screens. For ordering ads are useful services as ads.google.com and direct.yandex.ru</p>', null, null, '500', '7', 'руб', '$', '2021-01-03', 'час', 'h', 'F42F81F8-1300-41CA-89BB-36BD7417BE1E'),
('11', 'Tor - сайты', 'tor-sites', 'tor', 'Tor - сайты', 'Dark web-sites', '<p>Tor-сайты обычно создаются чтоб разделить какую-нибудь информацию, которую нельзя выложить в публичный интернет потому что это небезопасно. Tor позволяет сохранить анонимность сервера работая через сеть луковых серверов. Создание скрытого tor-сайта ничем особенным не отличается от обычного сайта. Для этого как правило требуется отдельный компьютер, на который устанавливается специальные программы и tor-браузер. Для работы сервера в сети tor не требуется статического ip-адреса, но вы не получите высокую скорость загрузки страниц и красивого доменного имени, хотя изображения загружать на сервер и скачивать вполне возможно.</p>', '<p>Tor-sites often create to share some info, that may not out in public internet because unsafe. Tor allow to save anonymity of server, working through onion-servers network. Creating hidden tor-sites has not significant features with public web-sites, for that you need PC and ordinary soft and tor-browser. For tor-server functioning you neednt static ip-address, but you cant get high speed page load and nice done name, though upload and download images completely possible.</p>', '60478ae0ceb76.png', null, '500', '7', 'руб', '$', '2021-01-01', 'час', 'h', 'F42F81F8-1300-41CA-89BB-36BD7417BE1E'),
('14', 'Автоматизация', 'Automation', 'automation', 'Автоматизация', 'automation', '<p>Для выполнения рутинных задач как очистка логов, бэкапы, контроль использования дисков и не только, пишут скрипты, которые обычно запускают через планировщик на windows или cron на Linux. В крупной инфраструктуре выполнять задачи и контролировать результаты и ошибки лучше централизованно, используя такие системы мониторинга и управления как Elasticsearch и Ansible.</p>', '<p>To perform routine tasks such as clearing logs, backups, monitoring disk usage and more, they write scripts that are usually run through the scheduler on windows or cron on Linux. In a large infrastructure, it is better to perform tasks and monitor results and errors centrally, using monitoring and management systems such as Elasticsearch and Ansible.</p>', 'Screenshot 2024-04-09 131419.png', '1', '1000', '10', 'руб', '$', '0000-00-00', 'час', 'h', 'F42F81F8-1300-41CA-89BB-36BD7417BE1E'),
('12', 'VCS', 'VCS', 'VCS', 'Перенос релиза', 'Version controls', '<p>В серьёзных проектах обычно ведут контроль версий для удобства совместной работы, возможности вернуться в предыдущее состояние.</p>
<p>При работе с ветками важно понимать какие изменения будут влиты чтоб правильно решать конфликты.</p>
<p>Обычно перенос релиза это не только перенос файлов, но и миграции, изменения конфигурации, проверка логов, отвественное выполнение которого лучше доверить специалистам</p>', '<p>In serious projects, version control is usually carried out for the convenience of collaboration, the ability to return to the previous state.</p>
<p>When working with branches, it is important to understand what changes will be made in order to resolve conflicts correctly.</p>
<p>Usually, postponing a release is not only transferring files, but also migrations, configuration changes, and checking logs, the responsible execution of which is better entrusted to specialists</p>', 'git.png', '1', '1000', '10', 'руб', '$', '2021-01-15', 'час', 'h', 'F42F81F8-1300-41CA-89BB-36BD7417BE1E'),
('13', 'c#', 'c#', 'c-sharp', 'Windows приложения', 'Windows apps', '<p>На с# программируют для Windows, можно создавать различные типы программ, но пользователи чаще всего имеют дело с оконными приложениями. Для работы над купными и сложными проектами усилий одного программиста может быть недостаточно. Вы можете заказать поддержку существующих приложений или разработку новых под ваши цели</p>', '<p>They program for Windows in c#, you can create various types of programs, but users most often deal with windowed applications. To work on large and complex projects, the efforts of a single programmer may not be enough. You can order the customization of existing applications or the development of new ones for your purposes</p>', 'csharp-facturacion-facialix.jpg', '1', '1000', '10', 'руб', '$', '2021-01-20', 'час', 'h', 'F42F81F8-1300-41CA-89BB-36BD7417BE1E');