<?php
class LangFiles_Ru_Views_Templates_RecordEdit extends LangFiles_Ru_Views_SiteView
{
    public static function getLangPageContent(): stdClass
    {
        $lang = parent::getLangPageContent(); // TODO: Change the autogenerated stub

        $editView = new stdClass();
        $editView->submitUpdate = 'Обновить';
        $editView->submitNew = 'Создать';
        $editView->submitDel = 'Удалить';

        $lang->editView = $editView;
        return $lang;
    }

    public static function getLangHeader(): stdClass
    {
        $langHeader = parent::getLangHeader();

        $langHeader->updateFromArray = function ($array = []) use (&$langHeader){
            if($array['type'] == 'edit'){
                $langHeader->h1 = 'Редактирование записи в таблице '.$array['tableName'];
            }elseif ($array['type'] == 'new'){
                $langHeader->h1 = 'Создание записи в таблице '.$array['tableName'];
            }elseif ($array['type'] == 'delete'){
                $langHeader->h1 = 'Удаление записи в таблице '.$array['tableName'];
            }
        };
        return $langHeader;
    }
}
