<?php
class m_model_musictracks extends ModuleModel
{
    public $tableName = "musicTracks";

    public $tracksToAlb = "musicTracksToAlb";

    public $modelAliases = array(
        "en" => "music tracks",
        "rus" => "мелодии"
    );

    public $module_name = "music";

    function getRecordStructure()
    {
        require_once $_SERVER["DOCUMENT_ROOT"].JOINT_SITE_EXEC_DIR.
            "/application/recordsStructureFiles/modules/music/m_rsf_musictracks.php";
        $this->recordStructureFields = new m_rsf_musictracks();
        //$this->recordStructureFields->editFields["track_artist"]["filling"] = $this->fill_artist_list();
    }

    function fill_artist_list()
    {
        $return = array();
        $qry = "select track_artist from ".$this->tableName." group by track_artist order by track_artist";
        $res = $this->query($qry);
        if($res->rowCount()){
            while ($row = $res->fetch(PDO::FETCH_ASSOC)){
                $return[$row["track_artist"]] = $row["track_artist"];
            }
        }
        return $return;
    }
/*
    function deleteRecord()
    {
        $clearTrackToAlb_qry = "delete from ".$this->tracksToAlb." where track_id='".$this->recordStructureFields->record["track_id"]["curVal"]."'";
        $this->query($clearTrackToAlb_qry);
        return parent::deleteRecord(); // TODO: Change the autogenerated stub
    }
*/
}