<?php
class ModuleEditView extends RecordEditView
{
    public $module_config = null;
    public $m_process_url = null;
    public $module_name = null;

    function __construct()
    {
        parent::__construct();
        require_once $_SERVER["DOCUMENT_ROOT"].JOINT_SITE_EXEC_DIR.
            "/application/views/templates/ModuleMenu.php";
        $this->styles[] = JOINT_SITE_EXEC_DIR."/css/module.css";
        $this->scripts[]=JOINT_SITE_EXEC_DIR."/lib/js/tinymce/js/tinymce/tinymce.min.js";
        $this->scripts[] = JOINT_SITE_EXEC_DIR."/js/module_record_edit.js";
    }

    function print_page_content()
    {
        if(isset($this->module_name)){
            echo moduleMenu::print_module_menu($this->lang_map->menu_blocks["modules_menu"]["menu_items"][$this->module_name]["aliasMenu"],
                $this->module_config, $this->m_process_url);
        }else{
            echo moduleMenu::print_module_menu(null,
                $this->module_config, $this->m_process_url);
        }

        parent::print_page_content(); // TODO: Change the autogenerated stub
    }



    function getTnputType($fieldNname, $fieldOption = array(
        "format" => null,
        "fieldAliases" => array("en" => null, "rus" => null),
        "nameSpace" => null,
        "id" => null,
        "value" => null,
        "readonly" => null,
        "indexes" => null,
        "maxLength" => null, //for text and varchar format
        "style" => null, //for text and varchar format
    ), $value = null)
    {
        $parent_input = parent::getTnputType($fieldNname, $fieldOption, $value);

        if($fieldOption["format"] == "hidden"){
            return $parent_input;
        }

        $readonly_print = $parent_input["readonly_print"];
        $name_print = $parent_input["name_print"];
        $id_print = $parent_input["id_print"];
        $value_print = $parent_input["value_print"];

        if($fieldOption["format"] == "tinymce"){
            $id_print = "id='".$fieldNname."'";
        }

        if ($fieldOption["format"] == "tinymce") {
            $value_print = $value;
        }elseif ($fieldOption["format"] == "tinymce") {
            $value_print = $value;
        }elseif($fieldOption["format"] == "checkbox" or $fieldOption["format"] == "tinyint"){
            if($value){
                $value_print = "checked";
            }else{
                $value_print = null;
            }
            if(isset($fieldOption["readonly"]) and $fieldOption["readonly"] == true){
                $readonly_print = "onclick='return false;'";
            }
        } /*elseif ($fieldOption["format"] == "file"){
                        $value_print = null;
                    }



                    if($fieldOption["format"] == "file"){
                        $return_input = "<input type='file' ".$name_print;
                        if($fieldOption["file_options"]["accept"]){
                            $return_input .= " accept='".$fieldOption["file_options"]["accept"]."'";
                        }

                        $return_input .=">".
                            "<span class='file_val'>".$value."</span>";
                        if($fieldOption["file_options"]["load_dir"] and $value){
                            if($fieldOption["file_options"]["file_type"] == "img"){
                                if($fieldOption["replaces"]){
                                    $imgLink = $fieldOption["file_options"]["load_dir"];
                                    foreach ($fieldOption["replaces"] as $replace){
                                        $imgLink = str_replace($replace, $this->record[$replace]["curVal"], $imgLink);
                                    }
                                }else{
                                    $imgLink = $fieldOption["file_options"]["load_dir"]."/".$value;
                                }
                                $return_input .= "<img class='cell-img float-l' src='".$imgLink."'>";
                            }
                        }
                    }elseif($fieldOption["format"] == "radio"){
                        $radio_cnt = 0;
                        foreach ($fieldOption["filling"] as $opt_id=>$optVal){
                            $radio_cnt++;
                            $return_input .= " <input type='radio' id='".$opt_id."' ".$name_print." value='".$opt_id."' ";
                            if($radio_cnt == 1){
                                $return_input .= "checked";
                            }
                            $return_input .= ">".
                                "<label for='".$opt_id."'>".$optVal[$_SESSION["lang"]]."</label>";

                        }
                    }else*/if ($fieldOption["format"] == "password"){
        $return_input = "<input type='password' ".$name_print." ".$id_print." ".$value_print." ".$readonly_print.">";
    }/*elseif($fieldOption["format"] == "find-select"){
                $return_input = "<div class='find-select' id='".$fieldNname."'>".
                    "<input type='text' id='fst-".$fieldNname."' value='".$this->record[$fieldOption["fillName"]]["curVal"]."'>".
                    "<div class='fss'>".

                    "<select size='5' id='fs-".$fieldNname."' name='".$fieldNname."'>".
                    "<option value='".$value."' selected>".$this->record[$fieldOption["fillName"]]["curVal"]."</option>".
                    "</select>".
                    "</div>".
                    "</div>";
            }*/elseif($fieldOption["format"] == "tinymce"){
        $return_input = "<textarea ".$name_print." ".$id_print." ".$readonly_print.">".$value_print."</textarea>".
            "<script>tinyInit('#".$fieldNname."');</script>";
    }elseif($fieldOption["format"] == "number"){
                $return_input="<input type='number' max='".$fieldOption["max"]."' min='".$fieldOption["min"]."' step='".$fieldOption["step"]."' ".
                    $name_print." ".$id_print." ".$value_print." ".$readonly_print.">";
            }elseif($fieldOption["format"] == "list"){
                $return_input = "<input type='text' ".$name_print." ".$id_print." ".$value_print." ".$readonly_print." list='".$fieldNname."-list'>";

                $return_input .= "<datalist id='".$fieldNname."-list'>";
                foreach ($fieldOption["filling"] as $opt_id=>$optVal){
                    //$radio_cnt++;
                    $return_input .= " <option value='".$opt_id."'>".$optVal."</option>";

                }
                $return_input .="</datalist>";

            }else{
        $return_input = $parent_input["return_input"];
    }

        return array(
            "html" => "<div class='input-line"." ".$parent_input["line_class"]."'>".$parent_input["label_print"].$return_input."</div>",
        );
    }
}