<?php
class ModuleDetailView extends RecordDetailView
{
    public $module_config = null;
    public $m_process_url = null;
    public $module_name = null;

    public $bindTables = null;

    function __construct()
    {
        parent::__construct();
        require_once $_SERVER["DOCUMENT_ROOT"].JOINT_SITE_EXEC_DIR.
            "/application/views/templates/ModuleMenu.php";
        $this->styles[] = JOINT_SITE_EXEC_DIR."/css/module.css";
    }

    function printDetailView()
    {
        parent::printDetailView(); // TODO: Change the autogenerated stub
        if ($this->bindTables) {
            foreach ($this->bindTables as $btName => $btOptions) {
                echo "<div class='tbl-sub-panel' id='" . $btName . "'>" .
                    "<h3>" . $btOptions["h3"] . "</h3>" .
                    $btOptions["html"] .
                    "</div>";
            }
        }
    }

    function getTnputType($fieldNname, $fieldOption = array(
        "format" => null,
        "fieldAliases" => array("en" => null, "rus" => null),
        "nameSpace" => null,
        "id" => null,
        "value" => null,
        "readonly" => null,
        "indexes" => null,
        "maxLength" => null, //for text and varchar format
        "style" => null, //for text and varchar format
    ), $value = null)
    {
        $parent_input = parent::getTnputType($fieldNname, $fieldOption, $value); // TODO: Change the autogenerated stub

        if($fieldOption["format"] == "hidden"){
            return $parent_input;
        }

        if($fieldOption["format"] == "text-block"){
            $return_input = "<div class='detail-text-block'>".$this->record[$fieldNname]["curVal"]."</div>";
        }else{
            $return_input = $parent_input["return_input"];
        }

        return array(
            "html" => "<div class='input-line"." ".$parent_input["line_class"]."'>".$parent_input["label_print"].$return_input."</div>",
        );
    }

    function print_page_content()
    {
        echo moduleMenu::print_module_menu($this->lang_map->menu_blocks["modules_menu"]["menu_items"][$this->module_name]["aliasMenu"],
            $this->module_config, $this->m_process_url);
        parent::print_page_content();
    }
}