<?php
class LangFiles_Ru_Views_Cv_Main extends LangFiles_Ru_Views_SiteView
{
    public static function getLangPageContent(): stdClass
    {
        $langPageContent =  parent::getLangPageContent(); // TODO: Change the autogenerated stub
        $langPageContent->cvHeader = self::cvHeader();
        $langPageContent->cvMenu = self::cvMenu();

        return $langPageContent;
    }

    public static function cvHeader():stdClass
    {
        $langCvHeader = new \stdClass();

        $langCvHeader->title = 'Middle FullStack разработчик';

        $contacts = new \stdClass();
        $contacts->phoneLabel = 'Телефон';
        $contacts->addressLabel = 'Адрес';
        $contacts->addressVal = 'г. Иваново, ул. 8 Марта, д. 32, ТРЦ «Серебряный город»';
        $contacts->tgText = 'Телеграм';
        $contacts->tgLabel = 'Телеграм';
        $contacts->webLabel = 'Web-сайт';

        $langCvHeader->contacts = $contacts;
        return $langCvHeader;
    }

    public static function cvMenu():stdClass
    {
        $langMenu = new \stdClass();
        $langMenu->expText = 'Опыт работы';
        $langMenu->expTitle = 'Подробный опыт работы';
        $langMenu->skillsText = 'Профессиональные навыки';
        $langMenu->skillsTitle = 'Мой уровень владения технологией';
        $langMenu->faqText = 'Часто задаваемые вопросы';
        $langMenu->faqTitle = 'Мои ответы на популярные вопросы';
        $langMenu->pdfText = 'Скачать pdf';
        $langMenu->pdfTitle = 'Скачать cv';

        return $langMenu;
    }
}
