<?php
class LangFiles_En_Views_Cv_Main extends LangFiles_En_Views_SiteView
{
    public static function getLangPageContent(): stdClass
    {
        $langPageContent =  parent::getLangPageContent(); // TODO: Change the autogenerated stub
        $langPageContent->cvHeader = self::cvHeader();
        $langPageContent->cvMenu = self::cvMenu();
        $langPageContent->cvContent = static::cvContent();

        return $langPageContent;
    }

    public static function cvHeader():stdClass
    {
        $langCvHeader = new \stdClass();

        $langCvHeader->title = 'Middle FullStack developer';

        $contacts = new \stdClass();
        $contacts->phoneLabel = 'Phone';
        $contacts->addressLabel = 'Address';
        $contacts->addressVal = 'Russia, Ivanovo, 8-Match st., b. 32, «Silver city» mall, public hall';
        $contacts->tgText = 'Telegram';
        $contacts->tgLabel = 'link via Telegram';
        $contacts->webLabel = 'Web-site';

        $langCvHeader->contacts = $contacts;
        return $langCvHeader;
    }

    public static function cvMenu():stdClass
    {
        $langMenu = new \stdClass();
        $langMenu->expText = 'Experience';
        $langMenu->expTitle = 'Подробный опыт работы';
        $langMenu->skillsText = 'Нard skills';
        $langMenu->skillsTitle = 'Мой уровень владения технологией';
        $langMenu->faqText = 'FAQ';
        $langMenu->faqTitle = 'Мои ответы на популярные вопросы';
        $langMenu->pdfText = 'Download pdf';
        $langMenu->pdfTitle = 'download cv';

        return $langMenu;
    }

    public static function cvContent():stdClass
    {
        $cvContent = new stdClass();
        return $cvContent;
    }
}
