<?php

namespace JointApp\Controllers;

use JointApp\Factories\MailFactory;
use JointApp\Factories\ModelFactory;
use JointApp\JointAppMailer;
use JointApp\AuthConfig;


class Controller_Auth extends Controller
{
    public $callSignIn = false;
    public $callSignUp = false;
    public $socialAuth = false;
    public string $socialAuthCode = '';
    public string $okAuthState = '';

    public bool $cmdUserQuit = false;

    public function controllerFilterBody($bodyParams = []): void
    {
        parent::controllerFilterBody($bodyParams);

        if(isset($bodyParams['auth_signUp'])){
            $this->callSignUp = true;
        }elseif (isset($bodyParams['auth_signIn'])){
            $this->callSignIn = true;
        }
    }

    public function controllerFilterQuery($queryParams = []):void
    {
        parent::controllerFilterParams($queryParams); // TODO: Change the autogenerated stub

        if(isset($queryParams['exit']) and $queryParams['exit']=='userquit'){
            $this->cmdUserQuit = true;
        }

        if(isset($queryParams['code'])){
            $this->socialAuth = true;
            $this->socialAuthCode = $queryParams['code'];
        }

        if(isset($queryParams['state'])){
            $this->socialAuth = true;
            $this->okAuthState = $queryParams['state'];
        }
    }

    public function actionGetSignIn()
    {
        $this->view->switchForm = 'signIn';

        if($this->socialAuth){
            $this->socialAuth();
        }
    }

    public function actionGetSignUp()
    {
        $this->view->switchForm = 'signUp';
    }

    public function actionPostSignIn()
    {
        if($this->callSignIn) {

            $this->view->signInLogin = $this->requestParams['signInLogin'];
            $this->view->signInPassword = $this->requestParams['signInPassword'];

            $this->model->record["accLogin"]["curVal"] = $this->requestParams['signInLogin'];
            $pass = $this->requestParams['signInPassword'];
            if ($this->model::checkUserLogin($this->model->record["accLogin"]["curVal"])){
                if($this->model::checkUserPassword($pass)){
                    if ($this->model->copyByLoginOrEmail()) {
                        if($this->model->record["validDate"]["curVal"]) {
                            if (!$this->model->record["blackList"]["curVal"]) {
                                if(password_verify($pass, $this->model->record["pw_hash"]['curVal'])){
                                    $this->model->authSiteUser();
                                    $this->logger->redirect($this->httpRef);
                                }else{
                                    $this->view->signInErrWrongPass = true;
                                }
                            }else{
                                $this->view->signInErrBlackList = true;
                            }
                        }else{
                            $this->view->signInErrEMailValid = true;
                        }
                    }else{
                        $this->view->signInErrNotFound = true;
                    }
                }else{
                    $this->view->signInErrPass = true;
                }
            }else{
                $this->view->signInErrLogin = true;
            }
        }
    }

    public function actionPostSignUp()
    {

        $this->view->signUpLogin = $this->requestParams['signUpLogin'];
        $this->view->signUpPassword = $this->requestParams['signUpPassword'];
        $this->view->signUpPasswordRepeat = $this->requestParams['signUpPasswordRepeat'];
        $this->view->signUpEMail = $this->requestParams['signUpEMail'];

        if($this->callSignUp){
            $occur_err = false;
            $signUpLogin = $this->requestParams['signUpLogin'];
            if(!$this->model->checkUserLogin($signUpLogin)){
                $this->view->signUpErrLoginAccept = true;
                $occur_err = true;
            }else{
                if(!$this->model->checkDoubleLogin($signUpLogin)){
                    $this->view->signUpErrLoginReserved = true;
                    $occur_err = true;
                }
            }
            $pass = $this->requestParams['signUpPassword'];
            if(!$this->model->checkUserPassword($pass)){
                $this->view->signUpErrPassAccept = true;
                $occur_err = true;
            }
            $pass_r = $this->requestParams['signUpPasswordRepeat'];
            if($pass != $pass_r){
                $this->view->signUpErrPassMatch = true;
                $occur_err = true;
            }
            $signUpEMail = $this->requestParams['signUpEMail'];
            if(!$this->model->checkUserEmail($signUpEMail)){
                $this->view->signUpErrEMailAccept = true;
                $occur_err = true;
            }

            if(!$occur_err){
                if($this->model->createSiteUser($signUpLogin, $pass, $signUpEMail)) {

                    $model_Pdo = ModelFactory::createFromExistModel('JointApp\Models\Model_Pdo', $this->model);

                    $phpMailer = MailFactory::getMailer($this->getConfigDir());

                    $mailer = new JointAppMailer($phpMailer,$model_Pdo);

                    $replaces = [
                        'accAlias' => $this->model->record['accAlias']['curVal'],
                        'accPass' => $pass,
                        'validCode' => $this->model->record['vldCode']['curVal'],
                        'accLogin' => $this->model->record['accLogin']['curVal'],
                        'userEmail' => $this->model->record['eMail']['curVal'],
                    ];

                    $mailer->addNotification('welcomeFromSiteForUser',
                        'user',
                        $this->model->record["user_id"]["curVal"],
                        json_encode($replaces, JSON_UNESCAPED_UNICODE ),
                        true,
                        null);

                    $mailer->addNotification("newUserOnSite-site", "group",
                        "67A5CC8E-5EBF-46FD-9A37-4BE80DA17681", json_encode(
                            array(
                                "accLogin" => $this->model->record["accLogin"]["curVal"],
                                "accAlias" => $this->model->record["accAlias"]["curVal"],
                            )
                        ), true, "default");

                    $this->view->modalMenuActive = false;
                    $this->view->registerResult = true;
                    $this->view->validCode = $this->model->record['vldCode']['curVal'];
                }else{
                    echo 'Controller_User actionPostSignUp createSiteUser unknown error';
                }
            }else{
                $this->view->registerResult = false;
            }
        }
        $this->view->switchForm = 'signUp';
    }

    public function actionCmd()
    {
        if($this->cmdUserQuit){
            global $currentUser;
            $currentUser->userExit();
            $this->logger->redirect($this->httpRef);
        }
    }

    public function actionValidateEmail()
    {
        if($_GET["code"]){
            $find_qry = "select vldCode, accLogin, accAlias, validDate from users_dt where vldCode='".$_GET["code"]."'";
            $find_res = $this->model->query($find_qry);
            if($find_res->rowCount() == 1){
                $find_row = $find_res->fetch(PDO::FETCH_ASSOC);

                $view_data = $find_row;

                if($find_row["validDate"]){
                    $view_data["status"] = false;
                }else{
                    $update_qry = "update users_dt set validDate = '".date("Y-m-d H:i:s")."' where vldCode='".$_GET["code"]."'";
                    $this->model->query($update_qry);
                    $view_data["status"] = true;
                }

                $this->view->view_data = $view_data;
                $this->view->generate();
            }else{
                $this->logger->error("validate code doesnt not much any record", $this->logger->logger_context);
            }
        }else{
            $this->logger->error("null validate code", $this->logger->logger_context);
        }
    }

    function socialAuth(): void
    {
        if ($this->okAuthState == 'ok') {
            $this->authOk();
        }else{
            if (strlen($_GET['code'])<300){
                $this->authVk();
            }else{
                echo "another network";
                exit;
            }
        }
    }

    function authOk(): void
    {
        $authResult = false;

        $AuthConfig = new AuthConfig();
        $postReq = http_build_query(
            array(
                'code' => $this->socialAuthCode,
                'client_id' => $AuthConfig->ok->client_id,
                'client_secret' => $AuthConfig->ok->client_secret,
                "redirect_uri" => $AuthConfig->ok->redirect_uri,
                "grant_type" => "authorization_code"
            )
        );
        $opts = array('http' =>
            array(
                'method' => 'POST',
                'header' => 'Content-type: application/x-www-form-urlencoded',
                'content' => $postReq
            )
        );
        $context = stream_context_create($opts);
        $tokenReq = file_get_contents('https://api.ok.ru/oauth/token.do?', false, $context);
        $tokenArr = json_decode($tokenReq, true);

        if(isset($tokenArr['access_token']) and $tokenArr['access_token']!=null){
            $secret_key = MD5($tokenArr['access_token'].$AuthConfig->ok->client_secret);
            $sig = MD5('application_key='.$AuthConfig->ok->application_key.'format=jsonmethod=users.getCurrentUser'.$secret_key);

            $usrReq = file_get_contents('https://api.ok.ru/fb.do?application_key='.$AuthConfig->ok->application_key.'&format=json'.
                '&method=users.getCurrentUser&sig='.$sig.'&access_token='.$tokenArr['access_token']);
            $usrArr = json_decode($usrReq, true);

            if(isset($usrArr['uid']) and $usrArr['uid']!=null){
                $this->model->record['netWork']['curVal'] = 'ok';
                $this->model->record['accLogin']['curVal'] = $usrArr['uid'];
                $this->model->record['accAlias']['curVal'] = $usrArr['name'];
                $this->model->record['photoLink']['curVal'] = $usrArr['pic_2'];
                $this->model->record['birthDay']['curVal'] = $usrArr['birthday'];
                $this->model->record['socProf']['curVal'] = 'https://ok.ru/profile/'.$usrArr['uid'];
                $this->model->record['pref_lang']['curVal'] = $this->langLw;
                $authResult = true;
            }
        }

        if($authResult){
            if($this->model->copyByLoginOrEmail()){
                $this->model->updateRecord();
                $this->model->authSiteUser();
                $this->logger->redirect('/');
            }else{
                $this->model->record['user_id']['curVal'] =
                $this->model->record['created_by']['curVal'] = $this->model->createGUID();
                $this->model->record['validDate']['curVal'] =
                $this->model->record['regDate']['curVal'] = date('Y-m-d H:i:s');
                $this->model->record['blackList']['curVal'] = 0;

                if($this->model->insertRecord()){
                    $this->model->authSiteUser();
                    $this->logger->redirect('/');
                }
            }
        }
    }

    function authVk()
    {
        $authResult = false;

        $AuthConfig = new AuthConfig();
        $tokenReq=file_get_contents("https://oauth.vk.com/access_token?client_id=".$AuthConfig->vk->client_id
            ."&client_secret=".$AuthConfig->vk->client_secret."&redirect_uri=".$AuthConfig->vk->redirect_uri."&code=".$this->socialAuthCode);

        if($tokenArr=json_decode($tokenReq, true)){
            if(isset($tokenArr['access_token']) and $tokenArr['access_token']!=null){
                $usrReq = @file_get_contents('https://api.vk.com/method/users.get?user_ids='. $tokenArr['user_id'].
                    "&fields=photo_100,bdate&v=6.0&access_token=".$tokenArr['access_token']);
                $usrArr = json_decode($usrReq, true);
                if($usrArr!=null and isset($usrArr['response']['0']['id']) and $usrArr['response']['0']['id']!=null){
                    $this->model->record["netWork"]["curVal"] = "vk";
                    $this->model->record["accLogin"]["curVal"] = $usrArr['response']['0']['id'];
                    $this->model->record["accAlias"]["curVal"] = $usrArr['response']['0']['first_name']." ".$usrArr['response']['0']['last_name'];
                    $this->model->record["photoLink"]["curVal"] = $usrArr['response']['0']['photo_100'];
                    $this->model->record["birthDay"]["curVal"] = date_format(date_create($usrArr['response']['0']['bdate']), 'Y-m-d');
                    $this->model->record["socProf"]["curVal"] = 'https://vk.com/id'.$usrArr['response']['0']['id'];
                    $this->model->record['pref_lang']['curVal'] = $this->langLw;

                    $authResult = true;
                }
            }
        }

        if($authResult){
            if($this->model->copyByLoginOrEmail()){
                $this->model->updateRecord();
                $this->model->authSiteUser();
                $this->logger->redirect($this->httpRef);
            }else{
                $this->model->record['user_id']['curVal'] =
                $this->model->record['created_by']['curVal'] = $this->model->createGUID();
                $this->model->record['validDate']['curVal'] =
                $this->model->record['regDate']['curVal'] = date("Y-m-d H:i:s");
                $this->model->record['blackList']['curVal'] = 0;
                if($this->model->insertRecord()){
                    $this->model->authSiteUser();
                    $this->logger->redirect($this->httpRef);
                }
            }
        }
    }
}
