<?php


namespace JointApp\Controllers;


use JointApp\Controllers\Records\RecordsController;
use JointApp\Factories\ModelFactory;
use JointApp\Views\Modules\ModuleListView;
use JointApp\ModulesAccessList;

class ModuleController extends RecordsController
{

    public string $moduleName = '';

    public $bindComponents = [];

    public function controllerFilterParams($controllerParams = []): void
    {
        parent::controllerFilterParams($controllerParams); // TODO: Change the autogenerated stub
        if(isset($controllerParams['moduleName'])){
            $this->moduleName = $controllerParams['moduleName'];
        }
    }


    public function checkAccessController(): bool
    {
        $user_m = ModulesAccessList::getUserModules();

        if(in_array($this->moduleName, $user_m)){
            return true;
        }
        $this->logger->warning('denied in ModuleController on checkAccessController', $this->logger->logger_context);
        return false;
    }

    public function loadBindComponents():void
    {


    }


    protected function prepareViewParams(): void
    {
        parent::prepareViewParams(); // TODO: Change the autogenerated stub

        $this->loadBindComponents();

        $this->view->bindComponents = $this->bindComponents;

        $this->view->moduleName = $this->moduleName;
        if(isset($this->langMap->moduleAlias)){
            $this->view->h2 = $this->langMap->moduleAlias;
        }
    }

    public function getDetailView(): void
    {
        parent::getDetailView(); // TODO: Change the autogenerated stub

        $addAfterText = '';
        foreach ($this->bindComponents as $kN=>$kOpt){
            //print sub panels, else use just in menu
            if(isset($kOpt['relationships'])){
                $mName = $kOpt['model'];
                $cName = $kOpt['controller'];


                $bindModel = ModelFactory::createFromExistModel($mName, $this->model);

                $redordList_view = new ModuleListView($this->docRoot);
                $bindController = new $cName($this->getRequest(), $bindModel, $redordList_view);


                $viewLang_name = $redordList_view::loadLangView($this->docRoot, $this->langLw);
                $viewLang = new $viewLang_name;
                $viewLang_pageContent = $viewLang::getLangPageContent();

                $bindController->prepareSearchFields();
                $bindController->prepareListFields();

                $listRec_arr = $bindController->getListRecords();



                $viewParams = new \stdClass();
                $viewParams->listFields = $bindController->listFields;
                $viewParams->listRecords = $listRec_arr['list'];

                $viewParams->langSl = $bindController->langSl;
                $viewParams->process_url = $bindController->processUri;
                $viewParams->list_frame_id = $bindController->model->tableName;
                $viewParams->listCount = $listRec_arr['count'];
                $viewParams->curPage = $bindController->viewCurPage;
                $viewParams->onPage = $bindController->viewOnPage;
                $viewParams->h2 = $bindModel->tableName;
                $viewParams->onPage_list = ['10', '20', '50'];

                $viewParams->searchFields = $bindController->searchFields;
                $viewParams->fieldAliases = $bindController->langMap->fieldAliases;
                $viewParams->h2 = $bindController->langMap->moduleAlias;
                $viewParams->hasAccessCreate = $redordList_view->hasAccessCreate ;

                $viewParams->slave_req = '';
                foreach ($kOpt['relationships'] as $curTableKey => $bindTableKey){
                    $viewParams->slave_req.=$bindTableKey.'='.$this->model->record[$curTableKey]['curVal'].'&';
                }

                $viewParams->slave_req = substr($viewParams->slave_req, 0, strlen($viewParams->slave_req)-1);
                $viewParams->newBtn_qry  = '?'.$viewParams->slave_req  ;

                $addAfterText.= $redordList_view::listView($viewLang_pageContent->fiterView, $viewParams);
            }


        }
        $this->view->putPageContentAfter($addAfterText);
    }


    public function getListView(): void
    {
        if(!$this->model->hasAccessCreate()){
            $this->view->hasAccessCreate = false;
        }
        parent::getListView(); // TODO: Change the autogenerated stub
    }

    public function getNewView(): void
    {
        if($this->model->hasAccessCreate()) {
            parent::getNewView(); // TODO: Change the autogenerated stub
        }else{
            $this->logger->warning('denied in ModuleController on getNewView', $this->logger->logger_context);
        }
    }

    public function postNewView(): void
    {
        if($this->model->hasAccessCreate()) {
            parent::postNewView(); // TODO: Change the autogenerated stub
        }else{
            $this->logger->warning('denied in ModuleController on postNewView', $this->logger->logger_context);
        }
    }
}