<?php


namespace JointApp\Controllers;


use JointApp\Controllers\Components\Controller_Components_Music;
use JointApp\Controllers\Records\RecordsController;
use JointApp\JointAppRequest;
use JointApp\Models\Model;
use JointApp\Views\Module\BindComponentsMenu;
use JointApp\Views\View;

class ModuleController extends RecordsController
{

    public string $moduleName = '';

    public $bindComponents = [];

    public function controllerFilterParams($controllerParams = []): void
    {
        parent::controllerFilterParams($controllerParams); // TODO: Change the autogenerated stub
        if(isset($controllerParams['moduleName'])){
            $this->moduleName = $controllerParams['moduleName'];
        }
    }


    public function checkAccessController(): bool
    {
        $user_m = ModulesAccessList::getUserModules();

        if(in_array($this->moduleName, $user_m)){
            return true;
        }
        $this->logger->warning('denied in ModuleController on checkAccessController', $this->logger->logger_context);
        return false;
    }

    public function loadBindComponents():void
    {


    }


    protected function prepareViewFields(): void
    {
        parent::prepareViewFields(); // TODO: Change the autogenerated stub

        $this->loadBindComponents();

        $this->view->bindComponents = $this->bindComponents;

        $this->view->moduleName = $this->moduleName;
        if(isset($this->langMap->moduleAlias)){
            $this->view->h2 = $this->langMap->moduleAlias;
        }
    }



    public function loadModulesList():void
    {

    }

    //SESSION
    public function checkModuleAccess():bool
    {
        //echo 'confid-dir='.$this->getConfigDir();
        return true;
    }

    public function actionModuleStat()
    {
        ///1. create model by hands, why config


        //echo $mainName = 'JointApp\Controllers\Components\Users\Controller_Components_'.$this->moduleName.'Main';

        //$controllerMain = $mainName::getModelName();

        //echo 'modelName='.$controllerMain;

        /*
        $this->loadModuleConfig();
        echo '<pre>';
        print_r($this->mConfig);
        echo 'actionModuleStat';
        exit;
        $this->view->mConfig = $this->mConfig;
        */
        //echo '<pre>';
        //print_r($this->mConfig);
    }

    /*
    public function actionGetUsersListView()
    {

    }
    */

}