<?php

namespace Src\Views;

use JointApp\JointAppRequest;
use JointApp\Views\SiteView;
use JointApp\Interfaces\LangWebViewInterface;

class View_Landing extends SiteView
{
    public $serviceList = [];

    public string $logo = '/img/siteLogo/rightjoint-logo-400.png';
    public string $shortcutIcon = '/img/siteLogo/favicon.png';

    public function addViewParams($addViewParams)
    {
        parent::addViewParams($addViewParams);
        $addParams = new \stdClass();
        $addParams->serviceList = $this->serviceList;
        $addViewParams($addParams);
    }

    public static function addScriptLinks(callable $addScriptLinks): void
    {
        parent::addScriptLinks($addScriptLinks); // TODO: Change the autogenerated stub
        $addScriptLinks([
            '/js/modernizr.custom.js',
            '/js/landing/matrix-rain.js',
            '/js/landing/contacts.js',
        ]);
    }

    public static function addStyleLinks(callable $addStyleLinks): void
    {
        parent::addStyleLinks($addStyleLinks); // TODO: Change the autogenerated stub
        $addStyleLinks([
            '/css/landing/jointPass.css',
            '/css/landing/title-block.css',
            '/css/pop-services.css',
            '/css/component.css',
            '/css/landing/contacts-footer.css',
        ]);
    }

    public static function loadLangView(string $docRoot = __DIR__, string $viewLang = 'ru', $loads = []): LangWebViewInterface
    {
        $name = 'LangFiles_'.self::langNs($viewLang).'_Views_Landing';
        $loads[] = [$name => $docRoot.'/LangFiles/Views/'.$name];
        return parent::loadLangView($docRoot, $viewLang, $loads);
    }
    /*
        function loadLangView():string
        {
            parent::loadLangView();
            require_once($this->request->langDir.'/Views/LangFiles_'.$this->request->langNs.'_Views_Landing.php');
            return 'LangFiles_'.$this->request->langNs.'_Views_Landing';
        }
    */
    public static function createPageContent(\stdClass $langPageContent, \stdClass $viewParams):string
    {
        echo '<pre>';
        print_r($viewParams);
        exit;
        return
            self::printTitleBlock($langPageContent->titleBlock).
            '<div class="contentBlock-frame dark"><div class="contentBlock-center">'.
            '<div class="contentBlock-wrap">'.
            self::printJointPass($langPageContent->jointPass).
            '</div></div></div>'.
            self::printServiceBlock($langPageContent->popServ, $viewParams->serviceList, $langPageContent->langLw).
            self::printContactsBlock($langPageContent->contactsBlock);
    }

    public static function matrixRain():string
    {
        return '<canvas id="rain-canvas">'.
            '</canvas>';
    }

    public static function printTitleBlock(\stdClass $titleBlock):string
    {
        return
            '<div class="contentBlock-frame bg-top">'.
            '<div class="contentBlock-center"><div class="contentBlock-wrap">'.
            '<div class="services-title-wrap">'.
            '<div class="langing-invoke">'.$titleBlock->invoke.
            '</div>'.
            '<div class="langing-comment">'.$titleBlock->invoke_cm.'</div>'.
            '<div class="services-title-left">'.
            '<div class="stl-line"><span class="st-txt1">'.$titleBlock->st_txt1.'</span></div>'.
            '<div class="stl-line"><span class="st-txt2">'.$titleBlock->st_txt2.'</span></div>'.
            '<div class="stl-line"><span class="st-txt3">'.$titleBlock->st_txt3.'</span></div>'.
            '</div>'.
            '<div class="service-title-photo">'.
            self::matrixRain().
            '</div>'.
            '<div class="services-title-right thought">'.$titleBlock->thought.
            '</div></div>'.
            '<div class="call-btn"><a href="tel:+7(903)8887772" title="'.$titleBlock->cb_txt.'">'.
            '<div class="cb-content-wrap">'.
            '<span class="cb-num">+7 (903) 888-7772</span>'.
            '<span class="cb-txt">'.$titleBlock->cb_txt.'</span></div>'.
            '<div class="cb-img">'.
            '<img src="/img/landing/phone-free.png"></div>' .
            '</a></div>'.
            '<div class="advantages-list">'.
            '<div class="advantages-line">'.
            '<div class="advantages-line-img"><img src="/img/landing/experience.png"></div><div class="advantages-line-txt">' .
            $titleBlock->advantages_list_1.'</div>'.
            '</div>'.
            '<div class="advantages-line">'.
            '<div class="advantages-line-img"><img src="/img/landing/trust.png"></div><div class="advantages-line-txt">' .
            $titleBlock->advantages_list_2.'</div>'.
            '</div>'.
            '<div class="advantages-line">'.
            '<div class="advantages-line-img"><img src="/img/landing/bank-flat.png"></div><div class="advantages-line-txt">' .
            $titleBlock->advantages_list_3.'</div>'.
            '</div>'.
            '<div class="advantages-line">'.
            '<div class="advantages-line-img"><img src="/img/landing/handsshake.png"></div><div class="advantages-line-txt">' .
            $titleBlock->advantages_list_4.'</div>'.
            '</div>'.
            '<div class="advantages-line">'.
            '<div class="advantages-line-img"><img src="/img/landing/flexible.png"></div><div class="advantages-line-txt">' .
            $titleBlock->advantages_list_5.'</div>'.
            '</div>'.
            '</div>'.
            '<div class="ask-questions-line">'.$titleBlock->ask_q_1.
            ' <a href="https://t.me/rightjoint" title="'.$titleBlock->ask_q_2.'">'.
            '<img src="/img/Services/telegram.png">Telegram</a> ' .
            $titleBlock->ask_q_3.
            ' <span class="feedback-title"><img src="/img/Services/application-logo.png">' .
            $titleBlock->ask_q_4.
            '</span> '.$titleBlock->ask_q_5.'</div>'.
            '</div></div></div>';
    }

    public static function printServiceBlock(\stdClass $popServ, $serviceList = [])
    {

        $return = '<div class="contentBlock-frame">'.
            '<div class="contentBlock-center"><div class="contentBlock-wrap pop-services">'.
            '<h2>'.$popServ->h2.'</h2>'.
            '<div class="container">'.
            '<div class="main">'.
            '<ul id="og-grid" class="og-grid">';


        foreach ($serviceList as $num => $popServices_row){
            $return.= '<li>'.
                '<span>'.$popServices_row['cardName_'.$this->request->langLw].'</span>'.
                '<a href="#" id="pop-'.$popServices_row['cardAlias'].'"
						data-largesrc="/img/Services/services/'.$popServices_row['card_id'].'/'.$popServices_row['cardImg'].'" 
						data-title="'.$popServices_row['shortDescr_'.$this->request->langLw].'" 
						data-description="'.$popServices_row['longDescr_'.$this->request->langLw].'" 
						data-buy="'.$popServices_row['cardAlias'].'" 
						data-lang="'.$this->request->langLw.'" 
						data-bought="<div>'.$popServ->btn_buy.' ';
            if(isset($_SESSION[$this->request->langLw]['basket']['prod'][$popServices_row['cardAlias']])){
                $return.= $popServ->more_txt;
            }
            $return.= '</div><label>'.$popServices_row['cardPrice_'.$this->request->langLw].'</label> '.$popServices_row['cardCurr_'.$this->request->langLw].'/'.
                $popServices_row['unit_'.$this->request->langLw].'">'.
                '<img src="/img/Services/images/thumbs/'.$popServices_row['cardAlias'].'.png" alt="pop-srv-icon"/>'.
                '</a>'.
                '</li>';
        }
        $return.= '</ul></div></div>'.
            '<script src="/js/grid.js"></script>' .
            '<script>$(function() {
    Grid.init();
});</script>';
        $return.= '</div></div></div>';
        return $return;
    }

    public static function printContactsBlock(\stdClass $contactsblock):string
    {
        //<script type="text/javascript" charset="utf-8" async src="https://api-maps.yandex.ru/services/constructor/1.0/js/?um=constructor%3A2d466e2d4f1632789b9df6fd6d34e6e4f660b8caa1bed15db7a0dd231e4c7a31&amp;width=1200&amp;height=300&amp;lang=ru_RU&amp;scroll=true"></script>
        return '<div class="contentBlock-frame dark"><div class="contentBlock-center"><div class="contentBlock-wrap contacts">'.
            '<div class="contacts-block">'.
            '<div class="cb-img-wrap active"><div>'.
            '<script type="text/javascript" charset="utf-8" async '.
            'src="https://api-maps.yandex.ru/services/constructor/1.0/js/?um=constructor%3A2d466e2d4f1632789b9df6fd6d34e6e4f660b8caa1bed15db7a0dd231e4c7a31&amp;width=1200&amp;height=300&amp;lang=ru_RU&amp;scroll=true"></script>'.
            '</div></div>'.
            '<div class="cb-img-wrap">'.
            '<img src="/img/landing/contacts/sg-1.jpg">'.
            '</div>'.
            '<div class="cb-img-wrap">'.
            '<img src="/img/landing/contacts/sg-2.jpg"></div>'.
            '</div>'.
            '<div class="descr-frame">'.
            '<div class="descr-line"><img src="/img/siteLogo/rightjoint-logo-150.png"><span class="fmNm">Right Joint</span></div>'.
            '<div class="descr-line"><span>'.$contactsblock->address_f.':</span>'.
            $contactsblock->address_v.'</div>'.
            '<div class="descr-line"><span>'.$contactsblock->Schedule_f.':</span>'.
            $contactsblock->Schedule_v.'</div>'.
            '<div class="descr-line"><span>E-Mail:</span> rightjoint@yandex.ru</div>'.
            '<div class="descr-line"><span>'.$contactsblock->phone_f.':</span>'.
            '<a href="tel:+7(903)8887772"> +7 (903) 888-7772</a></div>'.
            '<div class="locPr-block">'.
            '<img src="/img/landing/contacts/small-img-yMap.png" class="active" onclick="changeContImg(0)">'.
            '<img src="/img/landing/contacts/sg-1-small.jpg" onclick="changeContImg(1)">'.
            '<img src="/img/landing/contacts/sg-2-small.jpg" onclick="changeContImg(2)">'.
            '</div>'.
            '</div></div></div>';
    }

    public static function printJointPass(\stdClass $jointPass):string
    {
        return '<h2 style="color: silver; margin-top: 1em">'.$jointPass->h2.'</h2>'.
            '<div class="promote-block">'.
            '<div class="promote-block-title">'.
            '<div class="pbt-header">'.$jointPass->title.'</div>'.
            '<div class="pbt-numbers"><span>c#</span><span>wpf</span></div>'.
            '</div>'.
            '<div class="promote-block-content">'.
            '<div class="pbc-line f-left">'.
            '<img src="/img/landing/jointPass/jointPass.png">'.
            '<p>'.
            $jointPass->p1.
            '</p>'.
            '<p>'.
            $jointPass->p2.
            '</p>'.
            '</div>'.
            '<div class="pbc-line f-right">'.
            '<img src="/img/landing/jointPass/encrypt-img.png">'.
            '<p>'.
            $jointPass->p3.
            '</p>'.
            '<p>'.
            $jointPass->p4.
            '</p>'.
            '</div>'.
            '</div>'.
            '<div class="promote-block-order">'.
            '<div class="pbo-ctrl"><a href="/products/jointpass" class="pbo-ctrl-feedback" '.
            'title="'.$jointPass->a_title.'"><img src="/img/landing/jointPass/get-jp-icon.png">'.
            $jointPass->a_text.'</a></div>'.
            '<div class="pbo-txt"><div class="pbc-arrow"></div>'.$jointPass->arrow.'</div>'.
            '</div>'.
            '</div>';
    }
}