<?php


namespace Src\Controllers;


use JointApp\Controllers\Records\RecordsController;
use JointApp\Factories\MailFactory;
use JointApp\Factories\ModelFactory;
use JointApp\JointAppMailer;

class Controller_Applications extends RecordsController
{
    public string $application_id = '';
    public $basketProducts = [];
    public int $basketTotal = 0;
    public $appInfo = [];
    public $comments = [];

    public function loadLangController():string
    {
        parent::loadLangController();
        $name = 'LangFiles_'.$this->langNs.'_Controller_Applications';
        require_once $this->docRoot.'/LangFiles/Controllers/Applications/'.$name.'.php';
        return $name;
    }

    public function controllerFilterParams($controllerParams = []): void
    {
        parent::controllerFilterParams($controllerParams); // TODO: Change the autogenerated stub

        if((isset($controllerParams['application_id']))){
            $this->application_id = $controllerParams['application_id'];
        }



    }

    public function actionIndex()
    {
        if($this->getAppInfo()){
            $this->getBasketProducts();
            $this->getAppComments();

            $this->view->basketArr['products'] = $this->basketProducts;
            $this->view->basketArr['total'] = $this->basketTotal;
            $this->view->appInfo = $this->appInfo;
            $this->view->comment = $this->comments;
        }else{
            $this->logger->error('getAppInfo on empty application_id', $this->logger->logger_context);
        }
    }

    public function getAppInfo():bool
    {
        $return = false;
        if(!empty($this->application_id)){
            $this->model->record['appl_id']['curVal'] = $this->application_id;
            if($this->model->copyRecord()){
                $return = true;
            }
            $this->appInfo = $this->model->record;
        }
        return $return;
    }

    function getBasketProducts()
    {
        if(!empty($this->model->record['basket']['curVal'])){
            $basket = json_decode($this->model->record['basket']['curVal'], true);
            $this->basketTotal = $basket['total'];
            foreach ($basket['prod'] as $prodAlias=>$prodCount){;
                $findProd_qry = 'select * from srvCards_dt where cardAlias = "'.$prodAlias.'"';
                $findProd_res = $this->model->query($findProd_qry);
                if($findProd_row = $findProd_res->fetch(\PDO::FETCH_ASSOC)){
                    $findProd_row['count'] = $prodCount;
                    $this->basketProducts[$prodAlias] = $findProd_row;;
                }
            }
        }


    }

    public function getAppComments()
    {

        $findApplCm_qry = 'select  applCm_dt.content, applCm_dt.dateEntered, applCm_dt.user_id, applCm_dt.attach, usersToGroups_dt.group_id, 
users_dt.photoLink, users_dt.accAlias, applCm_dt.appl_id    
from applCm_dt
left join usersToGroups_dt on applCm_dt.user_id = usersToGroups_dt.user_id and group_id = "67A5CC8E-5EBF-46FD-9A37-4BE80DA17681" 
left join users_dt on users_dt.user_id = usersToGroups_dt.user_id 
where appl_id = "'.$this->model->record['appl_id']['curVal'].'"
order by applCm_dt.dateEntered desc';

        $this->comments = $this->model->fetchToArray($findApplCm_qry);
    }




    function mkApplicationModal()
    {

        $errFlag = false;

        $this->prepareEditFields();
        $this->updateModelRecordFromRequest();

        $fbfmResponse['clientName']['err'] = 0;
        $fbfmResponse['clientMail']['err'] = 0;
        $fbfmResponse['clientSubject']['err'] = 0;
        $fbfmResponse['fbfa'] = 0;
        $fbfmResponse['redirectUrl'] = '';
        $fbfmResponse['mo-submit']['err'] = 0;
        $fbfmResponse['mo-submit']['info'] = '';

        if(!$this->model->checkClientName()){
            $errFlag = true;
            $fbfmResponse['clientName']['err'] = 1;
            $fbfmResponse['clientName']['info'] = $this->langMap->mkAppErr->err_f.': '.
                $this->langMap->mkAppErr->err_1;
        }

        if(!$this->model->checkUserEmail()){
            $errFlag = true;
            $fbfmResponse['clientMail']['err'] = 1;
            $fbfmResponse['clientMail']['info'] = $this->langMap->mkAppErr->err_f.': '.
                $this->langMap->mkAppErr->err_2;
        }

        if(isset($_SESSION['basket']['total'])){
            $this->model->record['basket']['curVal'] = json_encode($_SESSION['basket']);
        }else{
            if(strlen($_POST['clientSubject'])>10){
                //$fbfmResponse['clientSubject']['err'] = 0;
            }else{
                $errFlag = true;
                $fbfmResponse['clientSubject']['err'] = 1;
                $fbfmResponse['clientSubject']['info'] = $this->langMap->mkAppErr->err_f.': '.
                    $this->langMap->mkAppErr->err_3;
            }
        }
        if(isset($_SESSION['user_id'])){
            $this->model->record['user_id']['curVal'] = $_SESSION['site_user']['user_id'];
        }
        $this->model->record['status']['curVal'] = 'new';
        $this->model->record['payStatus']['curVal'] = 'not-paid';

        if(!$errFlag){
            $this->model->record['dateEntered']['curVal'] = date('Y-m-d H:i:s');
            if($this->model->insertRecord()){
                unset($_SESSION["basket"]);
                $fbfmResponse['fbfa']=1;
                $fbfmResponse['redirectUrl']=$this->langSl.'/applications/details/'.$this->model->record['appl_id']['curVal'];


                $model_Pdo = ModelFactory::createFromExistModel('JointApp\Models\Model_Pdo', $this->model);

                $phpMailer = MailFactory::getMailer($this->getConfigDir());

                $mailer = new JointAppMailer($phpMailer,$model_Pdo);

                $mailer->addNotification('new-app-siteman', 'user',
                    'F42F81F8-1300-41CA-89BB-36BD7417BE1E', json_encode(
                        array(
                            'server_host' => $_SERVER['HTTP_HOST'],
                            'appl_id' => $this->model->record['appl_id']['curVal'],
                        )
                    ), true, 'default');

                $mailer->addNotification('new-app-user', 'email',
                    $this->model->record['clientMail']['curVal'], json_encode(
                        array(
                            'server_host' => $_SERVER['HTTP_HOST'],
                            'appl_id' => $this->model->record['appl_id']['curVal'],
                        )
                    ), true, "default");
            }else{
                $fbfmResponse['mo-submit']['err']=1;
                $fbfmResponse['mo-submit']['info'] = 'ошибка: неизвестная ошибка DB->putOne';
            }
        }

        $this->view->responseJson = $fbfmResponse;
    }
}