<?php


namespace Src\Controllers;


use JointApp\Controllers\Components\Controller_Components_MusicAlb;
use Src\Controllers\Controller_Music_Alb;
use JointApp\Controllers\Controller;
use JointApp\Controllers\Records\RecordsController;
use JointApp\Factories\ModelFactory;
use JointApp\JointAppQueryBuilder;
use Src\Models\Music\Model_Music_Tracks;

class Controller_Music extends Controller
{
    private string $playAlbName = '';

    public function controllerFilterParams($controllerParams = []): void
    {
        parent::controllerFilterParams($controllerParams); // TODO: Change the autogenerated stub
        if(isset($controllerParams['playAlbName'])){
            $this->playAlbName = $controllerParams['playAlbName'];
        }
    }

    public function actionIndex()
    {
        $this->view->newAlbums = $this->model->getNewAlbums();
        $this->view->albumsCount = $this->model->countRecords(new JointAppQueryBuilder());
        $modelMusicTracks = ModelFactory::createFromExistModel('Src\Models\Music\Model_Music_Tracks', $this->model);
        $this->view->newTracks = $modelMusicTracks->getNewTracks();
        $this->view->tracksCount =$modelMusicTracks->countRecords(new JointAppQueryBuilder());
    }

    function actionAlbums()
    {
        $controllerAlb = new Controller_Music_Alb($this->getRequest(), $this->model, $this->view, []);
        $controllerAlb->getListView();
    }

    public function actionPlayAlbum()
    {
        $qBuilder = new JointAppQueryBuilder();
        $qBuilder->where('musicAlb.albumAlias="'.$this->playAlbName.'"');

        $playAlb = $this->model->listRecords($qBuilder);
        if(isset($playAlb[0])){
            $this->view->playAlb = $playAlb[0];
            $albMenuBuilder = new JointAppQueryBuilder();
            $albMenuBuilder->groupBy('albumName')
                ->limit('0, 10');
            $this->view->playAlbList = $this->model->listRecords($albMenuBuilder);
            $this->view->playAlbTracks = $this->model->getAlbTracksList($playAlb[0]['album_id']);
        }else{
            $this->logger->error('album-not-found', $this->logger->logger_context);
        }
    }
}