<?php


namespace Src\Views\Blog;


use JointApp\Views\SiteView;
use JointApp\Interfaces\LangWebViewInterface;

class View_Blog_Art extends SiteView
{
    public string $logo = '/img/popimg/blog-logo.png';
    public string $shortcutIcon = '/img/popimg/blog-icon.png';

    const ART_COVERS = '/userdata/blog/covers';

    public $artRow = [];
    public $artTags = [];

    public static function loadLangView(string $docRoot = __DIR__, string $viewLang = 'ru', $loads = []): LangWebViewInterface
    {
        $lang = 'LangFiles_' . self::langNs($viewLang) . '_Views_BlogArts';
        $loads[] = [$lang => $docRoot . '/LangFiles/Views/Blog/' . $lang];
        return parent::loadLangView($docRoot, $viewLang, $loads);
    }

    public function addViewParams(callable $addViewParams)
    {
        parent::addViewParams($addViewParams); // TODO: Change the autogenerated stub
        $addParams = new \stdClass();
        $addParams->artRow = $this->artRow;
        $addParams->artTags = $this->artTags;
        $addViewParams($addParams);
    }

    function langHeaderUpdate(callable $updateFromArray): void
    {
        $updateFromArray(['h1' => $this->artRow['artName']]);
    }

    function langHeadUpdate(callable $updateFromArray): void
    {
        $updateFromArray([
                'title' => $this->artRow['artName'],
                'description' => $this->artRow['artMeta']]
        );
    }

    public static function addStyleLinks(callable $addStyleLinks): void
    {
        parent::addStyleLinks($addStyleLinks); // TODO: Change the autogenerated stub
        $addStyleLinks([
            '/css/blog/blogArts.css',
        ]);
    }


    public static function createPageContent(\stdClass $langPageContent, \stdClass $viewParams): string
    {
        $artTags = '';

        for ($i=0; $i<count($viewParams->artTags); $i++){
            $artTags.='<span class="tag-value">'.$viewParams->artTags[$i].'</span>';
        }

        $pageContent =
            '<div class="contentBlock-frame"><div class="contentBlock-center">'.
            '<div class="contentBlock-wrap">'.
            '<div class="blog-container">'.
            '<div class="blog-header">'.
            '<div class="blog-header-meta"><h2>'.$viewParams->artRow['artMeta'].'</h2></div>'.
            '<div class="blog-header-img"><img src="'.self::ART_COVERS.'/'.$viewParams->artRow['artImg'].'"></div>'.
            '</div>'.
            '<div class="blog-info">'.
            '<div class="blog-info-dates">'.
            '<span class="b-em-container">'.$langPageContent->artHeader->created.':</span>'.
            '<span class="b-em-value">'.$viewParams->artRow['pubDate'].'</span>';
        if(!empty($viewParams->artRow['refreshDate'])){
            $pageContent.='<span class="b-em-container">'.$langPageContent->artHeader->refresh.':</span>'.
            '<span class="b-em-value">'.$viewParams->artRow['refreshDate'].'</span>';
        }
        $pageContent.='</div>'.
            '<div class="blog-info-tags">'.
            '<span class="b-em-container">'.$langPageContent->artHeader->tags.':</span>'.
            $artTags.'</div>'.
            '</div>'.
            '<div class="art-content">'.
            static::printArtContent($langPageContent->langArtContent, $viewParams, $langPageContent->langLw).
            '</div>'.
            '</div>'.
            '</div>'.
            '</div>'.
            '</div>';

        return $pageContent;
    }

    public static function printArtContent(\stdClass $langArtContent, \stdClass $viewParams, string $langLw): string
    {
        return 'put-art-content-there';
    }
}