<?php
include "application/views/view_main.php";
class productSiteView extends view_main
{
    public $logo="/img/popimg/internet.png";

    function __construct()
    {
        parent::__construct();
        $this->styles[] = "/css/products/prod-deploy.css";
        $this->lang_map["head"]["title"] = array(
            "en" => "jointSite - product",
            "rus" => "джойнтСайт - продукт",
        );
        $this->lang_map["head"]["h1"] = array(
            "en" => "Web Site - product",
            "rus" => "Web site - продукт",
        );
    }

    function print_page_content()
    {

        echo "<div class='contentBlock-frame'><div class='contentBlock-center'>".
            "<div class='contentBlock-wrap'>";
        echo "<p>Сервер:
<ul>
<li>Apache</li>
<li>Mysql</li>
<li>php</li>
</ul>
</p>";
        echo "</div></div></div>";
        echo "<div class='contentBlock-frame'><div class='contentBlock-center'>".
            "<div class='contentBlock-wrap'>";
        echo "<div class='prod-deploy'>".
            "<h2>Установка</h2>".
            "<p>Для полученния файлов можно или клонировать ветку в гит или скачать архив</p>".
            "<p>Тематические ветки начинаются с siteman (Управление контентом)</p>".
            "<p>Ветка admin может быть полезна для работы с БД и проведения миграций</p>".
            "<h3>Клонирование ветки</h3>".
            "<p>git clone</p>".
            "<h3>Конфиги</h3>".
            "<p>tra-ta-ta</p>".
            "<h3>Миграции</h3>".
            "<p>tra-ta-ta</p>".
            "</div>";
        echo "</div></div></div>";

        foreach ($this->branches as $b_name=>$b_info){
            $this->branches[$b_name]["href"] = "/products/jointsite/".$b_name;
           // $this->lang_map["branches"]["list"][$b_name]["href"] = "/products/jointsite/".$b_name;
        }

        //echo "<pre>";
        //print_r($this->lang_map["branches"]["list"]);


        parent::print_page_content(); // TODO: Change the autogenerated stub
    }
}