<?php
include "application/views/products/productSiteView.php";
class productSiteModuleView extends productSiteView
{
    public $logo="/img/popimg/admin-logo.png";

    function __construct()
    {
        parent::__construct();
        $this->lang_map["head"]["title"] = array(
            "en" => "jointSite - branch Admin",
            "rus" => "джойнтСайт - ветка Админ",
        );
        $this->lang_map["head"]["h1"] = array(
            "en" => "Web Site - branch Admin",
            "rus" => "Web site - ветка Админ",
        );
        $this->lang_map["prod_about"] = $this->lang_map["branches"]["list"]["module"]["descr"];


        $this->lang_map["product-info"] = array(
            "h2_common" => array(
                "en" => "About admin Module (site manager)",
                "rus" => "О ветке Модуль (Управление сайтом)",
            ),
            "h2_setup" => array(
                "en" => "Set up Module",
                "rus" => "Установка ветки Модуль",
            ),
        );

        $this->lang_map["product-deploy"] = array(
            "install" => array(
                'checkout-branch' => array(
                    "en" => "module",
                    "rus" => "module",
                ),

                "download_link" => array(
                    "en" => null,
                    "rus" => "null",
                ),
                "example-text" => array(
                    "en" => "clone repository and checkout branch <span class='ex-conf'>module</span>",
                    "rus" => "клонирование репозитория и переключение на ветку <span class='ex-conf'>module</span>",
                ),
            ),
        );


        $this->lang_map["product-migration"]["p2"] = array(
            "en" => "About product",
            "rus" => "3333333 <span class='ex-conf'>20240109_213031_testtable_3_rec.php</span>".
                " чтоб протестить как работать с админкой и записями",
        );
    }

    function prod_info_custom(){
        echo "<p>Вход в адмику /siteman</p>".
            "<p>Пользователи</p>".
            "<p>Группы доступа</p>".
            "<p>Пользователи админы</p>".
            "<p>Права пользователей на сущность в модуле</p>".
            "<p>Уведомления</p>".
            "<p>Личный кабинет</p>".
            "<p>Регистрация нового пользователя</p>";
    }

    function prod_deploy_migrations()
    {
        parent::prod_deploy_migrations(); // TODO: Change the autogenerated stub
        echo "<p>Добавление пользователей</p>".
        "<p>Добавление группы</p>".
        "<p>Добавление шаблонов уведомлений</p>";
    }

}