<?php
class view_jointpass extends SiteView
{
    public $logo= JOINT_SITE_EXEC_DIR."/img/Products/jointPass.png";

    function __construct()
    {
        parent::__construct();
        $this->styles[] = JOINT_SITE_EXEC_DIR."/css/products/prod-deploy.css";
    }
/*
    function load_lang_files()
    {
        parent::load_lang_files(); // TODO: Change the autogenerated stub
        include "application/lang_files/views/products/lang_view_productJointPass_".$_SESSION["lang"].".php";
        return "lang_view_productJointPass_".$_SESSION["lang"];
    }
*/
    function LoadViewLang_custom()
    {
        require_once($_SERVER["DOCUMENT_ROOT"] . JOINT_SITE_EXEC_DIR .
            "/application/lang_files/views/products/lang_view_productJointPass_" . $_SESSION[JS_SAIK]["lang"] . ".php");
        return "lang_view_productJointPass_" . $_SESSION[JS_SAIK]["lang"];

    }
    function print_page_content()
    {

        $this->prod_about();
        $this->prod_menu();
        $this->prod_downloads();
        $this->prod_info();
        $this->prod_craft();
        $this->prod_feedback();
    }

    function prod_feedback()
    {
        echo "<div class='contentBlock-frame'><div class='contentBlock-center'>".
            "<div class='contentBlock-wrap'>".
            "<section style='margin-bottom: 4em'>".
            "<h2 id='product-feedback'>".$this->lang_map->product_info["h2_feedback"]."</h2>".
            "<p>".$this->lang_map->jp_feedback["p1"]." <span class='ex-conf'>rightjoint@yandex.ru</span>".
            "</p>".
            "</section>".
            "</div></div></div>";
    }

    function prod_downloads()
    {
        echo "<div class='contentBlock-frame'><div class='contentBlock-center'>".
            "<div class='contentBlock-wrap'>".
            "<section>".
            "<h2 id='product-downloads'>".$this->lang_map->product_info["h2_dwl"]."</h2>".
            "<p>".
            "<a class='dwl-img-link' href='/downloads/jointPass.zip' title='".$this->lang_map->jp_dwl["a_title"]." jointPass.zip'>".
            "<img src='".JOINT_SITE_EXEC_DIR."/img/Products/jointPass.png'>jointPass.zip".
            "</a>".
            " ".$this->lang_map->jp_dwl["p1_txt1"]." <span class='ex-conf'>jointPass.exe</span>. ".
            $this->lang_map->jp_dwl["p1_txt2"].
            "</p>".
            "<p>".$this->lang_map->jp_dwl["p2"]." <strong>aa653c47a6b6925441fb7faf0689eb3a</strong>".
            "</p>".
            "<div class='example'>".
            "<div class='example-code'>".
            "CertUtil -hashfile jointPass.exe MD5".
            "</div>".
            "<div class='example-code'>".
            "Хэш MD5 : jointPass.exe: aa653c47a6b6925441fb7faf0689eb3a".
            "</div>".
            "<div class='example-text'>".
            $this->lang_map->jp_dwl["ex-text1"].
            "</div>".
            "</div>".
            "</p>".
            "<p>".$this->lang_map->jp_dwl["p3"]."</p>".
            "<div class='example'>".
            "<div class='example-code'>".
            "git clone https://github.com/rightJoint/jointpass".
            "</div>".
            "<div class='example-code'>".
            "git checkout main".
            "</div>".
            "<div class='example-text'>".
            $this->lang_map->jp_dwl["ex-text2"].
            "</div>".
            "</div>".
            "</section>".
            "</div></div></div>";
    }

    function prod_info(){

        echo "<div class='contentBlock-frame'><div class='contentBlock-center'>".
            "<div class='contentBlock-wrap'>".
            "<section>".
            "<h2 id='product-info'>".$this->lang_map->product_info["h2_common"]."</h2>";
        $this->prod_info_custom();
        echo "</section>".
            "</div></div></div>";
    }

    function prod_info_custom()
    {

        echo "<div class='branches-block'>".
            "<p>".$this->lang_map->jp_gui["p1"]."</p>".
            "<p>".$this->lang_map->jp_gui["p2"]."</p>".
            "<div class='example'>".
            "<div class='example-img'>".
            "<img src='/img/Products/jp-signup_".$_SESSION[JS_SAIK]["lang"].".png'>".
            "</div>".
            "<div class='example-text'>".
            $this->lang_map->jp_gui["example-text-1"].
            "</div>".
            "</div>".
            "<p>".
            $this->lang_map->jp_gui["p3"].
            "</p>".
            "<p>".
            $this->lang_map->jp_gui["p4"].
            "</p>".
            "<div class='example'>".
            "<div class='example-img'>".
            "<img src='/img/Products/jp-change-pass_".$_SESSION[JS_SAIK]["lang"].".png'>".
            "</div>".
            "<div class='example-text'>".
            $this->lang_map->jp_gui["example-text-2"].
            "</div>".
            "</div>".
            "<p>".
            $this->lang_map->jp_gui["p5"].
            "</p>".
            "<div class='example'>".
            "<div class='example-img'>".
            "<img src='/img/Products/jp-mainWin_".$_SESSION[JS_SAIK]["lang"].".png'>".
            "</div>".
            "<div class='example-text'>".
            $this->lang_map->jp_gui["example-text-3"].
            "</div>".
            "</div>".
            "<p>".
            $this->lang_map->jp_gui["p6"].
            "</p>".
            "<p>".
            $this->lang_map->jp_gui["p7"].
            "</p>".
            "<p>".
            $this->lang_map->jp_gui["p8"].
            "</p>".
            "<p>".
            $this->lang_map->jp_gui["p9"].
            "</p>".
            "<div class='example'>".
            "<div class='example-img'>".
            "<img src='/img/Products/jp-accFields_".$_SESSION[JS_SAIK]["lang"].".png'>".
            "</div>".
            "<div class='example-text'>".
            $this->lang_map->jp_gui["example-text-4"].
            "</div>".
            "</div>".
            "<p>".
            $this->lang_map->jp_gui["p10"].
            "<p>".
            $this->lang_map->jp_gui["p11"].
            "</p>".
            "<div class='example'>".
            "<div class='example-img'>".
            "<img src='/img/Products/jp-group_".$_SESSION[JS_SAIK]["lang"].".png'>".
            "</div>".
            "<div class='example-text'>".
            $this->lang_map->jp_gui["example-text-5"].
            "</div>".
            "</div>".
            "<p>".
            $this->lang_map->jp_gui["p12"].
            "</p>".
            "<div class='example'>".
            "<div class='example-img'>".
            "<img src='/img/Products/jp-cat_".$_SESSION[JS_SAIK]["lang"].".png'>".
            "</div>".
            "<div class='example-text'>".
            $this->lang_map->jp_gui["example-text-6"].
            "</div>".
            "</div>".
            "<p>".
            $this->lang_map->jp_gui["p13"].
            "</p>".
            "<div class='example'>".
            "<div class='example-img'>".
            "<img src='/img/Products/jp-fields_".$_SESSION[JS_SAIK]["lang"].".png'>".
            "</div>".
            "<div class='example-text'>".
            $this->lang_map->jp_gui["example-text-7"].
            "</div>".
            "</div>".
            "<p>".
            $this->lang_map->jp_gui["p14"].
            "</p>".
            "<div class='example'>".
            "<div class='example-img'>".
            "<img src='/img/Products/jp-acc_".$_SESSION[JS_SAIK]["lang"].".png'>".
            "</div>".
            "<div class='example-text'>".
            $this->lang_map->jp_gui["example-text-8"].
            "</div>".
            "</div>";
    }

    function prod_craft()
    {
        echo "<div class='contentBlock-frame'><div class='contentBlock-center'>".
            "<div class='contentBlock-wrap'>".
            "<section class='prod-deploy'>".
            "<h2 id='product-craft'>".$this->lang_map->product_info["h2_craft"]."</h2>".
            "<p>".
            $this->lang_map->jp_craft["p1"].
            "</p>".
            "<p>".
            $this->lang_map->jp_craft["p2"].
            "</p>".
            "<div class='example'>".
            "<div class='example-code'>".
            "4O5VjnGixFORFSNfwfZwSl+LDrkF3C98EiaY87EweKN7bKSSv3ER6U8rq03yx8rwsCCK5DrP6yrR0ED6oVttrlotC8Cqu4E4I8MCQqxwDu61U4PE/sOUrNkI9SSrAzqj".
            "</div>".
            "<div class='example-text'>".
            $this->lang_map->jp_craft["example-text-1"].
            "</div>".
            "</div>".
            "<p>".
            $this->lang_map->jp_craft["p3"].
            "<p>".
            $this->lang_map->jp_craft["p4"].
            "</p>".
            "<div class='example'>".
            "<div class='example-img'>".
            "<img src='/img/Products/jp-dataFolder.png'>".
            "</div>".
            "<div class='example-text'>".
            $this->lang_map->jp_craft["example-text-2"].
            "</div>".
            "</div>".
            "<p>".
            $this->lang_map->jp_craft["p5"].
            "</p>".
            "</section>".
            "</div></div></div>";
    }

    function prod_about()
    {
        echo "<div class='contentBlock-frame'><div class='contentBlock-center'>".
            "<div class='contentBlock-wrap'>".
            "<section class='prod-about'>".
            "<p>".
            $this->lang_map->prod_about.
            "</p>".
            "</section>".
            "</div></div></div>";
    }

    function prod_menu()
    {
        echo "<div class='contentBlock-frame'><div class='contentBlock-center'>".
            "<div class='contentBlock-wrap'>".
            "<section class='prod-menu'>".
            "<h2>".$this->lang_map->product_info["h2_сontent"]."</h2>".
            "<ul>".
            "<li><a href='#product-downloads'>".$this->lang_map->product_info["h2_dwl"]."</a></li>".
            "<li><a href='#product-info'>".$this->lang_map->product_info["h2_common"]."</a></li>".
            "<li><a href='#product-craft'>".$this->lang_map->product_info["h2_craft"]."</a></li>".
            "<li><a href='#product-feedback'>".$this->lang_map->product_info["h2_feedback"]."</a></li>".
            "</ul>".
            "</section>".
            "</div></div></div>";
    }
}