<?php
require_once "application/core/Records/RecordsModel.php";
//require_once "application/core/Module/ModuleRecordsModel.php";
class model_applications extends RecordsModel
{
    public $tableName = "applList_dt";
    function getRecordStructure()
    {
        parent::getRecordStructure(); // TODO: Change the autogenerated stub

        $this->record = array(
            "appl_id" => array(
                "format" => "varchar",
                "indexes" => 1,
            ),
            "clientName" => array(
                "format" => "varchar",
            ),
            "clientPhone" => array(
                "format" => "varchar",
            ),
            "clientMail" => array(
                "format" => "varchar",
            ),
            "clientSubject" => array(
                "format" => "TEXT",
            ),
            "dateEntered" => array(
                "format" => "datetime",
            ),
            "basket" => array(
                "format" => "TEXT",
            ),
            "status" => array(
                "format" => "varchar",
            ),
            "payStatus" => array(
                "format" => "varchar",
            ),
            "invoiceSum" => array(
                "format" => "int",
            ),
            "info" => array(
                "format" => "varchar",
            ),
            "user_id" => array(
                "format" => "varchar",
            ),

        );

        $this->listFields = array(
            "btnDetail" => array(
                "replaces" => array("appl_id"),
                "format" => "link",
                "url" => "appl_id=appl_id",
            ),
            "btnEdit" => array(
                "replaces" => array("appl_id"),
                "format" => "link",
                "url" => "appl_id=appl_id",
            ),
            "btnDelete" => array(
                "replaces" => array("appl_id"),
                "format" => "link",
                "url" => "appl_id=appl_id",
            ),
            "appl_id" => array(
                "indexes" => 1,
                "format" => "varchar",
                "search" => 1,
                "fieldAliases" => array(
                    "en" => "appl id",
                    "rus" => "id заявки",
                ),
                //"sort" => 1,
            ),
            "clientName" => array(
                "format" => "varchar",
                "search" => 1,
                "fieldAliases" => array(
                    "en" => "Client",
                    "rus" => "Клиент",
                ),
            ),
            "clientPhone" => array(
                "format" => "varchar",
                "search" => 1,
                "fieldAliases" => array(
                    "en" => "Phone",
                    "rus" => "Номер",
                ),
            ),
            "clientMail" => array(
                "format" => "varchar",
                "search" => 1,
                "fieldAliases" => array(
                    "en" => "Mail",
                    "rus" => "Почта",
                ),
            ),
            "clientSubject" => array(
                "maxLength" => 20,
                "format" => "TEXT",
                "fieldAliases" => array(
                    "en" => "Subject",
                    "rus" => "Тема",
                ),
            ),
            "dateEntered" => array(
                "format" => "datetime",
                "search" => 1,
                "fieldAliases" => array(
                    "en" => "dt entered",
                    "rus" => "Дт. созд.",
                ),
            ),
            /*"basket" => array(
                "format" => "TEXT",
            ),*/
            "status" => array(
                "format" => "varchar",
                "search" => 1,
                "fieldAliases" => array(
                    "en" => "appl status",
                    "rus" => "Статус заяв.",
                ),
            ),
            "payStatus" => array(
                "format" => "varchar",
                "search" => 1,
                "fieldAliases" => array(
                    "en" => "pay status",
                    "rus" => "Статус плат.",
                ),
            ),
            "invoiceSum" => array(
                "format" => "int",
                "search" => 1,
                "fieldAliases" => array(
                    "en" => "Sum",
                    "rus" => "Сумма",
                ),
            ),
            "info" => array(
                "format" => "varchar",
                "fieldAliases" => array(
                    "en" => "Info",
                    "rus" => "Инфо",
                ),
            ),
            "user_id" => array(
                "format" => "varchar",
                "search" => 1,
                "fieldAliases" => array(
                    "en" => "User",
                    "rus" => "Пользователь",
                ),
            ),
        );
    }
    function checkUserEmail()
    {
        if (filter_var($this->record["clientMail"]["curVal"], FILTER_VALIDATE_EMAIL)){
            return true;
        }else{
            return false;
        }
    }
    public function checkClientName()
    {
        if (preg_match('/^[a-zа-я]{1}[0-9a-zа-я-._ ]{2,15}$/imsiu', $this->record["clientName"]["curVal"]) == 0){
            return false;
        }
        return true;
    }
}