<?php


namespace JointApp\Views\Modules;


use JointApp\Views\Records\RecordListView;

class ModuleListView extends RecordListView
{
    public $bindComponents = [];

    public string $moduleName = '';

    public bool $robotNoIndex = true;

    public function addViewParams($addViewParams)
    {
        parent::addViewParams($addViewParams);
        $addParams = new \stdClass();
        $addParams->bindComponents = $this->bindComponents;
        $addParams->moduleName = $this->moduleName;
        $addViewParams($addParams);
    }

    public static function addStyleLinks(callable $addStyleLinks): void
    {
        parent::addStyleLinks($addStyleLinks); // TODO: Change the autogenerated stub
        $addStyleLinks(['/css/modules/moduleMenu.css',]);
    }

    public static function createPageContent(\stdClass $langPageContent, \stdClass $viewParams): string
    {
        return ModuleSubMenu::bindModuleMenu($viewParams->bindComponents, $viewParams->userModules, $langPageContent->modulesMenu, $viewParams->moduleName).
            parent::createPageContent($langPageContent, $viewParams); // TODO: Change the autogenerated stub
    }

    public static function bindModuleMenu($bindComponents = [], $userModules = [], $modulesMenu = [], $moduleName = ''):string
    {
        $return = '<div class="contentBlock-frame"><div class="contentBlock-center">'.
            '<div class="contentBlock-wrap"><div class="module-menu"><ul>';
        $return .= '<li>'.
            '<a href="/siteman/'.$moduleName.'" title="'.$modulesMenu->menuItems[$moduleName]['refTitle'].'">'.
            $modulesMenu->menuItems[$moduleName]['refText'].
            '</a>'.
            '</li>';
        foreach ($bindComponents as $cN => $cOpt){
            $return.= '<li>'.
                '<a href="/siteman/'.$cN.'" title="'.$modulesMenu->menuItems[$cN]['refTitle'].'">'.
                $modulesMenu->menuItems[$cN]['refText'].
                '</a>'.
                '</li>';
        }

        $return.='</ul></div></div></div></div>';
        return $return;
    }
}