<?php


namespace JointApp\Views\Modules;


use JointApp\Interfaces\LangWebViewInterface;
use JointApp\Views\SiteView;

class ModulesListView extends SiteView
{
    public string $logo = '/img/popimg/module-logo.png';
    public string $shortcutIcon = '/img/popimg/module-logo.png';

    public static function loadLangView(string $docRoot = __DIR__, string $viewLang = 'ru', $loads = []): LangWebViewInterface
    {
        $name = 'LangFiles_'.self::langNs($viewLang).'_ModulesListView';
        $loads[] = [$name => $docRoot.'/JointApp/LangFiles/'.$name];
        return parent::loadLangView($docRoot, $viewLang, $loads);
    }

    public static function addStyleLinks(callable $addStyleLinks): void
    {
        parent::addStyleLinks($addStyleLinks); // TODO: Change the autogenerated stub
        $addStyleLinks(['/css/modules/modulesList.css']);
    }

    public static function createPageContent(\stdClass $langPageContent, \stdClass $viewParams):string
    {
        $img = array(
            'users' => '/img/modImg/users-logo.png',
            'groups' => '/img/modImg/groups-logo.png',
            'userstogroups' => '/img/modImg/groups-logo.png',
            'ntftemplates' => '/img/modImg/eMail-logo.png',
            'ntflist' => '/img/modImg/eMail-logo.png',
            'ntfread' => '/img/modImg/eMail-logo.png',
            'musicalb' => '/img/modImg/music-logo.png',
            'musictracks' => '/img/modImg/music-logo.png',
            'musictrackstoalb' => '/img/modImg/music-logo.png',
        );

        $pageContent =
            '<div class="contentBlock-frame"><div class="contentBlock-center">'.
            '<div class="contentBlock-wrap">'.
        '<div class="m-list-container"><h2>Modules list</h2>';

        foreach ($langPageContent->modulesMenu->menuItems as $mN => $mOpt){
            if(in_array($mN, $viewParams->userModules)){

                $pageContent .= '<div class="m-list-line">'.
                    '<div class="m-list-img">';
                if(isset($img[$mN])){
                    $pageContent .='<img src="'.$img[$mN].'" alt="'.$mN.' image">';
                }else{
                    $pageContent .='<img src="/img/popimg/avatar-default.png" alt="'.$mN.' default image">';
                }
                $pageContent .='</div>'.
                '<div class="m-list-name"><a href="/siteman/'.$mN.'">'.$mN.'</a></div>'.
                '</div>';
            }
        }
        $pageContent .='</div>'.
        '</div></div></div>';
        return $pageContent;
    }
}