<?php
require_once $_SERVER["DOCUMENT_ROOT"].JOINT_SITE_EXEC_DIR.
    "/application/core/model_pdo.php";
require_once $_SERVER["DOCUMENT_ROOT"].JOINT_SITE_EXEC_DIR.
    "/application/core/RecordsModel.php";
require_once $_SERVER["DOCUMENT_ROOT"].JOINT_SITE_EXEC_DIR.
    "/application/core/RecordsController.php";
require_once $_SERVER["DOCUMENT_ROOT"].JOINT_SITE_EXEC_DIR.
    "/application/core/ModuleController.php";
require_once $_SERVER["DOCUMENT_ROOT"].JOINT_SITE_EXEC_DIR.
    "/application/models/model_user.php";
class controller_module extends ModuleController
{
    function __construct($loaded_model, $loaded_view, $action_name)
    {
        controller_api::checkAccessController();
        $this->model = new model_user();
        $this->model->recordStructureFields->record["user_id"]["curVal"] = "1B9D4793-D79A-413C-A705-1A49A297633B";
        $this->model->copyRecord();
        $this->model->auth_user();
        parent::__construct($loaded_model, $loaded_view, $action_name);
        $this->view->header_content_type = "application/json; charset=utf-8";
    }

    function LoadView_custom($action_name = null)
    {
        return "View";
    }

    function doAction_custom($action_name)
    {
        $call_action = "action_".$action_name;
        if(method_exists($this, $call_action)){
            $this->$call_action(true);
        }
    }

    function action_music()
    {
        define("MUSIC_COVERS_DIR", "MUSIC_COVERS_DIR");
        define("MUSIC_TRACKS_DIR", "MUSIC_TRACKS_DIR");
        $this->module_process("music", JOINT_SITE_EXEC_DIR."/api/module/music");
    }

    function action_users()
    {
        $this->module_process("users", JOINT_SITE_EXEC_DIR."/api/module/users");
    }

    function action_newrec()
    {
        $this->view->generateJson(parent::action_new($_GET)); // TODO: Change the autogenerated stub
        exit;
    }

    protected function action_deleterec()
    {
        $this->model->copyValFromRequest($_GET);
        if(!$this->model->copyRecord()) {
            jointSite::throwErr("request", "res-module-controller on delete");
        }
        $this->view->generateJson(parent::action_delete($_GET)); // TODO: Change the autogenerated stub
        exit;
    }
    protected function action_editrec()
    {
        $this->view->generateJson(parent::action_edit($_GET)); // TODO: Change the autogenerated stub
        exit;
    }

    protected function action_listrec()
    {
        $this->view->generateJson(parent::action_list($_GET)); // TODO: Change the autogenerated stub
        exit;
    }

    function makeSlaveRequest()
    {
        $slave_req = "rest_access_token=111";
        return $slave_req;
    }
}