<?php
class controller_records extends controller_api
{
    function __construct($loaded_model, $loaded_view, $action_name)
    {
        parent::__construct($loaded_model, $loaded_view, $action_name);
        $this->view->header_content_type = "application/json; charset=utf-8";
    }

    function LoadView_custom($action_name = null)
    {
        return "View";
    }

    function action_index()
    {
        $this->records_process(JOINT_SITE_EXEC_DIR."/api/records/users_dt", "users_dt", null);
    }

    function action_users_dt()
    {
        $this->records_process(JOINT_SITE_EXEC_DIR."/api/records/users_dt", "users_dt", null);
    }

    function doAction_custom($action_name)
    {
        $call_action = "action_".$action_name;
        if(method_exists($this, $call_action)){
            $this->$call_action(true);
        }
    }

    function action_newrec()
    {
        $this->view->generateJson(parent::action_new($_GET)); // TODO: Change the autogenerated stub
        exit;
    }

    protected function action_deleterec()
    {
        $this->view->generateJson(parent::action_delete($_GET)); // TODO: Change the autogenerated stub
        exit;
    }
    protected function action_editrec()
    {
        $this->view->generateJson(parent::action_edit($_GET)); // TODO: Change the autogenerated stub
        exit;
    }

    protected function action_listrec()
    {
        $this->view->generateJson(parent::action_list($_GET)); // TODO: Change the autogenerated stub
        exit;
    }

    function makeSlaveRequest()
    {
        $slave_req = "rest_access_token=111";
        return $slave_req;
    }

}