<?php
class ModuleRecordsController extends RecordsController
{
    /*modules from __config/modulesInfo.php */
    public $modules;
    /*current one module from modules to process*/
    public $module;

    function __construct()
    {
        $this->lang_map["menu-access-warning"] = array(
            "en" => "denied in ModuleRecordsController checkAccessMenu",
            "rus" => "Ошибка доступа в ModuleRecordsController checkAccessMenu",
        );
    }

    function loadView($type_of_view, $process_path, $custom_name = null)
    {
        $loaded_view = parent::loadView($type_of_view, $process_path, $custom_name);
        $loaded_view->module = $this->module;
        $loaded_view->logo = $this->module["mImg"];
        $loaded_view->shortcut_icon = $this->module["mImg"];
        if($this->model->access_rules["create_rule"] < 7){
            $loaded_view->hasAccessCreate = false;
        }
        $loaded_view->logo = $this->module["mImg"];
        return $loaded_view;
    }

    function loadModel($process_path, $custom_name = null)
    {
        $return_model = parent::loadModel($process_path, $custom_name); // TODO: Change the autogenerated stub
        $return_model->access_groups = $this->module["accessGroups"];
        $return_model->checkAccessModel();
        return $return_model;
    }

    function process_detail($process_path = null)
    {
        if($this->module["moduleTable"]["tableName"] == $this->model->tableName){
            if($this->module["bindTables"]){
                foreach ($this->module["bindTables"] as $tName => $tOptions){
                    if($tOptions["relationships"]){

                        $bindModel = $this->loadModel($this->module["mUrl"], $tOptions["tUrl"]);
                        $bindModel->getRecordStructure();

                        $bindModel_where = null;
                        $slave_req = null;
                        foreach ($tOptions["relationships"] as $mainTable_field=>$bindTable_field){
                            $slave_req.=$bindTable_field."=".$this->model->record[$mainTable_field]["curVal"]."&";
                            $bindModel_where.=$bindModel->tableName.".".$bindTable_field."='".$this->model->record[$mainTable_field]["curVal"]."' and";
                        }

                        $bindModel_where = substr($bindModel_where, 0, strlen($bindModel_where) -4);
                        $slave_req = substr($slave_req, 0, strlen($slave_req) -1);

                        $sup_cond = $bindModel->filterWhere("GET");

                        $sup_cond["where"] = " where ".$bindModel_where;

                        $bind_list_view = $this->loadView("list", $this->loaded_model_process_url);

                        $bind_list_view->newBtn_qry = "?".$slave_req;

                        $bind_list_view->process_url = $this->loaded_model_process_url;

                        $bind_list_view->listCount = $bindModel->countRecords($sup_cond["where"]);

                        $bind_list_view->listFields = $bindModel->listFields;
                        $bind_list_view->searchFields = $bindModel->searchFields;
                        $bind_list_view->listRecords = $bindModel->listRecords($sup_cond["where"], $sup_cond["order"], $sup_cond["limit"]);

                        if($this->model->modelAliases[$_SESSION["lang"]]){
                            $bind_list_view->h2 =$bindModel->modelAliases[$_SESSION["lang"]];
                        }else{
                            $bind_list_view->h2 = $tName;
                        }

                        $bind_list_view->list_frame_id = $bindModel->tableName;

                        $data["bindTables"][$bindModel->tableName] = array(
                            "html" => $bind_list_view->ctrlLine().
                                "<div class='list_table'>".
                                $bind_list_view->listViewTable().
                                "</div>".
                                $bind_list_view->scriptListViewCrtlPannel($slave_req),
                            "h3" => $bind_list_view->h2,
                        );
                    }
                }
                $this->view->bindTables = $data["bindTables"];
            }
        }
        parent::process_detail($process_path);
    }

    function edit_record()
    {
        $update = false;
        if($_POST){
            $this->model->copyPost();
            $update = true;
        }
        if($_FILES){
            $update = true;
            foreach ($_FILES as $file_field => $file_info){
                if($this->model->editFields[$file_field]["format"] == "file"){
                    $this->model->uploadRecordFile($file_field, false, true);
                }
            }
        }
        if($update){
            $this->view->action_log = array(
                "result" => $this->model->updateRecord(),
                "log" => $this->model->log_message,
            );
        }
        $this->model->copyCustomFields();
    }

    function checkAccessMenu($process_module_url)
    {
        require_once "application/core/Module/ModuleMenu.php";
        $checkMenuAccess = false;
        if($access_items = moduleMenu::sitemanMenuAccess()){
            foreach ($access_items as $mUrl => $mOpt){
                if($mUrl == $process_module_url){
                    $checkMenuAccess = true;
                    break;
                }
            }
        }

        if(!$checkMenuAccess){
            throwErr("access", $this->lang_map["menu-access-warning"][$_SESSION["lang"]]);
        }
    }

    public function module_process($mName)
    {
        global $routes;

        if($process_module = $this->modules[$mName]){
            $this->module = $this->modules[$mName];
            $this->checkAccessMenu($process_module["mUrl"]);

            $mUri_exp = explode("/", $process_module["mUrl"]);
            $mUri_cnt = count($mUri_exp);

            if(!$routes[$mUri_cnt+1]){
                $mainModel = $this->loadModel($process_module["mUrl"], $process_module["moduleTable"]["tUrl"]);

                $mainModel->getRecordStructure();
                $countMain_where = $mainModel->filterWhere()["where"];

                $process_module["moduleTable"]["countRecords"]=$mainModel->countRecords($countMain_where);

                if($process_module["bindTables"]){
                    foreach ($process_module["bindTables"] as $tName => $tOptions){
                        $bindModel = $this->loadModel($process_module["mUrl"], $tOptions["tUrl"]);
                        $bindModel->getRecordStructure();
                        $count_where = $bindModel->filterWhere()["where"];
                        $process_module["bindTables"][$tName]["countRecords"]=$bindModel->countRecords($count_where);
                    }
                }

                include "application/core/Module/ModulesStatView.php";
                $this->view = new ModulesStatView();

                $this->view->logo = $process_module["mImg"];

                $this->view->modules = $process_module;

                $this->view->generate();
            }else{

                if($process_module["moduleTable"]["tUrl"] == $routes[$mUri_cnt+1]){
                    $tProcess = $process_module["moduleTable"]["tUrl"];
                }elseif (!$process_module["moduleTable"]["tUrl"] and ($routes[$mUri_cnt+1] == $process_module["moduleTable"]["tableName"] )){
                    $tProcess = $process_module["moduleTable"]["tableName"];
                }else{

                    foreach ($process_module["bindTables"] as $tName => $tOptions){
                        if ($routes[$mUri_cnt+1] == $tOptions["tUrl"]){
                            $tProcess = $tOptions["tUrl"];
                            break;
                        }elseif(($routes[$mUri_cnt+1] == $tName)){
                            $tProcess = $tName;
                            break;
                        }
                    }
                }

                if($tProcess){
                    $this->module = $process_module;
                    $this->records_process($process_module["mUrl"], $tProcess, null);
                }else{
                    throwErr("request", "siteman module_process ".$mName." tProcess not found");
                }
            }
        }
    }

    function action_index()
    {
        require_once "application/core/Module/ModuleMenu.php";

        if($access_items = moduleMenu::sitemanMenuAccess()){
            $this->model = new Model_Siteman();
            include "application/core/Module/ModulesListView.php";
            $this->view = new ModulesListView();
            $this->view->modules = $this->modules;
            $this->view->access_items = $access_items;
            $this->view->generate();
        }else{
            throwErr("access", $this->lang_map["menu-index-warning"][$_SESSION["lang"]]);
        }
    }

    function delete_record($process_path, $custom_name)
    {
        if($this->module["moduleTable"]["tableName"] == $this->model->tableName) {
            if ($this->module["bindTables"]) {
                foreach ($this->module["bindTables"] as $tName => $tOptions){
                    if($tOptions["relationships"]){

                        $bindModel = $this->loadModel($this->module["mUrl"], $tOptions["tUrl"]);
                        $bindModel->getRecordStructure();

                        $bindModel_where = null;
                        $slave_req = null;
                        foreach ($tOptions["relationships"] as $mainTable_field=>$bindTable_field){
                            $slave_req.=$bindTable_field."=".$this->model->record[$mainTable_field]["curVal"]."&";
                            $bindModel_where.=$bindModel->tableName.".".$bindTable_field."='".$this->model->record[$mainTable_field]["curVal"]."' and";
                        }

                        $bindModel_where = substr($bindModel_where, 0, strlen($bindModel_where) -4);
                        $slave_req = substr($slave_req, 0, strlen($slave_req) -1);

                        $sup_cond = $bindModel->filterWhere("GET");

                        $sup_cond["where"] = " where ".$bindModel_where;

                        $listRecords = $bindModel->listRecords($sup_cond["where"], $sup_cond["order"], $sup_cond["limit"]);
                        if(is_array($listRecords)){
                            foreach ($listRecords as $list_num => $list_fields){
                                foreach ($bindModel->record as $fieldName => $fieldOptions){
                                    if($fieldOptions["indexes"]){
                                        $bindModel->record[$fieldName]["curVal"] = $list_fields[$fieldName];
                                    }
                                }

                                $bindModel->deleteRecord();
                            }
                        }

                    }
                }
            }
            parent::delete_record($process_path, $custom_name);
        }else{
            parent::delete_record($process_path, $custom_name);
        }
    }

    function action_jointApi()
    {
        if(($_GET["method"] == "list") or ($_GET["method"] == "fillDL")){
            if($_GET["process_path"]){
                if($_GET["custom_name"]){

                    $module_name = explode("/", $_GET["process_path"])[1];

                    if($this->module = $this->modules[$module_name]){

                        $apiModel = $this->loadModel($_GET["process_path"], $_GET["custom_name"]);
                        $apiModel->getRecordStructure();

                        $req_where = json_decode($_GET["where"], true);
                        $api_where = $apiModel->filterWhere("custom", $req_where);

                        $api_listRecords = $apiModel->listRecords($api_where["where"]);


                        if($_GET["method"] == "fillDL"){
                            if($_GET["findField"] and $_GET["returnKey"]){
                                $list_return = array("" => "");
                                if($api_listRecords){
                                    foreach ($api_listRecords as $list_num => $list_row){
                                        $list_return[$list_row[$_GET["returnKey"]]] = $list_row[$_GET["findField"]];
                                    }

                                }
                            }else{
                                $list_return = array(
                                    "error" => "fields not set",
                                );
                            }
                        }else{
                            $list_return = array(
                                "error" => "unknown api method fillDL only",
                            );
                        }
                    }else{
                        $list_return = array(
                            "error" => "unknown module_name",
                        );
                    }
                }else{
                    $list_return = array(
                        "error" => "custom_name is not set",
                    );
                }
            }else{
                $list_return = array(
                    "error" => "process_path is not set",
                );
            }
        }else{
            $list_return = array(
                "error" => "unknown api method",
            );
        }
        $this->view = new View();
        $this->view->generateJson($list_return);
    }
}
