<?php
class ModuleRecordsController extends RecordsController
{
    public $module;

    function __construct()
    {
        $this->lang_map["menu-access-warning"] = array(
            "en" => "denied in ModuleRecordsController checkAccessMenu",
            "rus" => "Ошибка доступа в ModuleRecordsController checkAccessMenu",
        );
    }

    function loadView($type_of_view, $process_path, $custom_name = null)
    {
        $loaded_view = parent::loadView($type_of_view, $process_path, $custom_name);
        $loaded_view->module = $this->module;
        $loaded_view->logo = $this->module["mImg"];
        if($this->model->access_rules["create_rule"] < 7){
            $loaded_view->hasAccessCreate = false;
        }
        $loaded_view->logo = $this->module["mImg"];
        return $loaded_view;
    }

    function loadModel($process_path, $custom_name = null)
    {
        $return_model = parent::loadModel($process_path, $custom_name); // TODO: Change the autogenerated stub
        $return_model->access_groups = $this->module["accessGroups"];
        $return_model->checkAccessModel();
        return $return_model;
    }

    function process_detail($process_path = null)
    {
        if($this->module["moduleTable"]["tableName"] == $this->model->tableName){
            if($this->module["bindTables"]){
                foreach ($this->module["bindTables"] as $tName => $tOptions){
                    if($tOptions["relationships"]){
                        if(file_exists($_SERVER["DOCUMENT_ROOT"]."/application/models/".
                            $this->module["mUrl"]."/record".$tOptions["tUrl"]."Model.php")){
                            require_once ($_SERVER["DOCUMENT_ROOT"]."/application/models/".
                                $this->module["mUrl"]."/record".$tOptions["tUrl"]."Model.php");
                            $type = "record".$tOptions["tUrl"]."Model";
                            $bindModel = new $type;
                            $bindModel_process_url = $process_path."/". $tOptions["tUrl"];

                        }else{
                            $bindModel = new ModuleRecordsModel();
                            $bindModel->tableName = $tName;
                            $bindModel_process_url= $process_path."/". $tName;
                        }

                        $bindModel->access_groups = $this->module["accessGroups"];
                        $bindModel->checkAccessModel();

                        $bindModel->getRecordStructure();

                        $bindModel_where = null;
                        $slave_req = null;
                        foreach ($tOptions["relationships"] as $mainTable_field=>$bindTable_field){
                            $slave_req.=$bindTable_field."=".$this->model->record[$mainTable_field]["curVal"]."&";
                            $bindModel_where.=$bindModel->tableName.".".$bindTable_field."='".$this->model->record[$mainTable_field]["curVal"]."' and";
                        }

                        $bindModel_where = substr($bindModel_where, 0, strlen($bindModel_where) -4);
                        $slave_req = substr($slave_req, 0, strlen($slave_req) -1);

                        $sup_cond = $bindModel->filterWhere("GET");

                        $sup_cond["where"] = " where ".$bindModel_where;

                        $bind_list_view = $this->loadView("list", $bindModel_process_url);

                        $bind_list_view->newBtn_qry = "?".$slave_req;

                        $bind_list_view->process_url = $bindModel_process_url;

                        $bind_list_view->listCount = $bindModel->countRecords($sup_cond["where"]);

                        $bind_list_view->listFields = $bindModel->listFields;
                        $bind_list_view->searchFields = $bindModel->searchFields;
                        $bind_list_view->listRecords = $bindModel->listRecords($sup_cond["where"], $sup_cond["order"], $sup_cond["limit"]);

                        if($this->model->modelAliases[$_SESSION["lang"]]){
                            $bind_list_view->h2 =$bindModel->modelAliases[$_SESSION["lang"]];
                        }else{
                            $bind_list_view->h2 = $tName;
                        }

                        $bind_list_view->list_frame_id = $bindModel->tableName;

                        $data["bindTables"][$bindModel->tableName] = array(
                            "html" => $bind_list_view->ctrlLine().
                                "<div class='list_table'>".
                                $bind_list_view->listViewTable().
                                "</div>".
                                $bind_list_view->scriptListViewCrtlPannel($slave_req),
                            "h3" => $bind_list_view->h2,
                        );
                    }
                }
                $this->view->bindTables = $data["bindTables"];
            }
        }
        parent::process_detail($process_path);
    }

    function edit_record()
    {
        $update = false;
        if($_POST){
            $this->model->copyPost();
            $update = true;
        }
        if($_FILES){
            $update = true;
            foreach ($_FILES as $file_field => $file_info){
                if($this->model->editFields[$file_field]["format"] == "file"){
                    $this->model->uploadRecordFile($file_field, false, true);
                }
            }
        }
        if($update){
            $this->view->action_log = array(
                "result" => $this->model->updateRecord(),
                "log" => $this->model->log_message,
            );
        }
        $this->model->copyCustomFields();
    }

    public function module_process($mName)
    {
        global $routes;

        if($process_module = $this->modules[$mName]){




            require_once "application/core/Module/ModuleMenu.php";
            $checkMenuAccess = false;
            if($access_items = moduleMenu::sitemanMenuAccess()){
                foreach ($access_items as $mUrl => $mOpt){
                    if($mUrl == $process_module["mUrl"]){
                        $checkMenuAccess = true;
                        break;
                    }
                }
            }

            if(!$checkMenuAccess){
                throwErr("access", $this->lang_map["menu-access-warning"][$_SESSION["lang"]]);
            }

            $mUri_exp = explode("/", $process_module["mUrl"]);
            $mUri_cnt = count($mUri_exp);

            if(!$routes[$mUri_cnt+1]){
                $mainModel = $this->loadModel($process_module["mUrl"], $process_module["moduleTable"]["tUrl"]);

                $mainModel->getRecordStructure();

                $process_module["moduleTable"]["countRecords"]=$mainModel->countRecords();

                if($process_module["bindTables"]){
                    foreach ($process_module["bindTables"] as $tName => $tOptions){
                        $bindModel = $this->loadModel($process_module["mUrl"], $tOptions["tUrl"]);
                        $bindModel->getRecordStructure();
                        $count_where = $bindModel->filterWhere()["where"];
                        if($count_where){
                            $count_where.="where ".$count_where;
                        }
                        $process_module["bindTables"][$tName]["countRecords"]=$bindModel->countRecords($count_where);
                    }
                }

                include "application/core/Module/ModulesStatView.php";
                $this->view = new ModulesStatView();

                $this->view->logo = $process_module["mImg"];

                $this->view->modules = $process_module;

                $this->view->generate();
            }else{

                if($process_module["moduleTable"]["tUrl"] == $routes[$mUri_cnt+1]){
                    $tProcess = $process_module["moduleTable"]["tUrl"];
                }elseif (!$process_module["moduleTable"]["tUrl"] and ($routes[$mUri_cnt+1] == $process_module["moduleTable"]["tableName"] )){
                    $tProcess = $process_module["moduleTable"]["tableName"];
                }else{

                    foreach ($process_module["bindTables"] as $tName => $tOptions){
                        if ($routes[$mUri_cnt+1] == $tOptions["tUrl"]){
                            $tProcess = $tOptions["tUrl"];
                            break;
                        }elseif(($routes[$mUri_cnt+1] == $tName)){
                            $tProcess = $tName;
                            break;
                        }
                    }
                }

                if($tProcess){
                    $this->module = $process_module;
                    $this->records_process($process_module["mUrl"], $tProcess, null);
                }else{
                    throwErr("request", "siteman module_process ".$mName." tProcess not found");
                }
            }
        }
    }

    function action_index()
    {
        require_once "application/core/Module/ModuleMenu.php";

        if($access_items = moduleMenu::sitemanMenuAccess()){
            $this->model = new Model_Siteman();
            include "application/core/Module/ModulesListView.php";
            $this->view = new ModulesListView();
            $this->view->modules = $this->modules;
            $this->view->access_items = $access_items;
            $this->view->generate();
        }else{
            throwErr("access", $this->lang_map["menu-index-warning"][$_SESSION["lang"]]);
        }
    }

    function fillDataList()
    {
        if($_GET["fillDl"] == "yyy"){
            $this->view = new View();
            if($_GET["table"]){

                $list_qry = "select ".$_GET["findField"].", ".$_GET["returnKey"]." from ".$_GET["table"]." where ".$_GET["findField"]." like '%".$_GET["findValue"]."%'";
                $this->model = new Model();
                $list_res = $this->model->query($list_qry);
                $list_return = array("" => "");
                if($list_res->rowCount()){
                    while ($list_row = $list_res->fetch(PDO::FETCH_ASSOC)){
                        $list_return[$list_row[$_GET["returnKey"]]] = $list_row[$_GET["findField"]];
                    }
                }

                $this->view->generateJson($list_return);
            }

            return true;
        }
    }

    function delete_record($process_path, $custom_name)
    {
        if($this->module["moduleTable"]["tableName"] == $this->model->tableName) {
            if ($this->module["bindTables"]) {
                foreach ($this->module["bindTables"] as $tName => $tOptions){
                    if($tOptions["relationships"]){



                        if(file_exists($_SERVER["DOCUMENT_ROOT"]."/application/models/".
                            $this->module["mUrl"]."/record".$tOptions["tUrl"]."Model.php")){
                            require_once ($_SERVER["DOCUMENT_ROOT"]."/application/models/".
                                $this->module["mUrl"]."/record".$tOptions["tUrl"]."Model.php");
                            $type = "record".$tOptions["tUrl"]."Model";
                            $bindModel = new $type;
                            $bindModel_process_url = $process_path."/". $tOptions["tUrl"];

                        }else{
                            $bindModel = new ModuleRecordsModel();
                            $bindModel->tableName = $tName;
                            $bindModel_process_url= $process_path."/". $tName;
                        }

                        $bindModel->access_groups = $this->module["accessGroups"];
                        $bindModel->checkAccessModel();

                        $bindModel->getRecordStructure();

                        $bindModel_where = null;
                        $slave_req = null;
                        foreach ($tOptions["relationships"] as $mainTable_field=>$bindTable_field){
                            $slave_req.=$bindTable_field."=".$this->model->record[$mainTable_field]["curVal"]."&";
                            $bindModel_where.=$bindModel->tableName.".".$bindTable_field."='".$this->model->record[$mainTable_field]["curVal"]."' and";
                        }

                        $bindModel_where = substr($bindModel_where, 0, strlen($bindModel_where) -4);
                        $slave_req = substr($slave_req, 0, strlen($slave_req) -1);

                        $sup_cond = $bindModel->filterWhere("GET");

                        $sup_cond["where"] = " where ".$bindModel_where;

                        $listRecords = $bindModel->listRecords($sup_cond["where"], $sup_cond["order"], $sup_cond["limit"]);
                        if(is_array($listRecords)){
                            foreach ($listRecords as $list_num => $list_fields){
                                foreach ($bindModel->record as $fieldName => $fieldOptions){
                                    if($fieldOptions["indexes"]){
                                        $bindModel->record[$fieldName]["curVal"] = $list_fields[$fieldName];
                                    }
                                }

                                $bindModel->deleteRecord();
                            }
                        }

                    }
                }
            }
            parent::delete_record($process_path, $custom_name);
        }else{
            parent::delete_record($process_path, $custom_name);
        }
    }
}