<?php


namespace Src\Views\Kip;


use JointApp\Views\Records\RecordListView;
use JointApp\Views\Modules\ModuleEditView;
//use JointApp\Views\SiteView;
use JointApp\Interfaces\LangWebViewInterface;

class View_Kip_Tasks_Edit extends ModuleEditView
{
    /*
    public string $logo = '/img/popimg/blog-logo.png';
    public string $shortcutIcon = '/img/popimg/blog-icon.png';

    public array $artsList = [];
    public array $filterCats = [];
    public int $blogCountArts = 0;
    public int $curPage = 1;
    public int $onPage = 4;
    public int $inRow = 2;

    const ART_COVERS = '/userdata/blog/covers';

    public function addViewParams($addViewParams)
    {
        parent::addViewParams($addViewParams);
        $addParams = new \stdClass();
        $addParams->artsList = $this->artsList;
        $addParams->filterCats = $this->filterCats;
        $addParams->blogCountArts = $this->blogCountArts;
        $addParams->curPage = $this->curPage;
        $addParams->onPage = $this->onPage;
        $addParams->inRow = $this->inRow;
        $addViewParams($addParams);
    }

    public static function loadLangView(string $docRoot = __DIR__, string $viewLang = 'ru', $loads = []): LangWebViewInterface
    {
        $lang = 'LangFiles_' . self::langNs($viewLang) . '_Views_BlogMain';
        $loads[] = [$lang => $docRoot . '/LangFiles/Views/Blog/' . $lang];
        return parent::loadLangView($docRoot, $viewLang, $loads);
    }
*/
    public static function addScriptLinks(callable $addScriptLinks): void
    {
        parent::addScriptLinks($addScriptLinks); // TODO: Change the autogenerated stub
        $addScriptLinks(['/js/kip/kip-main.js',]);
    }
/*
    public static function addStyleLinks(callable $addStyleLinks): void
    {
        parent::addStyleLinks($addStyleLinks);
        $addStyleLinks([
            '/css/blog/blogMain.css',
            '/css/blog/blogOptionsPanel.css',
        ]);
    }

    public static function createPageContent(\stdClass $langPageContent, \stdClass $viewParams):string
    {
        return self::printFilterBlock($langPageContent->langBlogFilter, $viewParams->filterCats).
            '<div class="contentBlock-frame"><div class="contentBlock-center">'.
            '<div class="contentBlock-wrap">'.
            '<div class="blog-options">'.
            self::printCountArts($langPageContent->foundLabel, $viewParams->blogCountArts).
            '<div class="blog-pagination">'.
            self::printPaginationBlock($langPageContent->langPg, $viewParams->blogCountArts, $viewParams->curPage, $viewParams->onPage).
            '</div>'.
            self::printSortBlock($langPageContent->langSortBlock).
            self::printViewOptionsBlock($langPageContent->langViewOpt).
            '</div></div></div></div>'.
            '<div class="contentBlock-frame"><div class="contentBlock-center">'.
            '<div class="contentBlock-wrap">'.
            '<div class="blog-art-list">'.
            self::printArtListBlock($langPageContent->langArtList, $viewParams->artsList, $viewParams->inRow, $viewParams->langSl).
            '</div></div></div></div>';
    }

    public static function printFilterBlock(\stdClass $langBlogFilter, array $filterCats)
    {
        $return =
            '<div class="contentBlock-frame"><div class="contentBlock-center">'.
            '<div class="contentBlock-wrap">'.
            '<div class="blog-filter">'.
            '<div class="blog-filter-cat">'.
            '<label for="blog-filter-cat">'.$langBlogFilter->labelCats.'</label>'.
            '<select id="blog-filter-cat">';

        $catCounter = 0;
        foreach ($filterCats as $cat_id => $catName){
            $selected = '';
            if($catCounter == 0){
                $selected = ' selected';
            }
            $return .= '<option value="'.$cat_id.'"'.$selected.'>'.$catName.'</option>';

            $catCounter++;
        }
        $return .='</select>'.
            '</div>'.
            '<div class="blog-filter-artName">'.
            '<input type="text" id="blog-filter-artName" value="" placeholder="'.$langBlogFilter->artNamePh.'">'.
            '<button on onclick="filterBlog()"><img src="/img/popimg/search-icon.png">'.$langBlogFilter->findBtn.'</button>'.
            '</div>'.
            /*'<div class="blog-filter-tags">'.
            '<span>Тэги:</span>'.
            '<span>php</span>'.
            '<span>job</span>'.
            '<span>xxx</span>'.
            '</div>'.*/
            /*'</div></div></div></div>';

        return $return;
    }

    public static function printPaginationBlock(\stdClass $langPg, int $recordsCount, int $curPage, int $onPage):string
    {
        $return = RecordListView::paginationPrint($langPg, $recordsCount, $curPage, $onPage);
        return $return;
    }

    public static function printArtListBlock(\stdClass $langArtList, array $artListArr, int $inRow, string $langSl):string
    {
        $return = '';
        $len_cnt = 0;
        //$inRow optional: count cells in table row
        $pag_length = 2;    //optional:

        foreach ($artListArr as $num => $row) {

            if ($len_cnt == $inRow) {
                $len_cnt = 0;
            }

            if ($len_cnt == 0) {
                $return .= "<div class='blog-wrap-" . $inRow . "'>";
            }


            if ($row['refreshDate']) {
                $printDate = $langArtList->refreshText.": " . $row['refreshDate'];
            } else {
                $printDate = $langArtList->pubText.": " . $row['pubDate'];
            }

            $return .= '<div class="blog-art-container">'.
                '<img src="'.self::ART_COVERS.'/'.$row['artImg'].'" alt="art-img">'.
                '<div class="blog-art-header">' .
                '<a href="'.$langSl.'/blog/article/'.$row['artRef'].'" title="'.$langArtList->refTitle.' rightjoint.ru">'.$row['artName'].'</a>'.
                '<hr>'.
                '</div>'.
                '<div class="blog-art-refresh">'.$printDate.'</div>'.
                '<div class="blog-art-meta">'.$row['artMeta'].'</div>'.
                '<a class="blog-art-button" href="'.$langSl.'/blog/article/'.$row['artRef'].'" title="'.$langArtList->refTitle.' rightjoint.ru">'.
                $langArtList->refText.'</a>'.
                '</div>';

            if (($len_cnt + 1) == $inRow) {
                $return .= "</div>";
            }

            $len_cnt++;
        }

        return $return;
    }

    public static function printCountArts(string $foundLabel, int $countArts):string
    {
        $return =
            '<div class="blog-count"><label>'.$foundLabel.'</label>'.
            '<span id="blog-count-arts">'.$countArts.'</span></div>';

        return $return;
    }

    public static function printSortBlock(\stdClass $langSortBlock):string
    {
        $return =
            '<div class="blog-sort">'.
            '<label for="blog-sort-field">'.$langSortBlock->labelSortField.'</label>'.
            '<select id="blog-sort-field">'.
            '<option value="pubDate">'.$langSortBlock->optPubDate.'</option>'.
            '<option value="refreshDate">'.$langSortBlock->optRefreshDate.'</option>'.
            '<option value="artName">'.$langSortBlock->optArtName.'</option>'.
            '</select>'.
            '<label for="blog-sort-order">'.$langSortBlock->labelSortOrderBy.'</label>'.
            '<select id="blog-sort-order">'.
            '<option value="DESC">'.$langSortBlock->optOrderDesc.'</option>'.
            '<option value="ASC">'.$langSortBlock->optOrderAsc.'</option>'.
            '</select>'.
            "</div>";
        return $return;
    }

    public static function printViewOptionsBlock(\stdClass $langViewOpt)
    {
        $return ='<div class="blog-view-options">'.
            '<label for="blog-on-page">'.$langViewOpt->labelOnPage.'</label>'.
            '<select id="blog-on-page">'.
            '<option value="2">2</option>'.
            '<option value="3">3</option>'.
            '<option value="4" selected>4</option>'.
            '<option value="10">10</option>'.
            '</select>'.
            '<label for="blog-in-row">'.$langViewOpt->labelInRow.'</label>'.
            '<select id="blog-in-row">'.
            '<option value="1">1</option>'.
            '<option value="2" selected>2</option>'.
            '<option value="3">3</option>'.
            '<option value="4">4</option>'.
            '</select>'.
            '</div>';
        return $return;
    }
    */
}