<?php
class LangFiles_En_Views_ErrorsView extends LangFiles_En_Views_SiteView
{
    static public function getLangPageContent(): stdClass
    {
        $langPageContent = parent::getLangPageContent(); // TODO: Change the autogenerated stub
        $langPageContent->topText = 'At this page displaying catched errors. If you are here, something gone wrong.';
        $langPageContent->bottomText = 'Error occurred';
        return $langPageContent;
    }
}