<?php
class LangFiles_Ru_Views_ErrorsView extends LangFiles_Ru_Views_SiteView
{
    static public function getLangPageContent(): stdClass
    {
        $langPageContent = parent::getLangPageContent(); // TODO: Change the autogenerated stub
        $langPageContent->topText = 'На этой странице отображаются ошибки, перехваченные приложением. Если вы здесь, значит что-то пошло не так.';
        $langPageContent->bottomText = 'ОШИБКА';
        return $langPageContent;
    }
}