<?php

namespace JointApp\Views\Records;

//use JointApp\Records\ViewTemplates\RecordView;

use JointApp\Interfaces\LangWebViewInterface;
use JointApp\JointAppRequest;

class RecordEditView extends RecordView
{
    /*controller set up fields-------------------------------------------*/
    //result of CRUD actions from from model
    //empty if no action on display view
    public bool|null $actionResult = null;
    //message of CRUD actions from from model
    //empty if no action on display view
    public string|null $logMessage = '';
    //model recordStructuteFields->editFields (rsf) from model
    public $editFields = [];
    //type of view for action edit or new cause use the same template
    public string $type = 'edit';

    /*other declared fields----------------------------------------------*/
    public string $logo = '/img/popimg/edit-icon.png';

    public static function loadLangView(string $docRoot = __DIR__, string $viewLang = 'ru', $loads = []):LangWebViewInterface
    {
        $name = 'LangFiles_'.self::langNs($viewLang).'_Views_Templates_RecordEdit';
        $loads[] = [$name => $docRoot.'/JointApp/LangFiles/Views/Templates/'.$name];

        return parent::loadLangView($docRoot, $viewLang, $loads);
    }

    public static function addStyleLinks(callable $addStyleLinks): void
    {
        parent::addStyleLinks($addStyleLinks); // TODO: Change the autogenerated stub
        $addStyleLinks(['/css/records.css',]);
    }

    public function addViewParams($addViewParams)
    {
        parent::addViewParams($addViewParams);
        $addParams = new \stdClass();
        $addParams->type = $this->type;
        $addParams->logMessage = $this->logMessage;
        $addParams->actionResult = $this->actionResult;
        $addParams->editFields = $this->editFields;
        $addViewParams($addParams);
    }

    public function langHeaderUpdate(callable $updateFromArray)
    {
        $updateFromArray(['type' => $this->type, 'tableName' => $this->h2]);
    }

    public static function createPageContent(\stdClass $langPageContent, \stdClass $viewParams):string
    {



        $pageContent = '<div class="contentBlock-frame"><div class="contentBlock-center">'.
            '<div class="contentBlock-wrap">'.
            '<div class="edit-record-frame">';
        if ($viewParams->h2) {
            $pageContent.= '<h2><a href="'.$viewParams->langSl.$viewParams->process_url.'">'.$viewParams->h2.'</a></h2>';
        }
        $pageContent.= '<form class="editForm" method="post" enctype="multipart/form-data">';

        foreach ($viewParams->editFields as $fieldName => $fieldData) {
            if(isset($viewParams->fieldAliases[$fieldName])){
                $name_input = $viewParams->fieldAliases[$fieldName];
            }else{
                $name_input = $fieldName;
            }
            $htmlInput = self::getInputType($fieldName, $fieldData, $name_input);
            $pageContent.= $htmlInput->getHtml();
        }
        $pageContent.= '<div class="submit-line">';
        if($viewParams->actionResult !== null){
            if($viewParams->actionResult){
                $sub_class = 'well';
            }else{
                $sub_class = 'fail';
            }
            $pageContent.= '<div class="action-log '.$sub_class.'">'.$viewParams->logMessage.'</div>';
        }
        $pageContent.= '<input name="submit" type="submit" value="';
        if($viewParams->type == 'edit'){
            $pageContent.=$langPageContent->editView->submitUpdate;
        }elseif($viewParams->type == 'new'){
            $pageContent.=$langPageContent->editView->submitNew;
        }elseif($viewParams->type == 'delete'){
            $pageContent.=$langPageContent->editView->submitDel;
        }

        $pageContent.='"> </div>'.
            '</form>'.
            '</div>'.
            '</div>'.
            '</div>'.
            '</div>';
        return $pageContent;
    }
}