<?php

namespace JointApp\Views\Records;



use JointApp\Interfaces\LangWebViewInterface;

class RecordListView extends RecordView
{
    public string $type = 'list';

    /*3-viewFilterBody or viewFilterQuery----------------------------------*/
    public int $curPage = 1;
    public int $onPage = 10;

    /*5-controller set up fields-------------------------------------------*/
    //typically its model tableName, need when use two or more list tables
    public string|null $list_frame_id = '';

    /*-------------------------------------------------------------------*/

    public string $logo = '/img/popimg/editRecords.png';

    public $listFields = [];
    public $listRecords = [];
    public $searchFields = [];

    public int $listCount = 0;


    public $newBtn_qry = null;
    public $hasAccessCreate = true;
    public $slave_req = '';
    public $onPage_list= array(
        10, 20, 50, 100
    );

    public static function loadLangView(string $docRoot = __DIR__, string $viewLang = 'ru', $loads = []):LangWebViewInterface
    {
        $name = 'LangFiles_'.self::langNs($viewLang).'_Views_Templates_RecordsList';
        $loads[] = [$name => $docRoot.'/JointApp/LangFiles/Views/Templates/'.$name];

        return parent::loadLangView($docRoot, $viewLang, $loads);
    }

    public static function addScriptLinks(callable $addScriptLinks): void
    {
        parent::addScriptLinks($addScriptLinks); // TODO: Change the autogenerated stub
        $addScriptLinks(['/js/records.js',]);
    }

    public static function addStyleLinks(callable $addStyleLinks): void
    {
        parent::addStyleLinks($addStyleLinks); // TODO: Change the autogenerated stub
        $addStyleLinks(['/css/records.css',]);
    }

    function langHeaderUpdate(callable $updateFromArray):void
    {
        $updateFromArray(['h1' => $this->h2]);
    }

    function langHeadUpdate(callable $updateFromArray):void
    {
        $updateFromArray(['title' => $this->h2]);
    }

    public function addViewParams($addViewParams)
    {
        parent::addViewParams($addViewParams);
        $addParams = new \stdClass();
        $addParams->curPage = $this->curPage;
        $addParams->onPage = $this->onPage;
        $addParams->list_frame_id = $this->list_frame_id;
        $addParams->listFields = $this->listFields;
        $addParams->listRecords = $this->listRecords;
        $addParams->searchFields = $this->searchFields;
        $addParams->listCount = $this->listCount;
        $addParams->newBtn_qry = $this->newBtn_qry;
        $addParams->hasAccessCreate = $this->hasAccessCreate;
        $addParams->slave_req = $this->slave_req;
        $addParams->onPage_list = $this->onPage_list;
        $addViewParams($addParams);
    }

    public static function createPageContent(\stdClass $langPageContent, \stdClass $viewParams):string
    {
        return static::filterView($langPageContent->fiterView, $viewParams).
        static::listView($langPageContent->fiterView, $viewParams);
    }

    private static function filterView(\stdClass $langFilterView, \stdClass $viewParams = null)
    {
        $return_text = '<div class="contentBlock-frame"><div class="contentBlock-center">'.
            '<div class="contentBlock-wrap">'.
            '<div class="search_frame">'.
            '<form class="filterForm" method="post">';
        if(isset($viewParams->searchFields)){
            if(count($viewParams->searchFields)){
                foreach ($viewParams->searchFields as $fieldName=>$fieldData){
                    if(isset($fieldData['search']) and $fieldData['search'] == true){
                        if(isset($viewParams->fieldAliases[$fieldName])){
                            $name_input = $viewParams->fieldAliases[$fieldName];
                        }else{
                            $name_input = $fieldName;
                        }

                        $htmlInput = self::getInputType($fieldName, $fieldData, $name_input);
                        $return_text.=$htmlInput->getHtml();
                    }
                }
            }
        }


        $return_text.= '<div class="apply-line">';
        $return_text.= '<input type="button" class="applyFilterForm" '.
            'value="'.$langFilterView->list_table['btn_clear'].'" '.
            'onclick="clearSearchInputs()">'.
            '<input type="button" class="applyFilterForm" '.
            'value="'.$langFilterView->list_table['btn_apply'].'" '.
            'onclick="applyFilterForm()">'.
            '</div>'.
            '<input type="hidden" name="applyFilterRec" value="1">'.
            '</form>'.
            '</div>'.
            '</div>'.
            '</div>'.
            '</div>';

        return $return_text;
    }

    public static function listView($langFilterView, \stdClass $viewParams = null):string
    {
        $return = '<div class="contentBlock-frame"><div class="contentBlock-center">'.
            '<div class="contentBlock-wrap">'.
            '<div class="list_frame" id="'.$viewParams->list_frame_id.'">';
        if($viewParams->h2){
            $return.= '<h2>'.$viewParams->h2.'</h2>';
        }
        $return.= static::ctrlLine($langFilterView, $viewParams).
            '<div class="list_table">'.
            static::listViewTable($langFilterView, $viewParams).
            '</div>'.
            static::scriptListViewCrtlPannel($viewParams->list_frame_id, $viewParams->process_url, $viewParams->slave_req).
            self::scriptSortBlock($viewParams->list_frame_id).
            '</div>'.
            '</div>'.
            '</div>'.
            '</div>';

        return $return;
    }

    private static function scriptSortBlock(string $list_frame_id = ''):string
    {
        return '<script>$("#'.$list_frame_id.'").recordsSortBlock();</script>';
    }

    public static function scriptListViewCrtlPannel(string $list_frame_id = '', string $process_url = '', string $slave_req = '')
    {
        return '<script>$("#'.$list_frame_id.'").recordsPgBlock("'.$process_url.'", "'.$slave_req.'");</script>';
    }

    public static function listPgView($langFilterView, \stdClass $viewParams = null)
    {
        return '<span class="found_label">'.$langFilterView->list_table['found'].
            ': <span>'.$viewParams->listCount.'</span></span>'.
            self::paginationPrint($langFilterView->langPg, $viewParams->listCount, $viewParams->curPage, $viewParams->onPage);
    }

    public static function ctrlLine($langFilterView, \stdClass $viewParams = null)
    {
        $return_ajax = '<div class="ctrl-line">'.
            '<div class="pagination">'.
            static::listPgView($langFilterView, $viewParams);

        $return_ajax.= '</div>'.
            '<div class="sort-block">'.
            '<span class="found_label">'.$langFilterView->list_table['list_by'].': </span>'.
            '<select name="onPage">';
        foreach ($viewParams->onPage_list as $onPage){
            $return_ajax.= '<option value="'.$onPage.'"';
            if($onPage == $viewParams->onPage){
                $return_ajax.= ' selected';
            }
            $return_ajax.= '>'.$onPage.'</option>';
        }


        $sortOrder_asc = 'selected';
        $sortOrder_desc = null;
        $count_of = 0;
        $sortFields_options = null;
        foreach ($viewParams->searchFields as $fieldName=>$fieldData){
            if($fieldData['format'] != 'hidden'){
                $count_of++;
                if($count_of == 1){
                    if(isset($fieldData['sortOrder']) and $fieldData['sortOrder'] == 'DESC'){
                        $sortOrder_desc = 'selected';
                        $sortOrder_asc = null;
                    }
                }

                if(isset($viewParams->fieldAliases[$fieldName])){
                    $option_text = $viewParams->fieldAliases[$fieldName];
                }else{
                    $option_text = $fieldName;
                }

                $sortFields_options.='<option value="'.$fieldName.'">'.$option_text.'</option>';


            }
        }
        $return_ajax.= '</select>'.
            '<span class="sortField">'.$langFilterView->list_table['sort'].': </span>'.
            '<select name="sortField">'.$sortFields_options.'</select>'.
            '<select name="sortOrder"><option value="ASC" '.$sortOrder_asc.'>ASC</option><option value="DESC" '.$sortOrder_desc.'>DESC</option></select>'.
            '</div>'.
            '<div class="new-block">';
        if($viewParams->hasAccessCreate){
            $return_ajax.='<a href="'.$viewParams->langSl.$viewParams->process_url.'/newview'.
                $viewParams->newBtn_qry.'" class="newRecLink">'.$langFilterView->list_table['new'].'</a>';
        }

        $return_ajax.='</div>'.
            '</div>';
        return $return_ajax;
    }

    public static function listViewTable($langFilterView, \stdClass $viewParams = null)
    {
        $return_text = null;

        if($viewParams->listRecords){
            $return_text .= '<table>'.
                '<tr class="fCaption">';
            foreach ($viewParams->listFields as $fieldName => $fieldInfo){

                $return_text.= '<td';
                if(isset($fieldInfo['format']) and ( $fieldInfo['format']== 'hidden')){
                    $return_text.= ' style="display:none;"';
                }
                $return_text.='>';
                if ($fieldName == 'btnEdit'){
                    $return_text.= $langFilterView->list_table['cell_edit'];
                }elseif ($fieldName == 'btnDelete'){
                    $return_text.= $langFilterView->list_table['cell_del'];
                }elseif ($fieldName == 'btnDetail'){
                    $return_text.= $langFilterView->list_table['cell_view'];
                }elseif(isset($viewParams->fieldAliases[$fieldName])){
                    $return_text.= $viewParams->fieldAliases[$fieldName];
                }else{
                    $return_text.= $fieldName;
                }
                $return_text.= '</td>';
            }
            $return_text.= '</tr>';

            foreach($viewParams->listRecords as $row_num => $row){
                $return_text.= '<tr>';
                foreach ($viewParams->listFields as $fieldName => $fieldInfo){
                    $name_print = null;
                    if(isset($fieldInfo['useName'])){
                        $name_print = ' name="'.$row[$fieldInfo['useName']].'" ';
                    }

                    $return_text.= '<td';
                    if(isset($fieldInfo['format']) and ($fieldInfo["format"] == 'hidden')){
                        $return_text.= ' style="display:none;"';
                    }
                    $return_text.= '>';

                    if ($fieldInfo['format'] == 'file'){

                        if($row[$fieldName]){
                            if($fieldInfo['file_options']['file_type'] == 'img'){
                                $imgLink = null;
                                if($fieldInfo['file_options']['load_dir']){

                                    if(isset($fieldInfo['replaces'])){
                                        $imgLink = $fieldInfo['file_options']['load_dir'];
                                        if($fieldInfo['replaces']){
                                            foreach ($fieldInfo['replaces'] as $replace){
                                                $imgLink = str_replace($replace, $row[$replace], $imgLink);
                                            }
                                        }
                                    }else{
                                        $imgLink = $fieldInfo['file_options']['load_dir'].'/'.$row[$fieldName];
                                    }
                                }

                                if($imgLink){
                                    $return_text.='<img class="cell-img" src="'.$imgLink.'">';
                                }else{
                                    $return_text.= 'file:'.$fieldInfo['file_options']['file_type'].':'.$fieldInfo['file_options']['load_dir'].'='.
                                        $row[$fieldName];
                                }
                            }else{
                                $return_text.= 'file:'.$fieldInfo['file_options']['file_type'].':'.$fieldInfo['file_options']['load_dir'].'='.
                                    $row[$fieldName];
                            }
                        }
                    }elseif($fieldInfo['format'] == 'link'){
                        if(in_array($fieldName, array('btnDetail', 'btnEdit', 'btnDelete'))){
                            $urlLink = null;
                            if($fieldInfo['replaces']){
                                $urlLink = $fieldInfo['url'];
                                foreach ($fieldInfo['replaces'] as $replace){
                                    $repl_pos = strpos($urlLink, $replace);
                                    $urlLink_1 = substr($urlLink, 0, $repl_pos+strlen($replace)+1);
                                    $urlLink_2 = substr($urlLink, $repl_pos+strlen($replace)+1, strlen($urlLink));
                                    $urlLink_3 = str_replace($replace, $row[$replace], $urlLink_2);
                                    $urlLink = $urlLink_1.$urlLink_3;
                                }
                            }
                            //$urlLink .="&".$this->slave_req;
                            if ($fieldName == 'btnDetail'){
                                $return_text.= '<a href="'.$viewParams->langSl.$viewParams->process_url.'/detailview?'.
                                    $urlLink.'" class="list-btn">'.
                                    '<img src="/img/popimg/eye-icon.png"></a>';
                            }elseif ($fieldName == 'btnEdit'){
                                if(!isset($row['btnEdit']) or $row['btnEdit']!='disabled'){
                                    $return_text.= '<a href="'.$viewParams->langSl.$viewParams->process_url.'/editview?'.
                                        $urlLink.'" class="list-btn">'.
                                        '<img src="/img/popimg/edit-icon.png"></a>';
                                }
                            }elseif ($fieldName == 'btnDelete'){
                                if(!isset($row['btnDelete']) or $row['btnDelete']!='disabled'){
                                    $return_text.= '<a href="'.$viewParams->langSl.$viewParams->process_url.'/deleteview?'.
                                        $urlLink.'" class="list-btn">'.
                                        '<img src="/img/popimg/drop-icon.png"></a>';
                                }
                            }
                        }else{
                            $urlLink = null;
                            if($fieldInfo['replaces']){
                                $urlLink = $fieldInfo['url'];
                                foreach ($fieldInfo['replaces'] as $replace){
                                    $repl_pos = strpos($urlLink, $replace);
                                    $urlLink_1 = substr($urlLink, 0, $repl_pos+strlen($replace)+1);
                                    $urlLink_2 = substr($urlLink, $repl_pos+strlen($replace)+1, strlen($urlLink));
                                    $urlLink_3 = str_replace($replace, $row[$replace], $urlLink_2);
                                    $urlLink = $urlLink_1.$urlLink_3;
                                }
                            }
                            $return_text.= "<a href='".$viewParams->langSl.$urlLink."' title='edit'>".$row[$fieldName]."</a>";
                        }
                    }elseif($fieldInfo['format'] == 'ref'){
                        $urlLink = null;
                        if($fieldInfo['replaces']){
                            $urlLink = $fieldInfo['url'];
                            foreach ($fieldInfo['replaces'] as $replace){
                                $urlLink = str_replace($replace, $row[$replace], $urlLink);
                            }
                        }
                        $return_text.= '<a href="'.$viewParams->langSl.$viewParams->process_url.'/'.$urlLink.'" title="edit">'.$row[$fieldName].'</a>';

                    }elseif (($fieldInfo['format'] == 'varchar') or ($fieldInfo['format'] =='text')){
                        if(isset($fieldInfo['max_length']) and isset($row[$fieldName]) and  $fieldInfo['max_length'] < strlen($row[$fieldName]) ){
                            $return_text.= mb_substr($row[$fieldName], 0, $fieldInfo["max_length"]).' ...';
                        }else {
                            $return_text.=  $row[$fieldName];
                        }
                    }elseif (($fieldInfo['format'] == 'int') or ($fieldInfo['format'] =='float')
                        or ($fieldInfo['format'] =='datetime')or ($fieldInfo['format'] =='date')){
                        $return_text.=  $row[$fieldName];
                    }elseif (($fieldInfo['format'] == 'tinyint') or ($fieldInfo['format'] == 'checkbox')){
                        $return_text.= '<input type="checkbox" '.$name_print;
                        if($row[$fieldName]){
                            $return_text.= 'checked';
                        }
                        $return_text.='>';
                    }elseif ($fieldInfo['format'] == 'select'){
                        $return_text.= $fieldInfo['filling'][$row[$fieldName]];
                    }
                    else{
                        $custom_type = static::getCustomListType($fieldName, $row[$fieldName]);
                        if($custom_type != null){
                            $return_text.=$custom_type;
                        }else{
                            $return_text.= '<span>[format='.$fieldInfo['format'].']:</span>'.$row[$fieldName];
                        }
                    }
                    $return_text.= '</td>';
                }
                $return_text.= '</tr>';
            }
            $return_text.= '</table>';
        }
        return $return_text;
    }

    public static function getCustomListType($fieldName, $fieldVal)
    {

    }

    public static function paginationPrint(\stdClass $langPg, $recordsCount, $curPage, $onPage, $length=2, $pag_length=2):string
    {
        //$length = 2;        //optional: count cells in table row
        //$pag_length = 2;    //optional:
        if(round($recordsCount/$onPage) - $recordsCount/$onPage < 0){
            $page_count = round($recordsCount/$onPage) + 1;
        }else{
            $page_count =  round($recordsCount/$onPage);
        }

        $p_add_num_start = 0;

        if($curPage - $pag_length < 1){
            $p_add_num_start = $pag_length - $curPage +1;
        }

        $end_p_num = $curPage + $pag_length + $p_add_num_start;
        if($end_p_num > $page_count){
            $end_p_num = $page_count;
        }

        $start_p_num = $curPage - $pag_length + $p_add_num_start;
        if($end_p_num - $pag_length*2  < $start_p_num){
            $start_p_num = $end_p_num - $pag_length*2;
        }
        if($start_p_num < 1){
            $start_p_num = 1;
        }
        $page_list = null;
        for ($i = $start_p_num; $i <= $end_p_num; $i++){
            if ($curPage == $i){
                $page_list .= '<span class = "p_num active" page="'.$i.'">'.$i.'</span>';
            }else{
                if($i == 1){
                    $page_list .= '<span class = "p_num" page="'.$i.'" '.
                        '>'.$i.'</span>';
                }else{
                    $page_list .= '<span class = "p_num" page="'.$i.'" '.
                        '>'.$i.'</span>';
                }
            }
        }

        if($curPage < $page_count){
            $btn_nex = '<span class="p_btn next" page="'.($curPage+1).'" '.
                '>'.$langPg->next.'</span>';
        }else {
            $btn_nex = '<span class="p_btn next active" page="'.$curPage.'">'.$langPg->next.'</span>';
        }

        if ($curPage > 1){
            $btn_pre = '<span class="p_btn prev" page="'.($curPage-1).'" '.
                '>'.$langPg->pre.'</span>';
        }else {
            $btn_pre = '<span class="p_btn prev active" page="'.$curPage.'">'.$langPg->pre.'</span>';
        }

        return $btn_pre.$page_list.$btn_nex;
    }

}