<?php
class view_jointsite_siteman extends View_Products_JointSite
{
    public $current_branch = "siteman";

    function LoadViewLang($request = null)
    {
        parent::LoadViewLang($request = null); // TODO: Change the autogenerated stub
        require_once $_SERVER["DOCUMENT_ROOT"].JOINT_SITE_EXEC_DIR."/application/lang_files/views".
            "/products/lang_view_jointsite_siteman_".$_SESSION[JS_SAIK]["lang"].".php";
        return "lang_view_jointsite_siteman_".$_SESSION[JS_SAIK]["lang"];
    }

    function prod_about()
    {
     //   parent::prod_about(); // TODO: Change the autogenerated stub
    }

    function print_page_content()
    {
        $this->prod_about();
        $this->prod_menu();
        $this->prod_info();
        $this->prod_deploy();
        $this->principles_of_work();
    }

    function prod_menu()
    {
        echo "<div class='contentBlock-frame '><div class='contentBlock-center'>".
            "<div class='contentBlock-wrap'>".
            "<section class='prod-menu'>".
            "<h2>".$this->lang_map->prodmenu["h2_сontent"]."</h2>".
            "<ul>".
            "<li><a href='#product-info'>".$this->lang_map->prodmenu["h2_common"]."</a></li>".
            "<li><a href='#product-setup'>".$this->lang_map->prodmenu["h2_setup"]."</a></li>".
            "<li><a href='#principles_of_work'>".$this->lang_map->prodmenu["principles_of_work"]."</a></li>".
            "</ul>".
            "</section>".
            "</div></div></div>";

    }

    function principles_of_work()
    {
        /*
        include JOINT_SITE_CONF_DIR."/music_dir.php";
        require_once $_SERVER["DOCUMENT_ROOT"].JOINT_SITE_EXEC_DIR."/application/core/RecordsController.php";
        require_once $_SERVER["DOCUMENT_ROOT"].JOINT_SITE_EXEC_DIR."/application/core/ModuleController.php";
        $test_module_controller = new ModuleController("model_pdo", "View", "test");
        $test_module_controller->module_process("music", JOINT_SITE_EXEC_DIR."/products/jointsite/siteman");
*/

        /*
        include JOINT_SITE_CONF_DIR."/music_dir.php";
        require_once $_SERVER["DOCUMENT_ROOT"].JOINT_SITE_EXEC_DIR."/application/core/RecordsModel.php";
        require_once $_SERVER["DOCUMENT_ROOT"].JOINT_SITE_EXEC_DIR."/application/core/ModuleModel.php";
        require_once $_SERVER["DOCUMENT_ROOT"].JOINT_SITE_EXEC_DIR."/application/models/modules/music/m_model_musicalb.php";
        $test_module_model = new m_model_musicalb();
        $test_list = $test_module_model->listRecords(null, null, null, null);
        var_dump($test_list);
        */


        echo "<div class='contentBlock-frame'><div class='contentBlock-center'>".
            "<div class='contentBlock-wrap'>".
            "<section class='prod-test'>".
            "<h2 id='principles_of_work'>".$this->lang_map->prodmenu["principles_of_work"]."</h2>".
            "<div class='example'>".
            "<div class='example-code'>".
            "require_once $ _SERVER['DOCUMENT_ROOT'].JOINT_SITE_EXEC_DIR.'/application/core/RecordsController.php'".
            "require_once $ _SERVER['DOCUMENT_ROOT'].JOINT_SITE_EXEC_DIR.'/application/core/RecordsController.php'".
            "</div>".
            "<div class='example-code'>".
            "git checkout ".$this->lang_map->product_deploy["install"]["checkout-branch"].
            "</div>".
            "<div class='example-text'>".
            $this->lang_map->product_deploy["install"]["example-text"].
            "</div>".
            "</div>".
            "<h3>".$this->lang_map->principles_of_work["h3-1"]."</h3>".
            "<h3>".$this->lang_map->principles_of_work["h3-2"]."</h3>".
            "</section>".
            "</div></div></div>";
    }

    function prod_deploy_server()
    {

    }

    function print_prod_branches()
    {
        $this->print_branch("siteman");
    }

    function prod_info_custom()
    {
        echo "<div class='branches-block'>".
            "<p>".
            $this->lang_map->product_custom["p1"].
            "</p>";
        if(isset($this->lang_map->product_custom["p2"])){
            echo "<p>".
                $this->lang_map->product_custom["p2"].
                "</p>";
        }
        if(isset($this->lang_map->product_custom["p3"])){
            echo "<p>".
                $this->lang_map->product_custom["p3"].
                "</p>";
        }
        echo "<h3>".$this->lang_map->product_custom["h3-2"]."</h3>";
        $this->print_prod_branches();
        echo "</div>";
    }
}