<?php
class view_jointsite_module extends View_Products_JointSite
{
    public $current_branch = "module";

    function LoadViewLang($request = null)
    {
        parent::LoadViewLang($request = null); // TODO: Change the autogenerated stub
        require_once $_SERVER["DOCUMENT_ROOT"].JOINT_SITE_EXEC_DIR."/application/lang_files/views".
            "/products/lang_view_jointsite_module_".$_SESSION[JS_SAIK]["lang"].".php";
        return "lang_view_jointsite_module_".$_SESSION[JS_SAIK]["lang"];
    }

    function print_page_content()
    {
        $this->prod_about();
        $this->prod_menu();
        $this->prod_info();
        $this->prod_deploy();
        $this->principles_of_work();
    }

    function prod_menu()
    {
        echo "<div class='contentBlock-frame '><div class='contentBlock-center'>".
            "<div class='contentBlock-wrap'>".
            "<section class='prod-menu'>".
            "<h2>".$this->lang_map->prodmenu["h2_сontent"]."</h2>".
            "<ul>".
            "<li><a href='#product-info'>".$this->lang_map->prodmenu["h2_common"]."</a></li>".
            "<li><a href='#product-setup'>".$this->lang_map->prodmenu["h2_setup"]."</a></li>".
            "<li><a href='#principles_of_work'>".$this->lang_map->prodmenu["principles_of_work"]."</a></li>".
            "</ul>".
            "</section>".
            "</div></div></div>";

    }

    function principles_of_work()
    {
        echo "<div class='contentBlock-frame'><div class='contentBlock-center'>".
            "<div class='contentBlock-wrap'>".
            "<section class='prod-test'>".
            "<h2 id='principles_of_work'>".$this->lang_map->prodmenu["principles_of_work"]."</h2>".
            "<h3>".$this->lang_map->principles_of_work["h3-1"]."</h3>".
            "<h3>".$this->lang_map->principles_of_work["h3-2"]."</h3>".
            "</section>".
            "</div></div></div>";
    }
/*
    function prod_about()
    {
        echo "prod_about";
    }
*/
    function prod_deploy_server()
    {

    }
    /*
        function prod_deploy_migrations()
        {
            parent::prod_deploy_migrations(); // TODO: Change the autogenerated stub
            echo "<div class='example'>".
                "<div class='example-code'>".
                "CREATE DATABASE test_db CHARACTER SET utf8 COLLATE utf8_general_ci".
                "</div>".
                "<div class='example-text'>".
                "можно выполнить запрос для создания базы данных <span class='ex-conf'>test_db</span> в админке <span class='ex-conf'>/admin/sql</span>".
                "</div>".
                "</div>";

        }
    */


    function print_prod_branches()
    {
        $this->print_branch("module");
    }
    function prod_deploy_config()
    {
        echo "<h3>" . $this->lang_map->product_config["h3"] . "</h3>" .
            "<h4>Доступ к модулям в меню</h4>".
            "<p>".
            "в языковых файлах содержится описание всех пунктов меню. this->lang_map->menu_blocks[modules_menu][menu_items]".
            "в предствлении SiteView.php set_head_array вызывается перед выводом данных. ".

            "</p>".
            "<h4>Доступ к модулям в модели</h4>".
            "<p></p>";
    }

    /*
        function prod_deploy_config()
        {
            echo "<h3>".$this->lang_map->product_config["h3"]."</h3>".
                "<p>".
                $this->lang_map->product_config["p1"].
                "</p>";
            echo $this->prod_deploy_config_ex();
            echo "<p>".
                $this->lang_map->product_config["p3"].
                "</p>".
                "<div class='example'>".
                "<div class='example-code'>".
                "this->print_admin_menu('/admin')".
                "</div>".
                "<div class='example-text'>".
                $this->lang_map->product_config["example-text-3"].
                "</div>".
                "</div>";
            echo "<p>".
                $this->lang_map->product_config["p4"].
                "</p>".
                "<p>".
                $this->lang_map->product_config["p5"].
                "</p>".
                "<p>".
                $this->lang_map->product_config["p6"].
                "</p>";
        }*/
}