<?php
class view_jointsite_admin extends View_Products_JointSite
{
    public $current_branch = "admin";

    function LoadViewLang($request = null)
    {
        parent::LoadViewLang($request = null); // TODO: Change the autogenerated stub
        require_once $_SERVER["DOCUMENT_ROOT"].JOINT_SITE_EXEC_DIR."/application/lang_files/views/lang_view_jointsite_admin_".$_SESSION[JS_SAIK]["lang"].".php";
        return "lang_view_jointsite_admin_".$_SESSION[JS_SAIK]["lang"];
    }

    function prod_about()
    {

    }

    function prod_deploy_server()
    {

    }

    function prod_deploy_migrations()
    {
        parent::prod_deploy_migrations(); // TODO: Change the autogenerated stub
        echo "<div class='example'>".
        "<div class='example-code'>".
        "CREATE DATABASE test_db CHARACTER SET utf8 COLLATE utf8_general_ci".
        "</div>".
        "<div class='example-text'>".
        "можно выполнить запрос для создания базы данных <span class='ex-conf'>test_db</span> в админке <span class='ex-conf'>/admin/sql</span>".
        "</div>".
        "</div>";

    }



    function print_prod_branches()
    {
        $this->print_branch("admin");
        //parent::print_prod_branches(); // TODO: Change the autogenerated stub
    }

    function prod_info_custom()
    {
        parent::prod_info_custom();
        echo "<p>".$this->lang_map->product_custom["p1"]."</p>";
    }

    function prod_deploy_config()
    {
        echo "<h3>".$this->lang_map->product_config["h3"]."</h3>".
            "<p>".
            $this->lang_map->product_config["p1"].
            "<p>".
            $this->lang_map->product_config["p2"].
            "</p>".
            "<p>".
            $this->lang_map->product_config["p3"].
            "</p>";
    }
}