<?php


namespace JointApp\Views;


use JointApp\Interfaces\LangWebViewInterface;

class SiteView extends WebView
{
    //part of application basket
    public $serviceList = [];
    //pop arts
    public $popArts = [];

    public function addViewParams(callable $addViewParams)
    {
        parent::addViewParams($addViewParams); // TODO: Change the autogenerated stub
        $addParams = new \stdClass();
        $addParams->serviceList = $this->serviceList;
        $addParams->popArts = $this->popArts;
        $addViewParams($addParams);
    }

    public static function loadLangView(string $docRoot = __DIR__, string $viewLang = 'ru', $loads = []):LangWebViewInterface
    {
        $name = 'LangFiles_'.self::langNs($viewLang).'_Views_SiteView';
        $loads[] = [$name => $docRoot.'/JointApp/LangFiles/Views/'.$name];
        return parent::loadLangView($docRoot, $viewLang, $loads);
    }

    public static function addScriptLinks(callable $addScriptLinks): void
    {
        parent::addScriptLinks($addScriptLinks); // TODO: Change the autogenerated stub
        $addScriptLinks(['/lib/js/Elegant-Loading-Indicator-jQuery-Preloader/src/js/jquery.preloader.min.js']);
    }

    public static function addStyleLinks(callable $addStyleLinks): void
    {
        parent::addStyleLinks($addStyleLinks); // TODO: Change the autogenerated stub
        $addStyleLinks(['/lib/js/Elegant-Loading-Indicator-jQuery-Preloader/src/css/preloader.css']);
    }

    public static function createModalContent(\stdClass $langModal, \stdClass $viewParams):string
    {
        $return = self::modalMenuPopArts($langModal->blogMenuLine, $viewParams->popArts, $viewParams->langSl, $viewParams->routes_ns);
        //    self::modalMenuJointSite($langModal->jointSiteMenu, $viewParams->langSl, $viewParams->routes_ns)

        global $currentUser;
        if($currentUser->user_id == 'F42F81F8-1300-41CA-89BB-36BD7417BE1E'){
            $return .= self::modalMenuWebTests($langModal->webTestMenu, $viewParams->langSl, $viewParams->routes_ns);
        }
        $return .= self::modalMenuMusic($langModal->musicMenu, $viewParams->langSl);

        return $return;
    }

    private static function modalMenuPopArts(array $blogMenuLine, array $popArts,
                                             string $langSl = '', $routes_ns = ['', '']):string
    {
        $menuStyle = 'style="display: none"';
        $foldedStyle = 'folded';

        $menuItemsTxt = static::printMenuItems($popArts, '/blog/article', $langSl, $routes_ns);

        if ($menuItemsTxt['is_valid_path']) {
            $menuStyle = null;
            $foldedStyle = null;
        }

        $returnMenu = '<div class="modal-line prod">'.
            '<div class="modal-line-img"><img src="/img/popimg/blog-logo.png"></div>' .
            '<div class="modal-line-text"><a class="m-l-blue" href="'.$langSl.'/blog" '.
            'title="'.$blogMenuLine['refTitle'].'">'.
            $blogMenuLine['refText'].'</a><sup>'.
            $blogMenuLine['supText'].'</sup>'.
            '<span class="opnSubMenu '.$foldedStyle.'">'.$blogMenuLine['dropText'].'</span>'.
            '<ul '.$menuStyle.'>'.
            $menuItemsTxt['text'].
            '</ul>'.
            '</div>'.
            '</div>';
        return $returnMenu;
    }

    private static function modalMenuJointSite(\stdClass $jointSiteMenu, string $langSl = '', $routes_ns = ['', '']):string
    {
        $menuStyle = 'style="display: none"';
        $foldedStyle = 'folded';

        $menuItemsTxt = static::printMenuItems($jointSiteMenu->menuItems, '/jointsite', $langSl, $routes_ns);

        if ($menuItemsTxt['is_valid_path']) {
            $menuStyle = null;
            $foldedStyle = null;
        }

        $returnMenu = '<div class="modal-line prod">'.
            '<div class="modal-line-img"><img src="/img/popimg/internet.png"></div>' .
            '<div class="modal-line-text"><a class="m-l-blue" href="'.$langSl.'/jointsite" '.
            'title="'.$jointSiteMenu->menuLine['refTitle'].'">'.
            $jointSiteMenu->menuLine['refText'].'</a><sup>'.
            $jointSiteMenu->menuLine['supText'].'</sup>'.
            '<span class="opnSubMenu '.$foldedStyle.'">'.$jointSiteMenu->menuLine['dropText'].'</span>'.
            '<ul '.$menuStyle.'>'.
            $menuItemsTxt['text'].
            '</ul>'.
            '</div>'.
            '</div>';
        return $returnMenu;
    }

    private static function modalMenuWebTests(\stdClass $webTestMenu,
                                              string $langSl = '', $routes_ns = ['', '']):string
    {
        $menuStyle = 'style="display: none"';
        $foldedStyle = 'folded';

        $menuItemsTxt = static::printMenuItems($webTestMenu->menuItems, '/test', $langSl, $routes_ns);

        if ($menuItemsTxt['is_valid_path']) {
            $menuStyle = null;
            $foldedStyle = null;
        }

        $returnMenu = '<div class="modal-line prod">'.
            '<div class="modal-line-img"><img src="/img/popimg/test-logo.png"></div>' .
            '<div class="modal-line-text"><a class="m-l-blue" href="'.$langSl.'/test" '.
            'title="'.$webTestMenu->menuLine['refTitle'].'">'.
            $webTestMenu->menuLine['refText'].'</a><sup>'.
            $webTestMenu->menuLine['supText'].'</sup>'.
            '<span class="opnSubMenu '.$foldedStyle.'">'.$webTestMenu->menuLine['dropText'].'</span>'.
            '<ul '.$menuStyle.'>'.
            $menuItemsTxt['text'].
            '</ul>'.
            '</div>'.
            '</div>';

        return $returnMenu;
    }


    private static function modalMenuMusic(\stdClass $musicMenu, string $langSl = ''):string
    {
        return '<div class="modal-line">'.
            '<div class="modal-line-img"><img src="/img/popimg/music-logo.png"></div>'.
            '<div class="modal-line-text"><a class="m-l-blue" href="'.$langSl.'/music/playalbum/my-fav-music" '.
            'title="'.$musicMenu->link_title.'">'.
            $musicMenu->link_text.
            '</a></div>'.
            '</div>';
    }
}