<?php


namespace JointApp\Controllers\User;

use JointApp\Factories\ModelFactory;
use JointApp\Factories\MailFactory;
use JointApp\JointAppMailer;


class Controller_User_Email extends Controller_User_Account
{
    public string $eMail_new = '';

    public function controllerFilterBody($bodyParams = []): void
    {
        parent::controllerFilterBody($bodyParams); // TODO: Change the autogenerated stub

        if(isset($bodyParams['eMail_new'])){
            $this->eMail_new = $bodyParams['eMail_new'];
        }
    }

    public function loadLangController(): string
    {

        parent::loadLangController();

        $name = 'LangFiles_'.$this->langNs.'_Controller_User_Email';
        require_once $this->docRoot.'/JointApp/LangFiles/Controllers/User/'.$name.'.php';
        return $name;
    }

    public function actionGetChangeEmail()
    {
        global $currentUser;

        $this->model->getUser($currentUser->user_id);

        $this->view->h2 = $this->langMap->h2;
        $this->view->process_url = '';
        $this->view->fieldAliases = [];
        $this->view->actionResult = null;
        $this->view->logMessage = '';
        $this->prepareEditFields();
        $this->updateEditFieldsFromRecord();

        $this->view->editFields = $this->editFields;
        $this->view->type = 'edit';
    }

    public function prepareEditFields(): void
    {
        $this->editFields = array(
            'eMail' => array(
                'format' => 'varchar',
                'curVal' => '',

            ),
            'eMail_new' => array(
                'format' => 'varchar',
                'curVal' => '',
            ),
        );
    }

    public function actionPostChangeEmail()
    {
        global $currentUser;

        if($this->model->getUser($currentUser->user_id)){

            if($this->model::checkUserEmail($this->eMail_new)){
                if($this->eMail_new != $this->model->record['eMail']['curVal']){
                    $this->model->record['eMail']['curVal'] = $this->eMail_new;
                    if($this->model->updateRecord()){
                        $this->eMail_new = '';

                        $model_Pdo = ModelFactory::createFromExistModel('JointApp\Models\Model_Pdo', $this->model);

                        $phpMailer = MailFactory::getMailer($this->getConfigDir());

                        $mailer = new JointAppMailer($phpMailer,$model_Pdo);


                        $replaces = [
                            'accAlias' => $currentUser->accAlias,
                            'accLogin' => $currentUser->accLogin,
                            'newUserEmail' => $this->model->record['eMail']['curVal'],
                        ];

                        $mailer->addNotification('changeEmailForUser',
                            'user',
                            $currentUser->user_id,
                            json_encode($replaces, JSON_UNESCAPED_UNICODE ),
                            true,
                            null);

                    }else{
                        $this->logger->error('Model_User_Main getUser return false on actionPostUserMain', $this->logger->logger_context);
                    }
                }else{
                    $this->view->logMessage = 'curren and emails equals';
                }
            }else{
                $this->view->logMessage = 'email unacceptable';
            }
            $this->view->h2 = $this->langMap->h2;
            $this->view->process_url = '';
            $this->view->fieldAliases = [];
            $this->view->actionResult = true;
            $this->prepareEditFields();
            $this->updateEmailEditFieldsFromRecord();
            $this->view->editFields = $this->editFields;
            $this->view->fieldAliases = $this->langMap->fieldAliases;
            $this->view->type = 'edit';
        }else{
            $this->logger->error('Model_User_Main getUser return false on actionPostUserMain', $this->logger->logger_context);
        }
    }

    public function updateEmailEditFieldsFromRecord(): bool
    {

        //parent::updateEditFieldsFromRecord();
        $this->editFields['eMail_new']['curVal'] = $this->eMail_new;

        $this->editFields['eMail']['curVal'] = $this->model->record['eMail']['curVal'];

        return true;
    }
}