<?php


namespace JointApp\Controllers\User;


use JointApp\JointAppQueryBuilder;

class Controller_User_Notifications extends Controller_User_Account
{
    public string $ntf_id = '';

    public string $processUri = '/user/notifications';

    public function loadLangController(): string
    {

        parent::loadLangController();

        $name = 'LangFiles_'.$this->langNs.'_Controller_User_Notifications';
        require_once $this->docRoot.'/JointApp/LangFiles/Controllers/User/'.$name.'.php';
        return $name;
    }

    public function controllerFilterQuery($queryParams = []): void
    {
        parent::controllerFilterQuery($queryParams); // TODO: Change the autogenerated stub

        if(isset($queryParams['ntf_id']) and !empty($queryParams['ntf_id'])){
            $this->ntf_id = $queryParams['ntf_id'];
        }
    }

    public function actionGetUserNtfList()
    {
        $this->prepareSearchFields();
        $this->prepareEditFields();
        $this->updateModelPriKeysFromRequest();
        $this->updateModelRecordFromRequest();
        $this->updateSearchFieldsFromRecord();
        $qBuilderList = $this->filterWhere();
        $this->view->listRecords = $this->model->listRecords($qBuilderList);
        $qBuilderCount = clone $qBuilderList;
        $qBuilderCount
            ->limit('')
            ->order('');

        $this->view->listCount = $this->model->countRecords($qBuilderCount);

        $this->prepareListFields();
        $this->prepareSearchFields();
        $this->view->listFields = $this->listFields;
        $this->view->searchFields = $this->searchFields;
        $this->view->fieldAliases = $this->langMap->fieldAliases;
        $this->view->list_frame_id = $this->model->tableName;
        $this->view->process_url = $this->processUri;

        $this->view->h2 = $this->langMap->h2;

        $this->view->hasAccessCreate = false;
    }

    public function prepareListFields():void
    {
        $this->listFields = array(
            'btnDetail' => Array
            (
                'replaces' => Array('ntf_id', ),
                'format' => 'link',
                'url' => 'ntf_id=ntf_id',
            ),

            'tHeader' => array(
                'format' => 'varchar',
            ),
            'subscriber_type' => array(
                'format' => 'varchar',
            ),
            'ntf_id' => array(
                'format' => 'hidden',
            ),
            'user_id' => array(
                'format' => 'hidden',
            ),
            'read_date' => array(
                'format' => 'datetime',
            ),
            'put_date' => array(
                'format' => 'datetime',
            ),
            'send_flag' => array(
                'format' => 'tinyint',
            ),
            'btnDelete' => Array
            (
                'replaces' => Array('ntf_id', ),
                'format' => 'link',
                'url' => 'ntf_id=ntf_id',
            ),
            /*
            'del_flag' => array(
                'format' => 'tinyint',
            ),*/
        );
    }

    public function prepareSearchFields():void
    {
        $this->searchFields = array(
            'put_date' => array(
                'format' => 'datetime',
                'sort' => 1,
                'sortOrder' => 'DESC',
                'curVal' => '',
            ),
            'read_date' => array(
                'format' => 'datetime',
                'sort' => 1,
                'curVal' => '',
            ),
            'tHeader' => array(
                'format' => 'varchar',
                'search' => 1,
                'sort' => 1,
                'curVal' => '',
                'group_by_field' => 'tHeader',
            ),
            'subscriber_type' => array(
                'format' => 'varchar',
                'search' => 1,
                'sort' => 1,
                'curVal' => '',
                'use_table_name' => 'ntfList_dt',
                //'custom' => false,
            ),
            /*
            'ntf_id' => array(
                'format' => 'varchar',
                'search' => 1,
                'sort' => 1,
                'curVal' => '',
                //'custom' => false,
            ),
            'user_id' => array(
                'format' => 'varchar',
                'search' => 1,
                'sort' => 1,
                'curVal' => '',
            ),

            'send_flag' => array(
                'format' => 'tinyint',
                'search' => 1,
                'sort' => 1,
                'curVal' => '',
            ),*/
            /*'del_flag' => array(
                'format' => 'tinyint',
                'search' => 1,
                'sort' => 1,
                'curVal' => '',
            ),*/
        );
    }

    public function actionGetUserNtfDetail()
    {
        global $currentUser;
        if(!empty($this->ntf_id)){

            $this->model->record['ntf_id']['curVal'] = $this->ntf_id;
            $this->model->record['user_id']['curVal'] = $currentUser->user_id;
            if($this->model->copyRecord()){
                if(empty($this->model->record['read_date']['curVal'])){
                    $this->model->record['read_date']['curVal'] = date('Y-m-d H:i:s');
                    $this->model->updateRecord();
                }
                $this->prepareViewFields();
                $this->view->viewFields = $this->viewFields;
                $this->updateViewFieldsFromRecord();
                $this->prepareViewParams();

            }else{
                $this->logger->emergency($this->model->log_message,
                    $this->logger->logger_context);
            }


        }else{
            $this->logger->error('empty ntf_id on actionGetUserNtfDetail', $this->logger->logger_context);
        }
        $this->view->h2 = $this->langMap->h2_read;
    }

    public function prepareViewFields(): void
    {
        $this->viewFields = array(
            'ntf_id' => array(
                'format' => 'hidden',
                'readonly' => true,
            ),
            'user_id' => array(
                'format' => 'hidden',
                'readonly' => true,
            ),
            'read_date' => array(
                'format' => 'datetime',
                'readonly' => true,
            ),
            'put_date' => array(
                'format' => 'datetime',
                'readonly' => true,
            ),
            'send_flag' => array(
                'format' => 'tinyint',
                'readonly' => true,
            ),
            'del_flag' => array(
                'format' => 'tinyint',
                'readonly' => true,
            ),
            'subscriber_type' => array(
                'format' => 'varchar',
                'readonly' => true,
            ),
            'tName' => array(
                'format' => 'varchar',
                'readonly' => true,
            ),
            'tHeader' => array(
                'format' => 'varchar',
                'readonly' => true,
            ),
            'tBody' => array(
                'format' => 'email',
                'style' => array(
                    'class' => 'wd100',
                ),
                'replaces' => [],
                'readonly' => true,
            ),
        );
    }

    public function updateViewFieldsFromRecord(): void
    {
        parent::updateViewFieldsFromRecord(); // TODO: Change the autogenerated stub

        $this->view->viewFields['tBody']['template_params'] = $this->model->record['tBody']['template_params'];
    }

    public function deleteNotification()
    {
        global $currentUser;
        if(!empty($this->ntf_id)){

            $this->model->record['ntf_id']['curVal'] = $this->ntf_id;
            $this->model->record['user_id']['curVal'] = $currentUser->user_id;
            if($this->model->copyRecord()){
                $this->model->record['del_flag']['curVal'] = true;
                $this->model->updateRecord();
                $this->logger->redirect($this->langSl.'/user/notifications/');
            }else{
                $this->logger->emergency($this->model->log_message,
                    $this->logger->logger_context);
            }
        }else{
            $this->logger->error('empty ntf_id on actionGetUserNtfDetail', $this->logger->logger_context);
        }
    }
}