<?php


namespace JointApp\Models;


use JointApp\ModulesAccessList;
use JointApp\Models\Records\RecordsModel;

class ModuleModel extends RecordsModel
{
    protected $accessGroups = [];
    public string $moduleName = '';

    public $access_rules = array(
        'read_rule' => 0,
        'create_rule' => 0,
        'edit_rule' => 0,
        'delete_rule' => 0,
    );

    public function checkAccessModel(): bool
    {

        $this->accessGroups = ModulesAccessList::getAccessList()[$this->moduleName];

        $user_m = ModulesAccessList::getUserModules();

        if(!in_array($this->moduleName, $user_m)){
            return false;
        }

        global $currentUser;

        if($currentUser->is_admin == true){
            $this->access_rules = array(
                'read_rule' => 7,
                'create_rule' => 7,
                'edit_rule' => 7,
                'delete_rule' => 7,
            );
            return true;
        }
        $access_key_val = array(
            'any' => 7,
            'own' => 2,
            'enable' => 7,
            'disable' => 0,
            'forbidden' => 0,
            '' => 0,
            null => 0,
        );

        if($this->accessGroups){
            if(isset($currentUser->groups)){
                foreach ($currentUser->groups as $group_id => $access_rules){
                    if(in_array($group_id, $this->accessGroups)){
                        foreach ($this->access_rules as $return_u_rule => $return_u_val){
                            if($access_key_val[$access_rules[$return_u_rule]] > $this->access_rules[$return_u_rule]){
                                $this->access_rules[$return_u_rule] = $access_key_val[$access_rules[$return_u_rule]];
                            }
                        }
                    }
                }
            }
        }else{
            $this->access_rules = array(
                "read_rule" => 7,
                "create_rule" => 7,
                "edit_rule" => 7,
                "delete_rule" => 7,
            );
        }

        if(!$this->access_rules["read_rule"]){
            $this->logger->warning('denied in ModuleModel', $this->logger->logger_context);
            return false;
        }
        return true;
    }

    public function insertRecord(): bool
    {
        global $currentUser;

        $this->record['created_by']['curVal'] = $currentUser->user_id;
        return parent::insertRecord(); // TODO: Change the autogenerated stub
    }
}