<?php


namespace JointApp\Models;


use JointApp\ModulesAccessList;
use JointApp\Models\Records\RecordsModel;
use JointApp\JointAppQueryBuilder;

class ModuleModel extends RecordsModel
{
    protected $accessGroups = [];
    public string $moduleName = '';

    public $access_rules = array(
        'read_rule' => 0,
        'create_rule' => 0,
        'edit_rule' => 0,
        'delete_rule' => 0,
    );

    public function checkAccessModel(): bool
    {
        $modulesAccessGroups = ModulesAccessList::getAccessList();
        if(!isset($modulesAccessGroups[$this->moduleName])){
            $this->logger->warning('checkAccessModel: moduleName is not set in module model',
                $this->logger->logger_context);
            return false;
        }

        $user_m = ModulesAccessList::getUserModules();

        if(!in_array($this->moduleName, $user_m)){
            return false;
        }

        global $currentUser;

        if($currentUser->is_admin == true){
            $this->access_rules = array(
                'read_rule' => 7,
                'create_rule' => 7,
                'edit_rule' => 7,
                'delete_rule' => 7,
            );
            return true;
        }
        $access_key_val = array(
            'any' => 7,
            'own' => 2,
            'enable' => 7,
            'disable' => 0,
            'forbidden' => 0,
            '' => 0,
            null => 0,
        );

        if($this->accessGroups){
            if(isset($currentUser->groups)){
                foreach ($currentUser->groups as $group_id => $access_rules){
                    if(in_array($group_id, $this->accessGroups)){
                        foreach ($this->access_rules as $return_u_rule => $return_u_val){
                            if($access_key_val[$access_rules[$return_u_rule]] > $this->access_rules[$return_u_rule]){
                                $this->access_rules[$return_u_rule] = $access_key_val[$access_rules[$return_u_rule]];
                            }
                        }
                    }
                }
            }
        }else{
            $this->access_rules = array(
                "read_rule" => 7,
                "create_rule" => 7,
                "edit_rule" => 7,
                "delete_rule" => 7,
            );
        }

        if(!$this->access_rules["read_rule"]){
            $this->logger->warning('denied in ModuleModel', $this->logger->logger_context);
            return false;
        }
        return true;
    }

    public function insertRecord(): bool
    {
        global $currentUser;

        if($this->hasAccessCreate()){
            $this->record['created_by']['curVal'] = $currentUser->user_id;
            return parent::insertRecord(); // TODO: Change the autogenerated stub
        }else{
            $this->logger->warning('denied in ModuleModel on insertRecord', $this->logger->logger_context);
        }

    }

    public function copyRecord():bool
    {
        global $currentUser;

        if(parent::copyRecord()){
            if($this->access_rules['read_rule']<3){
                if ($this->access_rules['read_rule'] == 2) {
                    if($this->record['created_by']['curVal'] == $currentUser->user_id){
                        return true;
                    }else{
                        echo 'case-1';
                        exit;
                        //jointSite::throwErr("access", "access denied in ModuleRecordsModel copyRecord on user_id");
                    }
                }else{
                    echo 'case-2';
                    exit;
                    //jointSite::throwErr("access", "access denied in ModuleRecordsModel copyRecord on edit_rule: ".$this->access_rules["read_rule"]);
                }
            }
            return true;
        }else{
            return false;
        }
    }

    public function updateRecord(): bool
    {
        global $currentUser;

        $update = false;
        if($this->access_rules['edit_rule'] == 7){
            $update = true;
        }elseif($this->access_rules['edit_rule'] == 2){
            if($this->record['created_by']['curVal'] == $currentUser->user_id){
                $update = true;
            }
        }

        if($update){
            $update = parent::updateRecord(); // TODO: Change the autogenerated stub
        }else{
            $this->logger->warning('denied in ModuleModel updateRecord', $this->logger->logger_context);
        }
        return $update;
    }

    public function listRecords(JointAppQueryBuilder $qBuilder):array
    {
        $qBuilder = $this->createdByListWhere($qBuilder);
        return $this->checkListButtons(parent::listRecords($qBuilder));
    }

    public function createdByListWhere(JointAppQueryBuilder $qBuilder):JointAppQueryBuilder
    {
        global $currentUser;
        if($this->access_rules["read_rule"] > 2){
            return $qBuilder;
        }elseif($this->access_rules["read_rule"] == 2){
            if($qBuilder->where){
                $qBuilder->where.= " and ";
            }
            $qBuilder->where.= $this->tableName.".created_by = '".$currentUser->user_id."'";
            return $qBuilder;
        }else{
            $this->logger->warning('denied in ModuleModel on createdByListWhere', $this->logger->logger_context);
        }
        return $qBuilder;
    }

    public function checkListButtons(array $listRecords = []):array
    {
        global $currentUser;
        if($this->access_rules["edit_rule"] > 2 and $this->access_rules["delete_rule"] > 2){
            //return $return_access_listRecords;
        }else{
            if($listRecords){
                foreach ($listRecords as $row_num => $row){
                    $check_read = true;
                    if ($this->access_rules["read_rule"] < 3) {
                        if ($this->access_rules["read_rule"] == 2) {
                            if ($row["created_by"] != $currentUser->user_id) {
                                $check_read = false;
                            }
                        }
                    }

                    if($check_read == true){
                        if ($this->access_rules["edit_rule"] < 3) {
                            if ($this->access_rules["edit_rule"] == 2) {
                                if ($row["created_by"] != $currentUser->user_id) {
                                    $listRecords[$row_num]["btnEdit"] = "disabled";
                                }

                            } else {
                                $listRecords[$row_num]["btnEdit"] = "disabled";
                            }

                        }
                        if ($this->access_rules["delete_rule"] < 3) {
                            if ($this->access_rules["delete_rule"] == 2) {
                                if ($row["created_by"] != $currentUser->user_id) {
                                    $listRecords[$row_num]["btnDelete"] = "disabled";
                                }

                            } else {
                                $listRecords[$row_num]["btnDelete"] = "disabled";
                            }

                        }
                    }else{
                        unset($listRecords[$row_num]);
                    }
                }
            }
        }

        return $listRecords;
    }

    public function hasAccessCreate():bool
    {
        if($this->access_rules['create_rule'] < 2){
            return false;
        }
        return true;
    }

    public function hasAccessDelete():bool
    {
        global $currentUser;

        if($this->access_rules['delete_rule'] == 7){
            return true;
        }elseif($this->access_rules['delete_rule'] == 2){
            if($this->record['created_by']['curVal'] == $currentUser->user_id){
                return true;
            }
        }
        return false;
    }

    public function deleteRecord()
    {
        if($this->hasAccessDelete()){
            return parent::deleteRecord(); // TODO: Change the autogenerated stub
        }else{
            $this->logger->warning('denied in ModuleModel deleteRecord', $this->logger->logger_context);
        }

    }


}